#!/bin/bash

.  /etc/common.rc
cd ${CWD}


function fn_addr2caller()
{
    if [ ! -f "${1}" ]; then
        echo "file[${1}] not exist"; exit
    fi
    tac='/tmp/tac'
    tac ${1} > ${tac}

    if [ -n "${2}" ]; then
        echo ${@:2} | xargs -n1 | {
        while read ADDR; do 
            sed -n "/^ *${ADDR}/,/>:/p" ${tac} | awk -F'[<>]' -v addr=$ADDR 'END {print addr,$2}'
        done
        }
    else
        cat /dev/stdin | {
        while read ADDR; do 
            sed -n "/^ *${ADDR}/,/>:/p" ${tac} | awk -F'[<>]' -v addr=$ADDR 'END {print addr,$2}'
        done
        }
    fi
}

function fn_addr2func()
{
    if [ ! -f "${1}" ]; then
        echo "file[${1}] not exist"; exit
    fi
    asm="${1}"

    if [ -n "${2}" ]; then
        echo ${@:2} | xargs -n1 | {
        while read ADDR; do 
            grep "^0*$ADDR <" ${asm} |  awk -F'[<>]' '{print $1,$2}'
        done
        }
    else
        cat /dev/stdin | {
        while read ADDR; do 
            grep "^0*$ADDR <" ${asm} |  awk -F'[<>]' '{print $1,$2}'
        done
        }
    fi
}

function fn_install_info()
{
    # stackoverflow
    # where-are-info-document-files-in-mac-or-in-linux-and-how-can-i-install-some-missing-info-files
    [ -n "${1}" ]
    xt_ret $? "" || return $?

    app=$1
    mkdir -p /root/info
    cd /root/info
    wget https://www.gnu.org/software/$app/manual/$app.info.tar.gz
    xt_ret $? "" || return $?

    tar xf $app.info.tar.gz
    xt_ret $? "" || return $?

    gzip $app.info
    chmod 644 $app.info.gz
    chown root:root $app.info.gz

    mkdir -p /usr/share/info
    mv $app.info.gz /usr/share/info

    # generate a hypertext link to $app in the info top page:
    ginstall-info --info-dir=/usr/share/info --info-file=/usr/share/info/$app.info.gz

    #info $app
    pinfo $app
}

function fn_main() 
{
    cmdlist=(
    # fixed sequence
    "addr2caller .ASM       # name -> function name() { cat name ;}"
    "addr2func   .ASM       # bakeup files in /root"

    # volatile sequence 
    "install_info"
    )

    fn_execute "$@"
}

asm='/root/c/thd.wrap/.asm'

fn_main "$@"
