#! /bin/sh

. ~/bin/common.rc

array=(
    SHOW_This_usage                                             NULL
    ax.cc/gcc-linaro-7.5.0-2019.12-x86_64_arm-linux-gnueabihf   爱芯
    augentix.cc/arm-linux-gnueabihf-4.8.3-201404                df
)

help_show()
{
    echo -e "\n   Usage:"
    local i
    for (( i=0; i<${#array[@]}; i+=2 )); do
        compile=${array[$i]}
        let j=i+1
        let No=i/2
        printf "\t%-4d%-52s\t# %s\n" $No $compile ${array[$j]}
    done

    return;
}

fn_main()
{
    arm_cc='/opt'
    lnk_cc='/opt/arm.cc/gcc/bin'

    case ${1:-0} in
    0)
        help_show

        [ -e "${lnk_cc}" ] && {
            local i
            for (( i=2; i<${#array[@]}; i+=2 )); do
                let j=i+1
                ls -l ${lnk_cc} | grep -q ${array[$i]} && { curr=${array[$j]}; break ;}
            done
        } || curr=NONE
        echo "
        curr: ${curr:-____not_match_any____}
        "
        return
        ;;
    [1-9])
        rm -f ${lnk_cc}
        No=$1*2
        [ -e "${arm_cc}/${array[$No]}/bin" ]
        xt_ret $? "Not exist: ${arm_cc}/${array[$No]}/bin" || return $?
        ln -sf ${arm_cc}/${array[$No]}/bin ${lnk_cc}
        let No++
        echo "
        link ${array[$No]} succ
        "
        ;;                         
    *)
        help_show
        return
        ;;
    esac
}

fn_main $@
