#!/bin/bash
#
# a single tool is easy to be forgotten
#

shopt -s gnu_errfmt
shopt -s extglob

function xt_ret() { [ "${1}" -eq 0 ] || echo ${@:2}; return ${1}; }

function fn_exe_usage()
{
    echo "
    call from $@
    ${0##*/} <id> [OPTIONS...]
    ${0##*/} keyword_in_list
    ${0##*/} {-l | --list}
    ${0##*/} / keyword
    "
    exit 1
}

function fn_execute()
{
    case $1 in
    ''|l|-l|--list)
        echo "$helpmsg"
        local idx
        for (( idx=0; idx<${#cmdlist[@]}; idx+=1 )); do
            printf "  %-4s%s\n" $idx "${cmdlist[${idx}]}"
        done
        echo
        ;;
    +([0-9]))
        [ $1 -ge ${#cmdlist[@]} ] && \
        fn_execute --list && fn_echo_fail "  -- fn_execute $1 too big --\n" && return

        cmd=${cmdlist[$1]/ */}
        fn_${cmd} "${@:2}"
        ;;
    /)
        local idx
        for (( idx=0; idx<${#cmdlist[@]}; idx+=1 )); do
            printf "  %-4s%s\n" $idx "${cmdlist[${idx}]}"
        done | grep --color "${@:2}"
        ;;
    *)
        local idx
        for (( idx=0; idx<${#cmdlist[@]}; idx+=1 )); do
            cmd=${cmdlist[${idx}]/ */}
            if [ "$1" = "${cmd}" ] ; then
                fn_${cmd} "${@:2}"
                return $?            # avoid _fn_exe_usage_
            fi
        done
        fn_exe_usage "${BASH_SOURCE[1]##*/}|${BASH_LINENO[0]}|"
        ;;
    esac
}

# --------------------- common part ---------------------------------------

function fn_md_table()
{
    mkdir -p /winc/
    temp='/tmp/.mdtable'

    [ -f "${1}" ] || { echo "Usage: do_table FILE"; exit ;}

    grep -q -- '\* \* \*' $1 && sed -i '0,/\* \* \*/d' $1 
    cp $1 /tmp/.bbox.1
    grep '^##* ' $1 | sed 's/  *$//g' > ${temp}

    while read; do
        if [ "${REPLY:2:1}" = '#' ]; then
            sym=${REPLY:4}
            id=`echo $sym | tr -d . | tr ' ' - | tr '[A-Z]' '[a-z]'`
            echo "        *   [$sym](#${id})"
        elif [ "${REPLY:1:1}" = '#' ]; then
            sym=${REPLY:3}
            id=`echo $sym | tr -d . | tr ' ' - | tr '[A-Z]' '[a-z]'`
            echo "    *   [$sym](#${id})"
        else
            sym=${REPLY:2}
            id=`echo $sym | tr -d . | tr ' ' - | tr '[A-Z]' '[a-z]'`
            echo "* [$sym](#${id})"
        fi
    done < ${temp} > /winc/xm.txt

    echo >> /winc/xm.txt
    
    cat <<-"HERE"  >> /winc/xm.txt
	* * *
	HERE

    cat ${1} >> /winc/xm.txt
    cp /winc/xm.txt ${1}
}

function fn_main() 
{
    cmdlist=(
    "md_table FILE.md       # create content table on gitee.com"
    )

    fn_execute "$@"
}

fn_main "$@"
