#! /bin/bash

function fn_main()
{
    case $1 in
    +|s|sum)
        let sum=0
        for i in ${@:2}; do
            let sum=sum+$i
        done
        echo $sum
        ;;
    x|m|mul)
        # 取消使用通配符
        set -f
        let mul=1
        for i in ${@:2}; do
            let mul=mul*$i
        done
        echo $mul
        ;;
    ''|h|help)
        echo -e "\nUsage:"
        echo -e "    <set -f> to disable \*"
        echo -e "    Calc {+|x} num..."
        echo -e "    Calc statements            # envvar: SCALE=10\n"
        ;;
    *)
        echo "scale=${SCALE:-10}; $*" | bc -l 
        ;;
    esac
}

fn_main $1 "${@:2}"
