#! /bin/bash

function fn_main()
{
    case $1 in
    +|s|sum)
        let sum=0
        for i in ${@:2}; do
            let sum=sum+$i
        done
        echo $sum
        ;;
    x|m|mul)
        let mul=1
        for i in ${@:2}; do
            let mul=mul*$i
        done
        echo $mul
        ;;
    eh|eH|ef)
        min=`bc -l <<< "scale=0; $2 + (240-$2)*0.368/1" `
        [ "${1}" = ef ] && tag=fast
        echo ${min} min after  09:30 AM, ${tag:-__buying__} @
        if [ "${min}" -lt 120 ]; then
            date --date="09:30:00 ${min} minute" +'%T'
        else
            let min=min-120
            date --date="13:00:00 ${min} minute" +'%T'
        fi
        ;;
    el|eL|es)
        min=`bc -l <<< "scale=0; 240 - ($2+(240-$2)*(1-0.368))/1"`
        [ "${1}" = es ] && tag=slow
        echo ${min} min before 03:00 PM, ${tag:-__selling__} @
        if [ "${min}" -lt 120 ]; then
            date --date="15:00:00 ${min} minute ago" +'%T'
        else
            let min=min-120
            date --date="11:30:00 ${min} minute ago" +'%T'
        fi
        ;;
    ''|h|help)
        echo -e "\nUsage:"
        echo "\
        Calc +  num...              # sum
        Calc x  num...              # multiple

        Calc {eH|ef} minutes        # fast .367, High time to get buy  minutes after  09:30 AM
        Calc {eL|es} minutes        # slow .633, Low  time to get sell minutes before 03:00 PM
                                    # 09:30 低开机率70%, 10:05 11:00 14:00 14:35

        <set -f> to disable \*
        SCALE=10 to set scale
        "
        ;;
    *)
        echo "scale=${SCALE:-10}; $*" | bc -l 
        ;;
    esac
}

fn_main $1 "${@:2}"
