#! /bin/bash

function fn_main()
{
    case $1 in
    s|sum)
        let sum=0
        for i in ${@:2}; do
            let sum=sum+$i
        done
        echo $sum
        ;;
    x|m|mul)
        # 取消使用通配符
        set -f
        let mul=1
        for i in ${@:2}; do
            let mul=mul*$i
        done
        echo $mul
        ;;
    h|help)
        echo -e "\nUsage:"
        echo -e "    Calc {sum|mul} dig..."
        echo -e "    Calc statements # SCALE=3\n"
        ;;
    *)
        set -f
        bc -l <<< "scale=${SCALE:-3}; $*"
        ;;
    esac
}

fn_main $@
