#! /bin/sh

set -x

IPC=${IPC:-192.168.9.111}

if [ -z "$1" ]; then
    echo "list" | nc ${IPC} 9999 | sed -e 's/;/\n/g' -e 's/.*ccess]/____:\n/g' | sort
    echo "
    Usage: IPC=xxx ccli cmd...
    "
else
    echo "$*" | timeout 5 nc ${IPC} 9999 | sed -e 's/;/\n/g' -e 's/ccess]/&\n/g'
fi

