#!/bin/bash -
#-----------------------------------------------------------------------------
#          FILE: csgen
#   DESCRIPTION: Generate ${reffile} for cscope
#        AUTHOR: moo (God helps those who help themselves) 
#       CREATED: 2012-05-24 11:29:59 HKT
#      REVISION: 1.0 
#-----------------------------------------------------------------------------

PS8="eval echo \${BASH_SOURCE##*/}\|\$LINENO\|: "
xert() { [ "${1}" -eq 0 ] || echo ${@:2}; return ${1}; }


function fn_usage()
{
    cat <<-HERE
    Usage: ${0##*/} [OPTION]
    Generate ${reffile} for cscope

        -h, --help          show usage
        -r, --remove        remove ${reffile}* b4 cscope -Rbq
        -i, --interactive   vi ${cspathes} of project b4 cscope -Rbq
        -f, --filelist      rebuild ${reffile} __without__ update ${csfiles}
        -u,                 Unconditionally rebuild ${reffile} and __update__ ${csfiles} FROM ${cspathes}

    Configuration:
        .cscope.pathes, include path or exclude pathes
        head with -, support all kinds of pathes like: '' '/' './' '../'
	HERE

    exit 0
}

function fn_main()
{
    cpplang=(
        # *.c is default
        '*.h'
        '*.cpp'
        '*.cc'
        '*.xx'
        # include
        '*.hh'
        '*.hpp'
        '*.inc'
    )

    reffile=.cscope.out
    csfiles=.cscope.files
   cspathes=.cscope.pathes
    exclude='(||)'  # grep -E -v "${exclude}"
   namepatt="-iname '*.c' -print"
    incpath='-I/usr/local/include'

    if [ -f ${reffile} ] && lsof ${reffile} >& /dev/null; then
        echo "
        -----------------------------------------------------

        Another cscope is running! Please exit it first...

        -----------------------------------------------------
        "
        sleep 1 && exit
    fi

    case "$1" in
        -h|--help|h)        fn_usage                            ;;
        -i|--interactive)   vi ${cspathes}                      ;;
        -u) force=$1                                            ;;
        -f) cscope ${incpath} -bq -i$csfiles -f${reffile}
            exit 0                                              ;;
            # -k turns off the use of [/usr/include]
        -r|--remove)
            echo "------------------------------------"
            echo "RM ${reffile%%.out}.* but keep ${cspathes}"
            ls ${reffile%%.out}* | grep -v pathes | xargs rm -rf
            exit 0                                              ;;
        *)  ;;
    esac

    local idx
    for (( idx=0; idx<${#cpplang[@]}; idx+=1 )); do
        namepatt="${namepatt} -o -iname '${cpplang[$idx]}' -print"
    done

    [ ! -f "$cspathes" ] && > ${cspathes} && vi ${cspathes}

    # exclude line start with '-'
    exclude_path=`grep "^-" $cspathes | sed 's/^- *//g'`

    if [ -n "$exclude_path" ]; then
        for x_path in $exclude_path; do
            # -path -prune must begin with '/' './' '../' and 
            #               not end with '/'
            x_path=${x_path%/}
            if [ "${x_path:0:1}" != '/' ] && [ "${x_path:0:3}" != '../' ]; then
                x_path=./${x_path#./}
            fi
            [ ! -e "$x_path" ] && echo $x_path not exist && exit 1
            echo "skip path $x_path"
            exclude_opt="$exclude_opt -path '$x_path' -prune -o"
        done
    fi

   #     find [path1] [path2] [path3] -name <name>
   #echo find . $exclude_opt $namepatt 
    eval find . $exclude_opt $namepatt > $csfiles
    xert $? `$PS8` "find" || return $?

    while read srcpath; do
        [ -z "$srcpath" ] && continue
        [ "${srcpath:0:1}" == '-' ] && continue

        # 应用于文件夹与文件在同一目录的情况，如 http下 httpd*.c onvif: 
        # Format: pathname -maxdepth 1
        [ ! -d "${srcpath%% *}" ] && echo "$srcpath: No such directory" && exit 0

        # echo \
        #    find ${srcpath} ${exclude_opt} $namepatt >> $csfiles"
        eval find ${srcpath} ${exclude_opt} $namepatt >> $csfiles
    done < $cspathes

    sort -u $csfiles -o $csfiles
    echo "building cscope db."
    cscope ${incpath} ${force} -bq -i $csfiles -f${reffile} 
}

fn_main $@
