#!/usr/bin/expect -f
#
# spacial [] {} etc. can't be put after telnet
#
if { $argc == 0 } {
    puts "Usage: $argv0 ip port"
    exit -1
} else {
    set ip   [ lrange $argv 0 0 ]
    set port 24

    if { $argc == 2 } {
        set port [ lrange $argv 1 1 ]
    }

    if { [string match *elogin $argv0] == 1 } {      # ipc as default
        spawn telnet $ip $port
        expect  "grain-media login:"
        send    "root\n"
        expect  "Password:"
        send    "jabsco668\n"

        interact {
            timeout 30 { send "" }
        }
    } elseif { [string match *nlogin $argv0] == 1 } {
        spawn telnet $ip $port
        expect  "login:"
        send    "root\n"
        expect  "Password:"
        send    "jco88888\n"

        interact {
            timeout 30 { send "" }
        }
    } else { 
        puts "$argv0"
        puts "Usage: {elogin|nlogin} ip"
    }
}
