#!/usr/bin/expect -f
#
# spacial [] {} etc. can't be put after telnet
#
if { $argc == 0 } {
    puts "
    Usage: $argv0 ip port
    echo 'root::0:0:root,,,:/root:/bin/sh' > /tmp/passwd; mount --bind /tmp/passwd /etc/passwd
    "
    exit -1
} else {
    set ip   [ lrange $argv 0 0 ]
    set port 24

    if { $argc == 2 } {
        set port [ lrange $argv 1 1 ]
    }

    if { [string match *elogin $argv0] == 1 } {         # Grain + Nxp
        spawn telnet $ip $port
        expect  "login:"
        send    "root\n"
        expect  "Password:"
        send    "jabsco668\n"

        interact {
            timeout 30 { send "" }
        }
    } elseif { [string match *alogin $argv0] == 1 } {   # Anyka
        spawn telnet $ip $port
        expect  "login:"
        send    "root\n"
        expect  "Password:"
        send    "jabsco168\n"

        interact {
            timeout 30 { send "" }
        }
    } elseif { [string match *vlogin $argv0] == 1 } {   # v-ipcsdk
        spawn telnet $ip $port
        expect  "login:"
        send    "root\n"
        expect  "Password:"
        send    "admin666666\n"

        interact {
            timeout 30 { send "" }
        }
    } elseif { [string match *jlogin $argv0] == 1 } {   # Junzheng
        spawn telnet $ip $port
        expect  "login:"
        send    "root\n"
        expect  "Password:"
        send    "jco666888\n"

        interact {
            timeout 30 { send "" }
        }
    } elseif { [string match *nlogin $argv0] == 1 } {   # new-ipc-passwd
        spawn telnet $ip $port
        expect  "login:"
        send    "root\n"
        expect  "Password:"
        send    "AeC08j%2\n"

        interact {
            timeout 30 { send "" }
        }
    } elseif { [string match *ilogin $argv0] == 1 } {   # mstar-ipc
        spawn telnet $ip $port
        expect  "login:"
        send    "root\n"
        expect  "Password:"
        send    "jco16888\n"

        interact {
            timeout 30 { send "" }
        }
    } elseif { [string match *Nlogin $argv0] == 1 } {   # old-nvr
        spawn telnet $ip $port
        expect  "login:"
        send    "root\n"
        expect  "Password:"
        send    "jco88888\n"

        interact {
            timeout 30 { send "" }
        }
    } elseif { [string match *Rlogin $argv0] == 1 } {   # No password
        spawn telnet $ip $port
        expect  "login:"
        send    "root\n"

        interact {
            timeout 30 { send "" }
        }
    } else { 
        puts "$argv0"
        puts "Usage: {elogin|nlogin} ip"
    }
}
