#! /bin/bash

function fn_main() 
{
    # add commit push
    # commit了但没有push的内容：git diff HEAD^ HEAD 
    if [ -z "$*" ] ; then
        echo "Usage: $0 file..." 
        git status
        exit
    fi  

    local i=
    for i in $@; do
        [ ! -f "$i" ] && { echo "Error: $i not exist"; exit ;}
    done

    read -p "    Please input comment: "

    git add $@
    git commit -m "$REPLY" $@
    git push origin
}

fn_main $@
