#!/bin/bash - 
#---------------------------------------------------------------------------
#          FILE: j2.sh
#         USAGE: ./j2.sh 
#   DESCRIPTION: 
#        AUTHOR: moo (God helps those who help themselves) 
#  ORGANIZATION: 
#       CREATED: 2012-11-02 11:31:15 CST
#      REVISION: 1.0 
#---------------------------------------------------------------------------

function xt_ret() {
    [ $? -eq 0 ] && return 0
    printf "${BASH_SOURCE[1]##*/}%-6s %s\n" "|${BASH_LINENO[0]}|" "$*"
    return 1
}

# jcli devvecfg -act list
# [Success]gnum=2;id=0;enable=1;codec=1;vencsize=2;standard=0;fps=25;bps=2048;gop=25;fixfps=1;fixbps=1;profile=0;level=40;idrframe=1;#id=1;enable=1;codec=1;vencsize=0;standard=0;fps=25;bps=256;gop=25;fixfps=1;fixbps=1;profile=0;level=40;idrframe=1;#


function fn_list() 
{
    sed -n '/struct JcpCmdMap JcpCmdAll/,$p' $f_jcp | grep '{"[a-z]' | \
        awk -F'"' '{print $2}' | xargs -n3 | \
        awk '{printf "    %-24s%-24s%-24s\n", $1, $2, $3}'
}

function fn_main()
{
    f_jcp='/home/s/n/server/./jcp/jcpCmdImplement.cpp'
    if [ "$#" -eq 0 ] ; then
        fn_list
        return
    fi
    if [ "$1" == '/' ] ; then
        fn_list | grep --color ${@:2}
        return
    fi
    jcli $@ | sed -e 's///g' -e 's/\;\#$//' | sed -e 's/[;#]/\n/g' 
}

fn_main $@
