#! /bin/bash

. ~/bin/common.rc

#   mips-gcc720-uclibc0.9.33.2-r5.1.7   T41
#   mips-gcc540-glibc222-r3.3.7                          T32-33333333    mips-linux-uclibc-gnu-

array=(
    SHOW_This_usage                                      NULL            NULL
    mips-gcc540-glibc222-64bit-r3.3.0                    T31             mips-linux-uclibc-gnu-
    mips-gcc540-glibc222-r3.3.5                          T32-33555555    mips-linux-uclibc-gnu-
    mips-linux-gnu-ingenic-gcc7.2.0-uclibc0.9.33.2-fp64  T41             mips-linux-uclibc-
    mips-gcc540-uclibc0.9.33.2-64bit-r3.3.0.smaller      T23-uclibc      mips-linux-uclibc-
    mips-gcc540-glibc222-64bit-r3.3.0.smaller            T23-glibc       mips-linux-gnu-
    mips-gcc472-glibc216-32bit                           _472_yyShang    mips-linux-uclibc-gnu-
    mips-gcc720-glibc226                                 T40             mips-linux-uclibc-gnu-
    mips-gcc720-uclibc0.9.33.2-r5.1.11                   T40-315Pro      mips-linux-uclibc-gnu-
    ______________                                       Occ             NULL
    gcc-arm-9.2-2023.12-x86_64-aarch64-none-linux-gnu    ax-2023         NULL
    ______________                                       Occ             NULL
    ______________                                       Occ             NULL
    ______________                                       Occ             NULL
    ______________                                       Occ             NULL
    arm-fullhanv3-linux-uclibcgnueabi-b6                 Fulhan-8852     NULL
    arm-fullhanv3-linux-uclibcgnueabi-b6                 Fulhan-8652-16  NULL
)

help_show()
{
    echo -e "\nUsage:"
    local i
    for (( i=0; i<${#array[@]}; i+=3 )); do
        compile=${array[$i]}
        let j=i+1
        let k=i+2
        let No=i/3
        printf "  %-3d%-54s  # %-14s %s\n" $No $compile ${array[$j]} ${array[$k]}
    done
    return;
}

fn_main()
{
    ingn_cc='/opt/ingen.cc'
    link_cc='/opt/ingen.cc/gcc/bin'

    if [ "${1:-0}" -eq 10 ]; then
        ingn_cc='/opt/ax.cc'
    fi

    case ${1:-0} in
    10|11|12)
        ingn_cc='/opt/ax.cc'                ;;
    15)
        ingn_cc='/opt/fullhan/toolchain'    ;;
    16)
        ingn_cc='/opt/fullhan/865x'         ;;
    esac

    case ${1:-0} in
    0)
        help_show

        [ -e "${link_cc}" ] && {
            local i
            for (( i=3; i<${#array[@]}; i+=3 )); do
                let j=i+1
                ls -l ${link_cc} | grep -q ${array[$i]} && { curr=${array[$j]}; break ;}
            done
        } || curr=NONE
        echo "
        curr: ${curr:-____not_match_any____}
        "
        ls -l ${link_cc}; echo
        return
        ;;
    [0-9]*)
        rm -f ${link_cc}
        No=$1*3
        let j=No+2
        [ -e "${ingn_cc}/${array[$No]}/bin" ]
        xt_ret $? "Not exist: ${ingn_cc}/${array[$No]}/bin" || return $?
        ln -sf ${ingn_cc}/${array[$No]}/bin ${link_cc}
        let No++
        echo "
        link ${array[$No]} ${array[$j]} succ
        "
        echo ${array[$j]} > ~/.cross
        ls -l ${link_cc}; echo
        echo 
        ;;                         
    *)
        help_show
        return
        ;;
    esac
}

fn_main $@
