#!/bin/sh
# indent -kr -i8 -bad -bap -l80 -lp -nbbo $1;rm -f $1~
# modi: -i8 -nbbo -bad
# add: 	-l80 -ppi 4 -lps

kkr_style() {
indent \
 -bad -bap -nbbo -nbc -br -brs -c33 -cd33 -ncdb -ce -ci4 -cli0 \
 -cp33 -cs -d0 -di1 -nfc1 -nfca -hnl -i4 -ip0 -l88 -lp -npcs \
 -nprs -npsl -saf -sai -saw -nsc -nsob -nss	--no-tabs \
 \
 -l88 -ppi 4 -lps\
 \
 $1;rm -f $1~

}

if [ $# -eq 0 ]; then
	echo "Usage: /root/bin/kkr_style args"
	exit 1
fi

until [ $# -eq 0 ]; do
	kkr_style $1
	shift
done
