#! /bin/bash

# kvim -- check whether a bg vim running?

function fn_main()
{
    TTY=$(tty)
    TTY=${TTY##/dev/}
    PTS=(`ps -ef | grep -w -E "([v]i|[v]im|[v]imdiff)" | /usr/bin/awk '{print $6}'`)
    PID=(`ps -ef | grep -w -E "([v]i|[v]im|[v]imdiff)" | grep "${TTY}\>" | /usr/bin/awk '{print $2}'`)

    [ -z "${PTS[*]}" ] && echo -e "\n No vim --Running--! \n" && exit 0

    #  [ -n ${PID[@]} ] don't work well
    if [ 0 -ne ${#PID[@]} ]; then
        local i=
        for i in ${PID[@]}; do
            cwd=`ls -l /proc/$i/cwd | /usr/bin/awk '{print $10}'`
            echo -e "\n    ---------> running@ $cwd"
        done
        echo
    else
            echo -e "\n    ^_^ Please turn to@ `echo ${PTS[@]}`! \n"
    fi
}

fn_main $@
