#!/bin/bash
#
# 2017-01-03
#

.  ~/bin/common.rc
cd ${CWD}

function fn_ipctool()
{
    MYIP='192.168.9.246'
    key="SEARCH * HDS/1.0 LOCALIP=${MYIP}#LOCALPORT=8788#i_am_nc"
    grp='230.230.230.230'
    port=8002
    ps -ef | awk '/[n]c....8788/{print $2}' | xargs kill -9 2>/dev/null
    nc -u -l 8788&
    
    while :; do
        echo "[Ctrl-C] to exit, or Type [Enter] to shoot a SEARCH" && read line
        # 组播时必须指定源地址[-s172.25.100.44]，单播则不然
        nc -w0 -s ${MYIP} -p8002 -u ${grp}        ${port} <<< "$key"
       #nc -w0                         -u 172.25.100.10 ${port} <<< "$key"
        sleep .5
    done
}


function fn_ffw_force()
{
    grep -q ffw <<< "$1"
    xt_ret $? "ffw needed" || return $?

    echo -n "$1" > ffw.txt
}

function fn_update_force()
{
    grep -q tgz <<< "$1"
    xt_ret $? "ffw needed" || return $?

    echo -n "$1" > update_force.txt
}


function fn_drop()
{
    sync; echo 3 > /proc/sys/vm/drop_caches
    top -n1 | sed -n '1,5p'; free;
    echo -n "free+buffer+cache: "
    cat /proc/meminfo | sed -n '2,4p' | awk '{sum=sum+$2} END{print sum}'
}

function fn_pskill()
{
    test -n "$1" || {
        echo "Usage: pskill name" && return 1
    };
    head=${1:0:1};
    body=${1:1};
    ps -ef | grep --color=auto -E "[${head}]${body}\>" | awk '{print $2}' | xargs kill -9
}


function fn_autossh()
{
    fn_pskill autossh
    sleep .5
    netstat -nat | grep -w 22
    autossh -M 55555 -NfR 0.0.0.0:22001:localhost:22 root@47.112.230.17 -p 48367
    echo "
    autossh reset succ
    "
}

function fn_main() 
{
    cmdlist=(
    "ipctool                # search-ipc"
    "nvrtool                # search-nvr"
    "update_force           # 生成 update_force.txt 文件"
    "ffw_force              # 生成 ffw.txt 文件"
    "drop                   # vmm drop"
    "autossh                # restart"
    )

    fn_execute "$@"
}

fn_main "$@"
