#! /bin/bash 
# -- file -- ma 
[ $# -lt 1 ] && echo "Usage: $0 keyword" && exit -1 
TMP=/tmp/.man 
keyword=$1 
/usr/bin/man -f ${keyword} > $TMP 2>&1 || { cat $TMP && exit $?; } 
cat $TMP 
line=`wc -l $TMP` 
line=${line%% *} 
# echo $line 
indexs=`man -f $keyword | awk -F'[ ()]' '{print $3}'` 
if [ "${line}" -gt 1 ]; then 
    echo -e "\nPls Enter man page index number:" 
    read man_index 
    echo ${indexs} | grep -w ${man_index} >& /dev/null 
    if [ "$?" -eq 0 ]; then
        man $man_index $keyword > /dev/shm/ma
    else
        # echo "$man_index is not a good index, use default"
        man ${indexs%% *} $keyword > /dev/shm/ma
    fi
else 
    man $keyword > /dev/shm/ma
fi 

