#! /bin/bash

#   <meta charset="GB2312">

HEAD='
<head>
    <meta charset="UTF-8">
    <title></title>
    <style id="system" type="text/css">h1,h2,h3,h4,h5,h6,p,blockquote { margin: 0; padding: 0;}
        body { font-family: "Helvetica Neue", Helvetica, "Hiragino Sans GB", Arial, sans-serif; 
         font-size: 13px; line-height: 18px; color: #737373; margin: 10px 13px 10px 13px;} 
        a { color: #0069d6;}
        a:hover { color: #0050a3; text-decoration: none;}
        a img { border: none;}
        p { margin-bottom: 9px;}h1,h2,h3,h4,h5,h6 { color: #404040; line-height: 36px;}
        h1 { margin-bottom: 18px; font-size: 30px;}
        h2 { font-size: 24px;}
        h3 { font-size: 18px;}
        h4 { font-size: 16px;}
        h5 { font-size: 14px;}
        h6 { font-size: 13px;}
        hr { margin: 0 0 19px; border: 0; border-bottom: 1px solid #ccc;}
        blockquote { padding: 13px 13px 21px 15px; margin-bottom: 18px; font-family:georgia,serif; font-style: italic;}
        blockquote:before { font-size:40px; margin-left:-10px; font-family:georgia,serif; color:#eee;}
        blockquote p { font-size:
         14px; font-weight: 300; line-height: 18px; margin-bottom: 0; font-style: italic;}
        code, pre { font-family: Monaco, Andale Mono, Courier New, monospace;}
        code { background-color: #fee9cc; color: rgba(0, 0, 0, 0.75); padding: 1px 3px; 
         font-size: 12px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px;}
        pre { display: block; padding: 14px; margin: 0 0 18px; line-height: 16px; font-size: 11px; 
         border: 1px solid #d9d9d9; white-space: pre-wrap; word-wrap: break-word;}
        pre code { background-color: #fff; color:#737373; font-size: 11px; padding: 0;}@media screen and (min-width: 768px) 
        { body { width: 748px;  margin:10px auto; } }
    </style>
    <style id="custom" type="text/css"></style>
</head>
'


function fn_gen_link() 
{
    # echo $cur_level $prev_level $* > /dev/stderr
    echo "<li><a href=\"#$*\">$@</a></li>"
}


function fn_gen_content() 
{
    levels=(`grep '^#' $1 | sed -e 's///g' | sed -e 's/ *$//g' | awk '{ 
            print $1; }' `)

    heads=`grep '^#' $1 | sed -e 's///g' | sed -e 's/ *$//g'  -e 's/^#* //g'`

    prev_level=0
    cnt_open=0
    cnt_close=0

    local i
    for (( i=0; i<${#levels[@]}; i+=1 )); do
        let lno=i+1
        head=`echo "$heads" | sed -n "${lno}p"`
        cur_level=`echo -n ${levels[$i]} | wc -m`

        if [ $cur_level -gt "$prev_level" ] ; then
            echo "<ul>"
            let cnt_open++
        fi

        if [ $cur_level -lt "$prev_level" ]; then
            local j
            for (( j=$cur_level; j<$prev_level; j+=1 )); do
                echo "</ul>"
                let cnt_close++
            done
        fi

        fn_gen_link $head


        prev_level=$cur_level

        # echo  $cur_level $head
    done

    for (( i=$cnt_close; i<$cnt_open; i+=1 )); do
        echo "</ul>"
    done
    # echo $cnt_close $cnt_open
    # echo $levels
    
}

function fn_main() 
{
    [ ! -f "$1" ] && echo "md2html txtfile" && exit 1

    body=$1.html.body
    content=$1.html.content

    /root/bin/Markdown.pl $1 > $body

    fn_gen_content $1 > $content
    # fn_gen_content $1 > con.html


    cat <<-HERE
    $HEAD
<!-- INDEX BEGIN -->
<div name="index">
<p><a name="__index__"></a></p>

    `cat $content`

<hr name="index" />
</div>
<!-- INDEX END -->

    `cat $body`

	HERE

    rm -f $body $content
}

fn_main $@
# fn_gen_link 
