#! /bin/bash

function fn_main()
{
    filelist=${@:2}

    case $1 in
    a)
        find ! -name '.' -a -name '*' | xargs -I{} svn add --force {}  | cat -n
        ;;
    c)
        svn ci $filelist
        ;;
    r)
        [ -z "$filelist" ] && echo "Error: file... must be dedicated" && exit
        svn revert $filelist
        ;;
    s)
        svn status
        ;;
    q)
        svn -q status
        ;;
    *)
        echo "
        ----------- Usage --------------
        a   find ! -name '.' -a -name '*' | xargs -I{} svn add --force {}  | cat -n
        c   ci [files...]
        r   revert [file or directory]
        q   -q status
        s   status
        "
        svn status | sed 's/^/\t/g'
        ;;
    esac

}

fn_main $@
