#! /bin/bash


function fn_usage()
{
    echo "
        ----------- Usage --------------
        a   find ! -name '.' -a -name '*' | xargs -I{} svn add --force {}  | cat -n
        c   ci [files...]
        D   {?|M}
        d   diff
        q   -q status
        r   revert -R {file|dir}
        s   status
        u   update
    "
}

function fn_main()
{
    filelist="${@:2}"

    case $1 in
    a)
        find ! -name '.' -a -name '*' | xargs -I{} svn add --force {}  | cat -n
        ;;
    c|ci)
        svn ci $filelist
        ;;
    D)
        [ -z "$filelist" ] && echo "Warn: use ? as START-CHAR"
        svn status | grep "^${filelist:-?}" |  awk '{print $2}' | xargs -I{} rm -rf {}
        ;;
    d|diff)
        svn diff $filelist
        ;;
    r)
        [ -z "$filelist" ] && echo "Error: file... must be dedicated" && exit
        svn --depth=infinity revert $filelist
        ;;
    s)
        svn status $filelist
        ;;
    q)
        svn -q status
        ;;
    u|up)
        svn up $filelist
        ;;
    h)
        fn_usage
        ;;
    *)
        fn_usage
        svn status | sed 's/^/\t/g'
        ;;
    esac

}

fn_main $@
