#! /bin/bash

function fn_main()
{
    if [ "${#}" -eq 0 ]; then
        echo "
        Usage: wrap filelist...
        "
        exit
    fi

    local i=
    for i in $*; do
        if [ ! -e "${i}" ]; then
            echo ${i} not exist
            continue
        fi

        echo "___process___ $i"
        header='\#ifdef __not_8M'
        tailer='\#endif'
        sed -i -e "1i${header}" -e "\$a${tailer}" ${i}
    done
}

fn_main $@
