#! /bin/bash

2. 习惯
    We are what we repeatedly do. Excellence, then, is not an act, but a habit. 
    We believe that a healthy lifestyle can cultivate good personal qualities;

    男人思想可以肮脏,但生活必须健康.没有强健的体魄拿什么支撑龌龊的灵魂.


3. Shaoyun
    words:
    1. The simpler the better, easy maintain & easy to share; 
    2. use existing tools as much as possible. (shell script especially)
    

    作为一名优秀的程序员，在面对一个复杂问题时，应该是寻求一种尽可能简单、直接并
    且高效的处理方式来解决，而不是将一个简单问题在实现上复杂化。如果想在简单问题
    上突出自己使用某种语言的熟练程度，是一种非常愚蠢且不成熟的行为。


6. Jinyi Li

  a. in the company, prefer to perfect the few task assigned on you 
	rather than do a lot  of work but with a lot of bugs, because 
	quality first. though the others help you with the problems, but you
	should also take the responsibility.
	
  b. Never be self_centered
	learn to thanks the others' help, so don't credit-claiming.

7. 罗恩
    =================================================================
    罗恩的形象应该被雕塑成不朽的铜像，矗立在各个高等学府的门前。它不是年轻人所应
    受的正规教育，也不是各级各类教育机构拟定的政策，而是让我们的意志变得更加坚强
    、信念更加坚定，行动更加迅捷，精力更加集中的精神——“把信送给加西亚”。 

    =================================================================

    concentrate
    相信我们都会有这样的感受，当我们能够"集中精力"专注在一件事情上时，往往产生效
    果的时间就会比较短。而当我们总是给自己缓冲、走神的借口或者机会时，我们完成工
    作的周期就会自然而然的加长，这就会造成工作任务结束周期的不可控制。

    "高效利用时间会带来快乐"

8. 人人都喜欢公平交易
    工作，以自己的时间换取老板的金钱；
    老板，用自己的管理及投入让他人为你赚钱；
    模式，以钱生钱，如修高速公路（有损耗），如创办公司所有权及管理权的分离。

9. 王垠    
    http://kurttlin.diandian.com/post/2011-10-03/5502426


