#! /bin/bash

http://www.zhihu.com/question/20668955


6 Harsh Truths That Will Make You a Better Person
六个可以让你变得更强大的残酷事实 

#6：这个世界只关心你能给予什么 
#5：别去相信嬉皮士的话 (Hippies are wrong) 
#4：你所做的事情不一定要换成钱，但一定要有益于他人
#3：你恨自己是因为你无所作为
#2：你的内在只有通过所做的事情才能表现出来 
#1：人的内心其实一直在拒斥进步 

