#! /bin/bash -- screener

. 选股

    因时、因地、因势选出最不坏的那个。

    知己知彼，百战不殆。分门另类，对2500支个股进行大梳理。

. KDJ诱多效应    
    RSV(Raw Stochastic Value) 
    

. DDX

    Dana可以轻松地把大资金分散，却难以把小资金聚拢，所以反映在市场中的DDX即是
    最真实的数据了。

    我们找比值最大的。 

    # 忽略某些列
    LOAD DATA INFILE 'file.txt'
      INTO TABLE t1
        (column1, @dummy, column2, @dummy, column3);

    # 忽略第一行
    IGNORE


. 龙头的裙带效应

    2013-09-30 “东方明珠”封涨停，“电广传媒”也跟着大涨。但是“电广传媒”有一点的
    滞后，应该是观望心态，看“东方明珠”是否坚挺。


