#! /bin/bash

    ╔═════════════════════════════════════════════════════════════════════════╗
    ║   Do Nothing                                                            ║
    ╠════════════════╤════════════════════════════════════════════════════════╣
    ║   Just Do it   │                                                        ║
    ║                │  逃避思考                                              ║
    ║                ├────────────────────────────────────────────────────────╢
    ║                │                                                        ║
    ║                │  知之者不如乐之者, 乐之者不如好之者(习惯)              ║
    ║                │                                                        ║
    ║                ├────────────┬───────────────────────────────────────────╢
    ║                │  以终为始  │                                           ║
    ║                │            │                                           ║
    ║                │            │ 眉毛胡子一把抓                            ║
    ║                │            ├───────────────────────────────────────────║
    ║                │            │                                           ║
    ║                │            │ 80/20原理(GDB整理, 但是重要的就一两招)    ║
    ║                │            │                                           ║
    ╚════════════════╧════════════╧═══════════════════════════════════════════╝

. What & How

    what    往往是不言自明的 
            http://baike.baidu.com/view/102959.htm#6

    how     细分的过程，因为模糊而让人失去焦点，不确定性让意志不坚守者过早放弃，
            而最终失败。
            
            细分后的阶段验证是能否进入下一个细分单元的保证。
            记得小时候背书
            记得老师说练二胡。

. 误区：

    误区一：工作缺乏计划（可并行性、后续性、工作方法的选择）
    误区二：不会适时说“不”
            （量力而行地说“不”，对己对人都是一种负责。否则是与委托人的“双输”。）

. 掌握“时间管理”的四大法宝

    “成功地界定问题就已经解决了问题的一半”，但如果没有切实可行的解决方案，困境还是
    不会改变。“华为”对于时间管理有4大法宝。

    法宝一：以SMART为导向的“华为”目标原则
        具体性（Specific）。    
            -- 清晰的，可产生行为导向的。
            “我要成为一个优秀的华为人” vs “我要获得今年的华为最佳员工奖”

        可衡量性（Measurable）。
            -- 目标必须用指标量化表达。
            “最佳员工奖”目标，它就对应着许多量化的指标——出勤、业务量等

        可行性（Attainable）。
            -- 一是目标应该有能力范围内；二是目标应该有一定难度。
            
        相关性（Relevant）。
            -- 与现实生活相关，而不是简单的“白日梦”。与组织价值对齐。
        
        及时性（Time-based）.
            -- 设立多个小时间段上的“时间里程碑”，以便进行工作进度的监控。

    法宝二：关注第二象限的华为四象限原则
        *4D*
        Do it now       -- 1
        Delegate it     -- 2 quadrant 界定后处理
        Do it later     -- 3 quadrant
        Don’t do it     -- 4 quadrant

    法宝三：赶跑时间第一大盗的华为韵律原则

    法宝四：执着于流程优化的华为精简原则

. TIME_MANAGE

    紧急的事情只是对他人重要

. x.1* story
    The Story of Cobble, Gravel, Sand and Water
    One day, the Professor put the Cobble, Gravel, Sand and Water into the
    bottle in a certain sequence, and ask what u think:
    One student say: the space in the bottle is like our left time.
    The professor say: What I want to emphasize is we must put the Cobble
    1st, or we can't accomodate the whole material.

    And it's like my rest and entertainment, if I don't go to bed earlier,
    I can't have a good rest and can't have a good condition to the next
    day's work.
    
. x.2* Effective
    Do it in time, time to dinner, time to Pingpang, time to Go home.
    and then, a  suspense　is solved on the way home and when you see 
    movies.
     ┌───────────────────────────────────────────────────────────────┐
     │  中午休息好30分钟，一个下午好精神                             │
     │  晚上休息好7小时，一天好精神（早起后先早读半小时）            │
     │  周末晚餐早20分钟，有个低油低盐的好午餐                       │
     └───────────────────────────────────────────────────────────────┘

