#! /bin/bash

. 更新源

    http://qlqllu.iteye.com/blog/1808089

    使用apt-get安装软件时，可能发生not found，404错误，修改更新源可能可以解决问题。

    1. vi /etc/apt/source.list，把下面内容copy到source.list中
    2. apt-get update
     
    deb http://mirrors.163.com/ubuntu/ oneiric main universe restricted multiverse 
    deb-src http://mirrors.163.com/ubuntu/ oneiric main universe restricted multiverse 
    deb http://mirrors.163.com/ubuntu/ oneiric-security universe main multiverse restricted 
    deb-src http://mirrors.163.com/ubuntu/ oneiric-security universe main multiverse restricted 
    deb http://mirrors.163.com/ubuntu/ oneiric-updates universe main multiverse restricted 
    deb http://mirrors.163.com/ubuntu/ oneiric-proposed universe main multiverse restricted 
    deb-src http://mirrors.163.com/ubuntu/ oneiric-proposed universe main multiverse restricted 
    deb http://mirrors.163.com/ubuntu/ oneiric-backports universe main multiverse restricted 
    deb-src http://mirrors.163.com/ubuntu/ oneiric-backports universe main multiverse restricted 
    deb-src http://mirrors.163.com/ubuntu/ oneiric-updates universe main multiverse restricted

. 下下策 rpm

    # 当apt-get install 无法安装软件时，制作一个rpm包
    # 打到服务文件 /etc/init.d/smbd，并其中的命令 -> which smbd -> /usr/sbin/smbd
    # ldd /usr/sbin/smbd | awk '{print $3}'
    # ll 检测是否是链接
    # 打包所有相关文件  --> svn.tgz 也曾经是这样制作的。

    function fn_main() {
        files="
            /etc/samba/
            /usr/sbin/smbd
            /etc/init.d/smbd
            /etc/alternatives/smbstatus
            /usr/bin/smb*
            /usr/lib/libldap_r-2.4.so.2
            /usr/lib/liblber-2.4.so.2
            /usr/lib/i386-linux-gnu/libgssapi_krb5.so.2
            /usr/lib/i386-linux-gnu/libkrb5.so.3
            /usr/lib/i386-linux-gnu/libk5crypto.so.3
            /lib/i386-linux-gnu/libcom_err.so.2
            /usr/lib/libcups.so.2
            /lib/i386-linux-gnu/libpam.so.0
            /lib/i386-linux-gnu/libacl.so.1
            /lib/i386-linux-gnu/libattr.so.1
            /lib/libcap.so.2
            /lib/i386-linux-gnu/libresolv.so.2
            /lib/i386-linux-gnu/libnsl.so.1
            /lib/i386-linux-gnu/libdl.so.2
            /lib/libpopt.so.0
            /usr/lib/libtalloc.so.2
            /usr/lib/libwbclient.so.0
            /lib/i386-linux-gnu/libz.so.1
            /lib/i386-linux-gnu/libc.so.6
            /usr/lib/libsasl2.so.2
            /usr/lib/i386-linux-gnu/libgnutls.so.26
            /lib/i386-linux-gnu/libgcrypt.so.11
            /lib/i386-linux-gnu/libpthread.so.0
            /usr/lib/i386-linux-gnu/libkrb5support.so.0
            /lib/i386-linux-gnu/libkeyutils.so.1
            /usr/lib/i386-linux-gnu/libavahi-common.so.3
            /usr/lib/i386-linux-gnu/libavahi-client.so.3
            /usr/lib/i386-linux-gnu/libtasn1.so.3
            /lib/i386-linux-gnu/libgpg-error.so.0
            /lib/i386-linux-gnu/libdbus-1.so.3
            /lib/i386-linux-gnu/librt.so.1
        " 

        tar -zcvf smb.tgz $files
    }

    fn_main $@

