#! /bin/bash export

# 1. set -a export all variables & functions

function fn_set()
{
  echo "
     Automatically mark variables and functions which are modified or created 
     for export to the environment of subsequent commands
  "
  
  return $?
}

# 2. source批量导入变量

function fn_set()
{
  if [ "${#}" -ne 2 ]; then
    echo "Usage: set key value" ; exit
  fi
  echo "export $1=${2}" > .myexport
}


# 3. 内部变量只有用export才能导出
# 4. export后，subsequent-routine会共享该变量

# file: b.sh

function fn_main()
{
    echo YIST is  $YIST
}

fn_main $@

# file: a.sh

function fn_chop_blank()
{
    YIST=a
    bash b.sh
    export YIST=a
    bash b.sh
    YIST=c
    bash b.sh
}

fn_chop_blank

# result: bash a.sh

|| YIST is
|| YIST is a
|| YIST is c
