#! /bin/bash

    READLINE
        ARG-COMPLETE
            Alt-#       comment a command line
            Alt-.       yank-last-arg. REPEAT Alt-. to count back 
            Alt--       yank-2nd-to-last-arg
            Alt-n Alt-. yank-nth-arg, REPEAT Alt-. to count back 

        OTHER-COMPLETE
            bind -p     | grep complete
            "TAB":      complete 
            "Alt-!":    complete-command 
            "Alt-/":    complete-filename 

            "Alt-@":    complete-hostname 
            "Alt-~":    complete-username 


        COMMAND-LINE-EXPAND
            bind -p     | grep 'C-x' 
        

            -- 互换CHAR
            Ctrl-t   

            -- 互换WORD
            Alt-t   

            -- 补全环境变量 
            Tab-Tab or "Alt-$":         # Putty中补全没有被绑架
            "Esc-Tab":                  # SecureCRT中经常被绑架

            -- complete-path --
            "Esc-<C-E>" 
