#! /bin/sh

tmp()
{
    f=${1}
    if [ ! -e "${f}" ]; then
        echo [${f}] not exist
        return
    fi

    if [ "${f:0:1}" != / ]; then
        f=$PWD/$f
    fi

    to=/tmp/${f##*/}
    cp $f $to
    mount --bind $to $f
}
