#! /bin/bash
    echo "
    #
    # tcopy.sh
    # whatever get or put, make sure: chmod 777 /tftpboot/
    #

    get
        tftp -gr  REMOTE_FILE -l LOCAL_SAVEPATH HOST
        tftp -r   <REMOTE_FILE>  -g ${ubt}
        tftp -r   modi_uboot_env -g ${ubt}

    put
        tftp -l                                -p ${ubt}
        tftp -l                  -r remotename -p ${ubt}
        tftp -l   modi_uboot_env -r remotename -p ${ubt}

    EXAMPLE

        tftp -gr feed.sh -l /tmp/feed.sh ${ubt:-192.168.2.248}
    "
