#! /bin/bash

# 横向考虑设计架构，纵向考虑可用性

    HIK协议实现1个月后傻眼，cby抓不到HTTP PUT的报文。

    设计者的职责：

        从横向考虑设计架构，如相关设计模式 mxmlapi.c 相关xml读写接口。
        从纵向考虑功能可用性，如一个URI的GET POST PUT DEL。

# 先固化，再优化

    从某种程度上来说，在项目开始时，兼顾2维性是值得的。
    系统软件开发时，bottom-to-up up-to-bottom同样值得从相互参考。

