#! /bin/bash

PROFILE解析失败

〇、现象
    720p 的设置 main 30 被 搞成了 ---> hign 40
    而 high 40是设备的默认值。
    
一、原因
    char *strtok(char *str, const char *delim); 
    strtok()依赖于delim， 没有delim, 其肯定会失败。

    这个问题早已被确认是工具曾经的bug.

二、罚
    曾经解决过的问题，花了3个小时排查，再花2个小时修改代码，及升级
    脚本中添加修复bug的操作。

    解决日期: 2013-01-16

三、罪

    # 很多时候，你只是发现问题，而并没有解决问题 

    (1) 我们需要的是patcher而不仅仅是bug finder，一个bug如果出现一次，
        那他同样可能出现第二次。

        请在第一次出现时引起重视。
        并考虑通过升级的方式自动修复之，而不是手动修复一台设备就完事了。

        对历史负责应该是我们做事的态度。

    (2) 从代码层面讲，
        对每一个操作进行返回值检查，并做log提示。
        唯有如此，越早发现问题，解决问题的成本越小。

    (3) 一个性质相同的问题 
        JCPCmdVICfg() -- bright contrast hue saturation设置无效

        if (SUCCESS != JCO_ARG_Parser(argc, argv, opts)) {
            return FAILURE;
        }

        上面这个代码，终端并不打印消息。
        对于这个 JCP命令vicfg，web并不进行结果检查。 

        
四、赎罪   
    请根据三中的条款赎罪。

