#! /bin/bash

. FORM模拟多文本输入框

    export TERM=linux
    dia_form='/tmp/dialog.form'

    function fn_eval_lables() {
        local i=0
        while read value; do
            eval ${lables[$i]}=$value
            let i++
        done < $dia_form
    }

    function fn_main() {
        # whiptail --inputbox NAME 40 20 zhangjian --inputbox GENDER 40 20 male
        # echo $NAME 
        # dialog --menu CODE 40 20 8 MYGOD haha what 123

        lables=(key1 key2 key3 key4)
        deflts=(1       2    3    4)

        dialog --backtitle "Dialog Form Example" --title "Dialog - Form" \
        --form "\nDialog Sample Label and Values" 25 60 16 \
        "${lables[0]}:" 1 1 "${deflts[0]}" 1 25 25 30 \
        "${lables[1]}:" 2 1 "${deflts[1]}" 2 25 25 30 \
        "${lables[2]}:" 3 1 "${deflts[2]}" 3 25 25 30 \
        "${lables[3]}:" 4 1 "${deflts[3]}" 4 25 25 30 \
        2>${dia_form}

        fn_eval_lables

        echo key1 is $key1
        echo key2 is $key2
        echo key3 is $key3
        echo key4 is $key4
    }

    fn_main

