#! /bin/bash

# dd 创建空文件, bs可以有单位，count也可以有单位

# skip 分割文件 if

dd bs=50K skip=0 count=1 if=/ipc/bin/impdbg of=/tmp/0; echo 0; 
dd bs=50K skip=1 count=1 if=/ipc/bin/impdbg of=/tmp/1; echo 1; 
dd bs=50K skip=2 count=1 if=/ipc/bin/impdbg of=/tmp/2; echo 2; 
dd bs=50K skip=3 count=1 if=/ipc/bin/impdbg of=/tmp/3; echo 3; 


# fake SD card (hexdump do 2G only)

             dd bs=1K skip=8M count=1 if=/dev/mmcblk0p1 | hexdump | head

timeout -t 3 dd bs=1K skip=8M count=1 if=/dev/mmcblk0p1 | hexdump | head


# seek 部分覆盖 of

dd bs=50K seek=3 

# 创建20M的文件

dd if=/dev/zero of=FILE_U_WANT bs=1M    count=20
dd if=/dev/zero of=FILE_U_WANT bs=512K  count=40

# 创建4G的文件

dd if=/dev/zero of=FILE_U_WANT bs=4K    count=1M

# 追加文件:[count=1]不能省

dd if=/dev/zero of=FILE_U_WANT bs=1M    count=20 oflag=append conv=notrunc
dd if=/dev/zero                bs=1G    count=1  >>FILE_U_WANT

# 测试网速.listen

nc -l  1234 > /dev/null
nc -lp 1234 > /dev/null

# 测试网速.send NR Mbits

NR=100 IF=/dev/zero HOST=192.168.2.102       # Send on IPC
NR=100 IF=/dev/zero HOST=192.168.9.246       # Send to Ubt

ps -ef >& /dev/null && export OPT=ax;

dd if=$IF  bs=400K count=$NR | nc ${HOST} 1234 &            \
pid=`ps $OPT | awk '/[d]d if/{printf ("%s", $1); exit}'`;   \
i=0; test -n "$pid" &&                                      \
while :; do kill -0 $pid || { echo __done__; break; };      \
    let i=i+1; echo $i;                                     \
    sleep 1; kill -USR1 $pid;                               \
done

# create files 1 2 3 ...
i=0; while [ ${i:=0} -lt 100 ]; do
    let i++; echo ____ $i
    dd if=/dev/zero of=${i:-0} bs=1M count=100 || { echo __exit; break ;}
done &

# read
i=0; while [ ${i:=0} -lt 100 ]; do
    let i++                          
    cat $i > /dev/null
done &                                
