#! /bin/bash

# *3* fdisk
# *3.2* fsck
# *3.1* add_a_new_disc_sh()


dev_disc="/dev/sde"
mount_path="/mnt"

fdisk $dev_disc

# p print the partition table
# d del specific partition
#
# n to add a new logical disk
# p to primay partition
#   Partition number (1-4): 1
#   First cylinder (1-2610, default 1): 1
#   Last cylinder or +size or +sizeM or +sizeK (1-2610, default 2610):
# w to write it in!

mkfs.ext4 ${dev_disc}1
sync                        # sync will send event[0p1] to kenerl.hotplug

fdisk -l | grep "$dev_disc"

if [ ! -d "$mount_path" ]; then
    mkdir $mount_path
fi

mount ${dev_disc}1 $mount_path

df -h
echo "add the start up conf to /etc/fstab"
sleep 2

dev_not_in_conf=`grep "$dev_disc"  /etc/fstab`
if [ -z $dev_not_in_conf ]; then
    echo "$dev_disc     $mount_path     ext4    defaults    1 2" >> "/etc/fstab"
fi



# 
#  fstab
# 
# /etc/fstab: static file system information with uuid.
#
# > blkid -o value -s UUID /dev/sdc1
#
# to print the universally unique identifier
# for a device; this may be used with UUID= as a more robust way to name
# devices that works even if disks are added and removed. See fstab(5).
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>

# mdata
UUID=5405139b-9085-4d5f-a6a3-931ff85b5856 /opt0/mdata/     ext4    errors=remount-ro 0       1

