#! /bin/bash

rar
    rar a archive.rar FILE...

unrar
    unrar x archive.rar .

zip
    zip -r archive_name.zip directory_to_compress
    unzip archive_name.zip [-d exdir]

zip 加密
    zip -re dir.zip dir
    unzip dir.zip

tar 1 single file                                           # 可以单独抽取压缩包中的某几个文件
    tar -zxvf <tar filename> <file you want to extract>     # extract a single file
    tar -zxvf kernel.tar.gz  kernel/net/wireless/reg.c

tar 不能处理无名文件

    dmesg | tar 会失败，只能先用临时文件保留，再 tar ，再删除

tar 
    /* Copying an Entire Directory Tree Without GNU cp, 
     * the '-' is stand for the stdin & stdout, or understand to a
     * intermediate file.
     */
    (cd  SRC_DIR  && tar cf - .) | (cd  DEST_DIR  && tar xvf -) 

    tar [options] a.tar.gz
        filename1 [ filename2, ... filenameN ]
        directory1 [ directory2, ...directoryN ]

    -t, --list
        列出存档中文件的目录
    -T, --files-from F
        从指定文件中得到要创建的'文件名列表'
    -X, --exclude-from FILE
        从指定文件中读入要排除的'文件的列表'(做备份时很有用)

    # 不备份 warehouse
    echo warehouse > /dev/shm/.tar.exclude
    cd ~; tar -zcf bin.tgz bin -X /dev/shm/.tar.exclude    

    # 可以指定目录层次
    echo kts/warehouse > /dev/shm/.tar.exclude 

    -J
        tar -xJf file.pkg.tar.xz

-X的3种有效路径

 1. 绝对路径：唯一匹配

 2. 多级相对路径：多个匹配，与find出后用grep过滤再tar

 3. 单级相对路径：多个匹配

    root@Moo:~/sh/t/tartest# find -name a
    ./a
    ./a/a
    ./a/a/a
    ./b/a
    ./b/a/a
    root@Moo:~/sh/t/tartest# echo a/a > X
    root@Moo:~/sh/t/tartest# tar -zcvf a.tgz * -X X
    a/
    a/b/
    b/
    b/a/
    b/b/
    t.tgz
    X

# tar 部分文件
# 1. -C outpath 一定要在 -zxf 前
# 2. SDK_release/linux/ 会保持 SDK_release 目录

tar -C /opt/ipc/df/trunk/kernel -zxf sdk_release_jpl-r3.2.0-rc2_1703.tgz SDK_release/linux/

