#! /bin/bash

# 手册
    pinfo date 查不到 date, 先 pinfo 进入手册，再搜索进入
    info coreutils 'date invocation'

# 格式输出
    date "+%F %T"
    1970-01-01 00:02:00

# ago and hence(从此)

   * To print the date of the day before yesterday:
        date --date='2 days ago' +'%F'

   * To print the date of the day three months and one day hence:
        date --date='3 months 1 day'   

# 转换：把<date-time>转换为<自Epoch的秒数>
    date --date='1970-01-01 00:02:00 +0000' +%s
    date --date='1970-01-01 00:02:00 UTC' +%s
    120

# 转换：把<自Epoch的秒数>转换为<date-time>
    date    -d  '1970-01-01 UTC 946684800 seconds' +"%F %T %z"
    date    -d  @946684800 +"%F %T %z"
    date -u -d  @946684800 +"%F %T %z"

# busybox
	date [-u|--utc|--universal] [MMDDhhmm[[CC]YY][.ss]]
	date -s "010820132013.33"
	        [MMDDhhmm[[CC]YY][.ss]]

# 可分别设置日期、时间
	date -s 2008-10-9; date -s 18:22:40
	date -s "18:00:00 2008-10-09"
	hwclock -w

# $touch改变文件的创建时间 
    touch --date=180910 w.c
    -rwxr-xr-x 1 root  root     0 Sep 10  2018 w.c
	
# 4 timezone configuration file
    /etc/TZ
	/etc/localtime			
	/etc/ntp.conf
	/usr/share/zoneinfo
	/etc/sysconfig/clock 		

    cat <<-"HERE"
    # ZONE=”Asia/Shanghai”
	{
		ZONE="Asia/Shanghai"
		UTC=0	// hwclock use UTC, if UTC=1, ust TZ and set file 
		ARC=0
	}

    /* $date */ 
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
	HERE
