#! /bin/bash

if [ x86 = "${1}" ]; then
    make distclean
    ./configure
    make

    cp src/iperf .
    strip iperf 

    du -sh iperf 
else
    CROSS=arm-unknown-linux-uclibcgnueabi-

    make distclean
    ./configure --host=${CROSS%-}
    make

    cp src/iperf .
    ${CROSS}strip iperf 

    du -sh iperf 

fi
