#! /bin/bash

# lockfile-progs

  lockfile=/some/file

  # /some/file 可以不存在，无选项 --lock-name 时，创建文件 /some/file.lock
  lockfile-create --lock-name ${lockfile}

  # 因为create后会失效，而被重新create，touch可防止失败
  lockfile-touch --lock-name ${lockfile}&

  # Save the PID of the lockfile-touch process，可以用 kill -0 或查看之用
  echo $! > ${lockfile} 

  do_something_important_with ${lockfile} 

  lockfile-remove --lock-name ${lockfile} 

  kill -9 `cat ${lockfile}`

  lockfile-remove --lock-name ${lockfile} 


  # 缺点：
  # lockfile-create (in 5 second increments)*9 = 180s 去尝试create，
  # 若lockfile占用很久，则下一个lockfile-create不是实时的，会有延时。
  # 可以用 lockfile-check 来轮询之。
  #

# flock  

  # mode1 命令是必选项

  flock mylockfile ls

  # mode2 http://www.liyu8.com/article/63.htm
  {
      flock -n 3
      [ $? -eq 1 ] && { echo fail; exit; }
      echo $$
      sleep 10
  } 3<>mylockfile   # mylockfile处必是路径，不可用变量
  
  使用<>打开mylockfile，原因是定向文件描述符是先于命令执行的。
  当{}内的语句执行完，mylockfile会自动关闭，并unlock该文件。
  
