#! /bin/bash

| Action       | info      | pinfo          |
| :------      | :------   | :------        |
| help         | ?         | man pinfo      |
| 进入节点     | Enter     | Enter →右      |
| 返回上层节点 | u         | h     →左      |
| 浏览器回退   | l         | h     →左      |
| 下一个link   | Tab       | j     →上      |
| 上一个link   | Esc-Tab   | k     →下      |
|              |           |                |
| 节点头       | b         | H              |
| 节点尾       | e         | e              |
| 节点next     | n         | n              |
| 节点prev     | p         | p              |
|              |           |                |
| 向下滚屏     | Space     | Space PageDown |
| 向上滚屏     | Backspace | b     PageUp   |
|              |           |                |
| 本页搜索     | / s       | /              |
| 全局搜索     |           | s              |
| 搜索下一个   | /<CR>     | f              |
|              |           |                |
| shell        |           | !              |

# install info

~/bin/7bin install_info make
