#! /bin/bash

MBA
http://chuansongme.com/account/embaclub


本着对《你的灯还亮着吗？》考虑问题的本质。

. C++之父Bjarne Stroustrup

    人们过多关注所谓的效率。Too little about what they want to do?

    So, What do I want to do?
        How do I know that I have done it?


. 目标 

    --问题如疾病，不可能消亡，相生而已
    --伦敦街头的马粪

    对问题的本质思考，深入骨髓。看看目标主义者的尴尬。
    http://chuansongme.com/n/142649 --artical_03_教育的意义

. 抽象 --有选择的忽略
    
    不抽象，只会一个结果，只见树木，不见树林

. 分解 --量化

    --界定问题，是不是问题？
    --界定问题，外部问题，找相关人？
    --界定问题，内部问题，在哪个模块？
    
    不分解，对实际单点问题，你将束手无策。
    幸福的原因往往是相同的，不幸却各有各的不幸。

