#!/bin/bash
#
# a single tool is easy to be forgotten
#

CWD=${PWD}

shopt -s gnu_errfmt 
. /etc/common.rc

cd ${CWD}


function fn_1stcol() 
{
    awk -v v_col=${1:-1} '{print $v_col}'
}

function fn_main() 
{
    cmdlist=(
    # fixed sequence
    "1stcol [COL:-1]                   # 从stdin打印第COL列"

    # volatile sequence 

    )

    fn_execute "$@"
}

fn_main "$@"

