#! /bin/bash -
#
## 除权 CREATED: 2014-03-08 20:21:44

# 定时从znz下载除权数据
# 为降低自身算法的复杂度（除权不仅是对价格，还要对成交量除权），
# 加快计算速度，特决定从znz下载已除权数据。

# 1. 记录最近一次从znz下载数据的日期(date_znz)，并更新到数据库
# 2. 手动更新当日(date_dzh)的dzh的除权数据记录，并筛选出近期(>date_znz)
#    进行了除权的股票，得到股票列表(stocklist)
# 3. 遍历stocklist，下载近12(或15)个月的数据

. bin/znz.yahoo

function fn_rebuild_list_and_download_from_last_xRD()
{
    last_xRD=`echo "
    CREATE TABLE IF NOT EXISTS tbl_xRDdate ( date DATE NOT NULL DEFAULT 0 );
    SELECT max(date) FROM tbl_xRDdate;
    " | mysql -u root -N kts`
    xt_ret $? "mysql" || return $?

    if [ NULL = "$last_xRD" ] ; then
        last_xRD=$(date +'%F' --date='90 days ago')
        echo "
        INSERT INTO tbl_xRDdate (date) VALUES('${last_xRD}');
        " | mysql -u root kts
        xt_ret $? "mysql" || return $?
    fi

    # echo $last_xRD mygod ;exit
    ## rebuild $yahooask
    echo "
    SELECT code FROM xRD WHERE date > '${last_xRD}' and date <= '${date_maxyahoo}';
    " | mysql -u root -N kts > $yahooask
    xt_ret $? "mysql" || return $?

    # tag_try_2_times_fail 强制执行失败的个例
    # echo "002394 300232 300377" > $yahooask

    [ -s "$yahooask" ]
    xt_ret $? "empty file $yahooask" || return $?

    echo "
    going to xRD `wc -l ${yahooask}` codes
    "

    ## begin to download
    start_sps=($(date +'%Y %m %d' --date='365 days ago' ))
    endin_sps=($(date +'%Y %m %d'))
    start_year=${start_sps[0]}; start_month=${start_sps[1]}; start_day=${start_sps[2]}
    endin_year=${endin_sps[0]}; endin_month=${endin_sps[1]}; endin_day=${endin_sps[2]}

    fn_yahoo start

    echo "    Redoing the timeout ones[`cat $yahootimeout`]..."
    cp $yahootimeout $yahooask
    NOCLEAN=1 fn_yahoo start

    test -z "`cat $yahootimeout`"
    xt_ret $? "ask_help_to tag_try_2_times_fail" || return 0
}


function fn_main()
{
    read -p "
    make sure [up up_tbl_xRD --keep.PWR] is done!!!
    type any key to continue."
    # get date_maxyahoo
    fn_maxyahoo

    [ -n "${date_maxyahoo}" ]
    xt_ret $? "date_maxyahoo is NULL" || return $?

    fn_rebuild_list_and_download_from_last_xRD
    xt_ret $? "rebuild" || return $?

    rm -f ${znzday}/900001

    local i=
    for i in `ls ${znzday}`; do
        # it's so slow, don't use: code in (SELECT code from zxg)
        echo "
        DELETE FROM day WHERE code=$i and date <='${date_maxyahoo}';
        " | mysql -N kts
        xt_ret $? "mysql" || return $?
    done

    echo "DELETE over"

    up load_directory
    xt_ret $? "load znzday fail" || return $?

    echo "LOAD over"

    # dzh 会超前写入除权数据
    # INSERT INTO tbl_xRDdate (date) VALUES((SELECT max(date) FROM xRD));
    echo "
    INSERT INTO tbl_xRDdate (date) VALUES('${date_maxyahoo}');
    " | mysql -u root kts
    xt_ret $? "mysql" || return $?

    echo "UPDATE ${date_maxyahoo}"
}

fn_main $@
