#! /bin/bash -
# CREATED: 2014-03-08 20:21:44

. znz.yahoo

function fn_maxyahoo() 
{
    start_sps=($(date +'%Y %m %d' --date='8 days ago' ))
    endin_sps=($(date +'%Y %m %d'))
    start_year=${start_sps[0]}; start_month=${start_sps[1]}; start_day=${start_sps[2]}
    endin_year=${endin_sps[0]}; endin_month=${endin_sps[1]}; endin_day=${endin_sps[2]}

    echo sh000001 > ${yahooask}
    NOCLEAN=1 fn_yahoo start

    date_maxyahoo=`tail -1 ${znzday}/900001 | awk '{print $2}'`
}

function fn_rebuild_list_and_download_from_last_xRD() 
{
    last_xRD=`echo "
    CREATE TABLE IF NOT EXISTS tbl_xRDdate ( date DATE NOT NULL DEFAULT 0 ); 
    SELECT max(date) FROM tbl_xRDdate;
    " | mysql -u root -N kts`
    xt_ret $? "mysql" || return $?

    if [ NULL = "$last_xRD" ] ; then
        last_xRD=$(date +'%F' --date='90 days ago')
        echo "
        INSERT INTO tbl_xRDdate (date) VALUES('${last_xRD}');
        " | mysql -u root kts
        xt_ret $? "mysql" || return $?
    fi

    # echo $last_xRD mygod ;exit

    ## rebuild $yahooask
    echo "
    SELECT code FROM xRD WHERE date > '${last_xRD}' and date <= '${date_maxyahoo}';
    " | mysql -u root -N kts > $yahooask
    xt_ret $? "mysql" || return $?

    [ -s "$yahooask" ]
    xt_ret $? "empty file $yahooask" || return $?

    ## begin to download
    start_sps=($(date +'%Y %m %d' --date='365 days ago' ))
    endin_sps=($(date +'%Y %m %d'))
    start_year=${start_sps[0]}; start_month=${start_sps[1]}; start_day=${start_sps[2]}
    endin_year=${endin_sps[0]}; endin_month=${endin_sps[1]}; endin_day=${endin_sps[2]}

    fn_yahoo start

    cp $yahootimeout $yahooask
    NOCLEAN=1 fn_yahoo start
}


function fn_main() 
{
    # get date_maxyahoo
    fn_maxyahoo

    [ -n "${date_maxyahoo}" ]
    xt_ret $? "date_maxyahoo is NULL" || return $?

    fn_rebuild_list_and_download_from_last_xRD
    xt_ret $? "" || return $?

    rm -f ${znzday}/900001

    local i=
    for i in `ls ${znzday}`; do
        # it's so slow, don't use: code in (SELECT code from zxg)
        echo "
        DELETE FROM day WHERE code=$i and date <='${date_maxyahoo}';
        " | mysql -N kts 
        xt_ret $? "mysql" || return $?
    done

    echo "DELETE over"

    up load_directory
    xt_ret $? "load znzday fail" || return $?

    echo "LOAD over"

    # dzh 会超前写入除权数据
    # INSERT INTO tbl_xRDdate (date) VALUES((SELECT max(date) FROM xRD));
    echo "
    INSERT INTO tbl_xRDdate (date) VALUES('${date_maxyahoo}');
    " | mysql -u root kts
    xt_ret $? "mysql" || return $?

    echo "UPDATE ${date_maxyahoo}"
}

fn_main $@
