#! /bin/bash -
#
## 除权 CREATED: 2014-03-08 20:21:44

# 定时从znz下载除权数据
# 为降低自身算法的复杂度（除权不仅是对价格，还要对成交量除权），
# 加快计算速度，特决定从znz下载已除权数据。

# 1. 记录最近一次从znz下载数据的日期(date_znz)，并更新到数据库
# 2. 手动更新当日(date_dzh)的dzh的除权数据记录，并筛选出近期(>date_znz)
#    进行了除权的股票，得到股票列表(stocklist)
# 3. 遍历stocklist，下载近12(或15)个月的数据

. bin/znz.yahoo

function fn_rebuild_list_and_download_from_last_xRD()
{
    last_xRD=`echo "
    CREATE TABLE IF NOT EXISTS tbl_xRDdate ( date DATE NOT NULL DEFAULT 0 );
    SELECT max(date) FROM tbl_xRDdate;
    " | mysql -u root -N kts`
    xt_ret $? "mysql" || return $?

    if [ NULL = "$last_xRD" ] ; then
        last_xRD=$(date +'%F' --date='90 days ago')
        echo "
        INSERT INTO tbl_xRDdate (date) VALUES('${last_xRD}');
        " | mysql kts
        xt_ret $? "mysql" || return $?
    fi

    # echo $last_xRD mygod ;exit
    ## rebuild $yahooask
    echo "
    SELECT code FROM xRD WHERE date > '${last_xRD}' and date <= '${date_maxyahoo}';
    " | mysql -u root -N kts > $yahooask
    xt_ret $? "mysql" || return $?

    # tag_try_2_times_fail 强制执行失败的个例
    # export NUM=2000
    # echo "399006" > $yahooask
    if [ -n "${iLIST}" ]; then
        echo ${iLIST} | xargs -n1 > $yahooask
    fi

    [ -s "$yahooask" ]
    xt_ret $? "empty file $yahooask" || return $?

    total=`wc -l ${yahooask}`
    echo "
    going to xRD ${total} codes
    "

    fn_yahoo start

    echo "    Redoing the timeout ones[`cat $yahootimeout`]..."
    cp $yahootimeout $yahooask
    NOCLEAN=1 fn_yahoo start

    test -z "`cat $yahootimeout`"
    xt_ret $? "ask_help_to tag_try_2_times_fail" || return 0
}

function fn_main()
{
    read -p "
    Usage: autoxRD [code]
    make sure [up xRDdb --keep.PWR] is done!!!
    type any key to continue."

    iLIST="${*}"
    # get date_maxyahoo
    fn_maxyahoo

    [ -n "${date_maxyahoo}" ]
    xt_ret $? "date_maxyahoo is NULL" || return $?

    fn_rebuild_list_and_download_from_last_xRD
    xt_ret $? "rebuild" || return $?

    rm -f ${znzday}/900001

    local i=
    for i in `ls ${znzday}`; do
        # it's so slow, don't use: code in (SELECT code from zxg)
        mydate=`tail -1 ${znzday}/$i | awk '{print $2}'`
        xt_ret $? "" || return $?
        sqls=" DELETE FROM day WHERE code=$i and date <='${mydate:-${date_maxyahoo}}'"     # 每个code的数据可能不一样
        mysql -N kts<<<"${sqls}"
        xt_ret $? "mysql" || return $?
    done

    echo "DELETE over"

    up load_directory
    xt_ret $? "load znzday fail" || return $?
    fn_echo_succ "LOAD over"

    echo "
    INSERT INTO tbl_xRDdate (date) VALUES('${date_maxyahoo}');
    " | mysql kts
    xt_ret $? "mysql" || return $?

    echo "UPDATE ${date_maxyahoo}"
}

fn_main $@
