#! /bin/bash

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_main()
{
    [ -z "${*}" ] && echo Usage: bei codes... && exit 1
    echo "
    to visit ${#} codes,
    taif -f /tmp/bei.md
    "

    mysql kts <<<"truncate table tbl_rdiff;"
    xt_ret $? "try create tbl_rdiff: SCREENER tao 2" || return $?

    local i=
    for i in $@; do
        echo "# $i" | tee /dev/stderr
        ZIZE=${ZIZE:-5} SCREENER tao5 ${i}
    done > /tmp/bei.md

    SELECT rdiff
    return $?
}

fn_main $@ 
