#! /bin/bash

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_main()
{
    [ -z "${*}" ] && echo Usage: bei codes... && exit 1
    echo "
    to visit ${#} codes,
    taif -f /tmp/bei.md
    "

    local i=
    for i in $@; do
        echo "# $i" | tee /dev/stderr
        SIZE=5 SCREENER tao5 ${i}
    done > /tmp/bei.md
    return $?
}

fn_main $@ 
