#! /bin/bash
. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

# 小金属
# 除了用在军工上以外，很多新兴产业都要用到，主要包括
# 钛：宝钛股份、西部材料；锆：东方锆业；钽：东方钽业；锗：云南锗业；
# 铼：炼石有色；钨：中钨高新、厦门钨业、章源钨业；钼：金钼股份、洛阳钼业；
# 稀土：五矿稀土、包钢稀土、广晟有色。
# [互联网+](http://mt.sohu.com/20150311/n409644432.shtml)
# [互联金融](http://www.360doc.com/content/14/0201/22/1632548_349253018.shtml)

# 深证100R(对派息进行除权以减少波动)及深证100P均属于深证100指数,二者样本股组合完全相同

function fn_dzh()
{
    CWD=${PWD}
    BLK='/dzh2/USERDATA/block'
    maps=(
        创业板.BLK      .blk.cyb

        中证龙头.BLK    .blk.zzlt
        上证50.BLK      .blk.sz50
        深证成指.BLK    .blk.szcz
        创业板指.BLK    .blk.cybz
        中小板指.BLK    .blk.zxbz
        深证100R.BLK    .blk.sz100R
        深证300P.BLK    .blk.sz300P
        中证500.BLK     .blk.zz500

        军工指数.BLK    .blk.jgzs
        融资融券.BLK    .blk.rzrq
        券商.BLK        .blk.qs
        保险业.BLK      .blk.bxy
        银行业.BLK      .blk.yhy
        房地产.BLK      .blk.fdc
        300地产.BLK     .blk.300dc
        上海国资.BLK    .blk.shgz
        互联金融.BLK    .blk.hljr

        节能环保.BLK        .blk.jnhb
        污水处理.BLK        .blk.wscl
生态保护和环境治理业.BLK    .blk.hjzl
    )
    local i j
    for (( i=0,j=1; i<${#maps[@]}; i+=2,j+=2 )); do
        test ${maps[${j}]} -nt ${BLK}/${maps[${i}]} && continue
        echo ${maps[${i}]} ${maps[${j}]}
        cat ${BLK}/${maps[${i}]} | \
            tr -cd '[0-9SZH]' | sed 's/S[HZ]/\n/g'| \
            tail -n+2 | sort -g | grep '^[036]' > /dev/shm/.blk
        grep -f /dev/shm/.blk .codelist > ${maps[${j}]}
    done
    return $?
}

function fn_10jqka()
{
    iconv -f cp936 -t utf8 /10jqka/BlockUpdate/block_conception.ini > .10jqka.ini
    cat .10jqka.ini | grep -E '^40=|^B3=|^[0-9A-F]{4}=[^$]' | grep -v ':' > ${blk_name}.raw
    cat .10jqka.ini | grep -E '^40=|^B3=|^[0-9A-F]{4}=[^$]' | grep    ':' > ${blk_list}
    sed -i -e 's/^/0x/g' -e 's/=/\t/g' ${blk_name}.raw
    sed -i -e 's/^/0x/g' -e 's/[0-9][0-9]://g' -e 's/=/,/g' -e 's/,$//g' ${blk_list}

    awk '{printf "%d\t%s\n", $1,$2}' ${blk_name}.raw > ${blk_name}

    awk -F ',' '{
        for (i = 2; i <= NF; i++) {
            printf("%d\t%s\n", $1,$i)
        }
    }' ${blk_list} > ${blk_memb}

    echo "
    TRUNCATE TABLE blk_name;
    TRUNCATE TABLE blk_memb;
    LOAD DATA LOCAL INFILE '${blk_name}' INTO TABLE blk_name;
    LOAD DATA LOCAL INFILE '${blk_memb}' INTO TABLE blk_memb;
    " | mysql kts
    xt_ret $? "mysql" || return $?
    
    fn_echo_succ "up blk succ!"
}

function fn_up_bbd()
{
    echo "
    CREATE TABLE IF NOT EXISTS mat_bbd (
        id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
        date        date NOT NULL DEFAULT 0,
        time        time NOT NULL, 

        rise        DECIMAL(12,2) NOT NULL DEFAULT 0,
        dde         DECIMAL(12,2) NOT NULL DEFAULT 0,

        bbd_net     DECIMAL(12,2) NOT NULL DEFAULT 0,
        bbd_amount  DECIMAL(12,2) NOT NULL DEFAULT 0,
        bbd_buy     DECIMAL(12,2) NOT NULL DEFAULT 0,
        bbd_sell    DECIMAL(12,2) NOT NULL DEFAULT 0,

        up          INT,
        down        INT,
        name        CHAR(16),
        INDEX(date,time,name)
    );

    CREATE TABLE IF NOT EXISTS bbd LIKE mat_bbd;

    DROP   TEMPORARY TABLE IF EXISTS bbx;
    CREATE TEMPORARY TABLE bbx LIKE mat_bbd;
    LOAD DATA LOCAL INFILE '${wolf_rip}' INTO TABLE 
           bbx(date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name);

    DELETE FROM     bbd WHERE date='${CURR}';
    INSERT INTO     bbd(date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name)
        SELECT date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name FROM bbx;

    DELETE FROM mat_bbd WHERE date='${CURR}' && time='${HHMMSS}';
    INSERT INTO mat_bbd(date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name) 
        SELECT date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name FROM bbx;
    " | mysql kts   
    return $?
}

function fn_bbd()
{
    fn_get_export_file
    xt_ret $? "" || return $?

    # 代码   名称  机构动向     主动买入比  被动买入比  主动卖出比  被动卖出比 
    # 涨幅%  现价  涨速%        总手        换手        金额        流通市值    所属行业
    iconv -f cp936 -t utf8 ${efile} | tail -n+2 > ${wolf_raw}
    if ! grep -q '机器人概念' ${wolf_raw}; then
        fn_echo_fail "not a bbd file"
        return 1
    fi

    tag_blank='--.--.--'
    sed -e 's///g' -e 's/S.//g' -e 's/ //g'               \
        -e 's/%//g' -e 's/\t$//g' -e 's/\t\t*/\t/g'         \
        -e "/${tag_blank}/d" -e '/^$/d' ${wolf_raw}         \
        | awk '{
            printf "%s\t%s\t%.2f\t%.2f\t%.2f\t%.2f\t%s\t%s\t%s\n",
            $2,$3,$4/10000,$5/10000,$6/10000,$7/10000,$8,$9,$1
        }' \
        | sed "s/^/${CURR}\t${HHMMSS}\t/g" > ${wolf_rip}
    xt_ret $? "" || return $?

    # echo ${efile} ${ctime} ${epoch} $HHMMSS

    fn_up_bbd
    xt_ret $? "" || return $?
}

function fn_layout_bbd()
{
    sqls="
    SELECT l.code,count(l.code) as num, c.name FROM 
        (SELECT m.code FROM (
            SELECT name FROM bbd ORDER by bbd_amount DESC LIMIT ${LIMIT:-2}) as t, 
            blk_name as n, blk_memb as m 
            WHERE n.sym=t.name && n.blk=m.blk) as l, cap as c 
    WHERE l.code=c.code 
    GROUP by code 
    HAVING 1 ${COND}
    ORDER by num DESC
    " 
    mysql ${OPT:--t} kts <<<"${sqls}"
    fn_chao ${chao}.bbd
}


function fn_main()
{
    CURR=`fn_maxdate`
    case $1 in
    b|B|BBD)
        fn_bbd
        ;;
    d|dzh)
        fn_dzh
        ;;
    t|10jqka)
        fn_10jqka
        ;;
    l|layout_bbd)
        fn_layout_bbd
        ;;
    *)
        echo "
        Usage: blk <param>
        dzh         # dzh
        10jqka      # 同花顺
        bbd         # 操盘热点导入
        c           # 热点code
        l           # 热点layout，观察概念叠加
        "
        ;;
    esac
    return $?
}

fn_main $@
