#! /bin/bash

# 小金属
# 除了用在军工上以外，很多新兴产业都要用到，主要包括
# 钛：宝钛股份、西部材料；锆：东方锆业；钽：东方钽业；锗：云南锗业；
# 铼：炼石有色；钨：中钨高新、厦门钨业、章源钨业；钼：金钼股份、洛阳钼业；
# 稀土：五矿稀土、包钢稀土、广晟有色。
# [互联网+](http://mt.sohu.com/20150311/n409644432.shtml)
# [互联金融](http://www.360doc.com/content/14/0201/22/1632548_349253018.shtml)

function fn_main()
{
    CWD=${PWD}
    BLK='/dzh2/USERDATA/block'
    maps=(
        深成40.BLK      .blk.sc40
        创业板指.BLK    .blk.cybz
        深证300P.BLK    .blk.sz300p
        中证500.BLK     .blk.zz500

        军工指数.BLK    .blk.jgzs
        融资融券.BLK    .blk.rzrq
        券商.BLK        .blk.qs
        保险业.BLK      .blk.bxy
        银行业.BLK      .blk.yhy
        房地产.BLK      .blk.fdc
        300地产.BLK     .blk.300dc
        上海国资.BLK    .blk.shgz
        互联金融.BLK    .blk.hljr

        节能环保.BLK        .blk.jnhb
        污水处理.BLK        .blk.wscl
生态保护和环境治理业.BLK    .blk.hjzl
    )
    local i j
    for (( i=0,j=1; i<${#maps[@]}; i+=2,j+=2 )); do
        test ${maps[${j}]} -nt ${BLK}/${maps[${i}]} && continue
        echo ${maps[${i}]} ${maps[${j}]}
        cat ${BLK}/${maps[${i}]} | \
            tr -cd '[0-9SZH]' | sed 's/S[HZ]/\n/g'| \
            tail -n+2 | sort -g | grep '^[036]' > ${maps[${j}]}
    done
    return $?
}

fn_main
