#! /bin/bash

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /root/bin/common.rc

function fn_xunner()
{
    printf "%6s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%-5s\t%5s\t%5s\t%5s\n" \
            symbol avrg trade chng yesc open high pcnt_hi loww pcnt_lo turnov vratio name

    # cat ${buffer} 

    sed -n '1,2p' ${buffer}  | 
        tr -d '\n' | tr "'" '"' | 
        sed -e 's/^.*= *//' -e 's/;.*$//' | 
        JSON.sh -b | tr -d '"' | 
        awk '{printf \
                "%s\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%s\n", 
                $1,(100*$3-$10/($9+0.00001))/($3+0.00001),
                $3,$4, $5, $6, $7, 100*($3-$7)/$5, $8, 100*($3-$8)/$5, $11, $13, $2
        }' | sort -g -r -k4
}

fn_realtime()
{
    url='http://quote.stock.hexun.com/stockdata/stock_quote.aspx?stocklist'
    url="${url}=$1"
    # echo ${url}

    while :; do
        w3m -dump "${url}" 2>/dev/null | \
            sed -e 's/;indexdataArr/;\nindexdataArr/' \
                -e 's/*//g'  -e 's/ST//g'  > ${buffer}

        [ -n "`head -c2 ${buffer}`" ] && break
        echo "${url}"
        echo "w3m fail, try again!"
        sleep .5
    done

    fn_xunner
}

#
# https://www.cnblogs.com/phpxuetang/p/4519446.html
#
function fn_main() 
{
    [ -z "$*" ] && echo "Usage: $0 code" && exit 
    fn_realtime `echo -n 00000${1} | tail -c6`
}

fn_main ${@}
