#! /bin/bash -
#  CREATED: 2014-08-13 23:39:33

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_get_url()
{
    # fenbi只能下载当天数据 & 每次最多输出1000条记录
    # http://webstock.quote.hermes.hexun.com/a/deal?code=szse000002&start=20140813151000&number=-10&callback=callback
    url0="http://webstock.quote.hermes.hexun.com/a/deal?"
    [ ${1:0:1} -eq 6 ] && sec=sse || sec=szse 
    echo "${url0}code=${sec}${1}&start=${2}&number=-1000"
}

function fn_str_2_datetime()
{
    dt2=19450815132000
    echo ${dt2:0:4}
    echo ${dt2:4:2}
    echo ${dt2:6:2}
    echo ${dt2:8:2}
    echo ${dt2:10:2}
    echo ${dt2:12:2}
}

function fn_main()
{
    code=$1
    date=`date +%Y%m%d`
    date=`fn_maxdate|sed 's/-//g'`  # uncomment when weekend
    datetime0="${date}092500"
    datetime4="${date}112900"
    datetime5="${date}130000"
    datetime9="${date}150000"
    dt=${date}135000         # init from mysql
    raw='/tmp/raw'
    ripe='/tmp/ripe'
    cache='/tmp/cache'
    buffer='/tmp/buffer'
    lockfile='/run/lock/fenbi'

    >${buffer}

    while :; do
        url=`fn_get_url ${code} ${dt}`
        echo ${url}
        timeout 30 w3m -dump ${url} > ${raw}
        xt_ret $? "timeout" || return $?

        time cat ${raw} | sed -n '/\[\[/,$p' |      # Data:
            sed  -e '1s/^.*\[\[/[[/' -e '$s/]].*$/]]/' > ${ripe}

        [ "`stat -c%s $ripe`" -lt 80 ] && break      # 2 record at list
        
        cat ${ripe} | JSON.sh -b |
            awk -v code=$code \
                '{printf "%s\t%s\t%s\t%s\t%s\t%s\n", code,$1,$2,$3,$4,$5 }'>${cache} 
        xt_ret $? "" || return $?

        [ "${dt}" != "${datetime0}" ] && sed -i '1d' ${cache}
        cat ${cache} # >> ${buffer}
        true && {
            flock 20
            sqls="LOAD DATA LOCAL INFILE '${cache}' INTO TABLE fenbi
                  (code, datetime, trade, amount, volume, type1)"
            mysql -t kts <<< "${sqls}"
            # exit
        } 20<>${lockfile}

        dt=`tail -1 ${cache} | awk '{print $2}'`
        [ "${dt}" -ge ${datetime9} ] && break

        # exit # uncomment to w3m once
    done
}

# 数据的延时在30s内
fn_main 000002
# fn_main 399006
