#! /bin/bash -
#  CREATED: 2014-08-13 23:39:33

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc


# 下载分笔数据
# function fn_down_fenbi()
# {
#     # sina的分笔粒度是最小的，分笔数据3家对比详见：
#     mkdir -p `dirname $fenbi_raw`
# 
#     host="http://hqdigi2.eastmoney.com/EM_Quote2010NumericApplication/CompatiblePage.aspx?"
#     para="Type=OB&stk=000002&Reference=xml&limit=0&page="
# 
#     page_cnt=`$W3M -dump "$host${para}1" 2>/dev/null | head -1 | awk -F"[:,]" '{print $2}'`
#     [ -z "$page_cnt" ] && echo "error: null page_cnt" && exit
# 
#     > $fenbi_raw
#     local i
#     for (( i=1; i<=$page_cnt; i++ )); do
#          url=$host${para}$i
#          $W3M -dump "$url" 2>/dev/null >> $fenbi_raw
#          xt_ret $? "NETWORK" || return $?
#     done
# 
#     sed -i '/jsTimeSharingData/d' $fenbi_raw
#     cat $fenbi_raw | tr -d '[' | tr -d ']};' | sed 's/","/\n/g'  | tr -d '"' > ${fenbi_ripe}
# }

function fn_get_url()
{
    # fenbi只能下载当天数据 & 每次最多输出1000条记录
    # http://webstock.quote.hermes.hexun.com/a/deal?code=szse000002&start=20140813151000&number=-10&callback=callback
    url0="http://webstock.quote.hermes.hexun.com/a/deal?"
    [ ${1:0:1} -eq 6 ] && sec=sse || sec=szse 
    echo "${url0}code=${sec}${1}&start=${2}&number=1000"
}

function fn_hexun()
{
    code=$1
    date=`date +%Y%m%d`
    #date=`fn_maxdate|sed 's/-//g'`  # uncomment when weekend
    datetime0="${date}092500"
    datetime4="${date}112900"
    datetime5="${date}130000"
    datetime9="${date}150000"

    >${buffer}
    [ "${dt}" -lt ${datetime9} ]
    xt_ret $? "It's latest" || return $?

    while :; do
        url=`fn_get_url ${code} ${dt}`

        echo ${url}; # exit
        timeout 30 w3m -dump ${url} > ${fenbi_raw}
        xt_ret $? "timeout" || return $?

        cat ${fenbi_raw} | sed -n '/\[\[/,$p' |
            sed  -e '1s/^.*\[\[/[[/' -e '$s/]].*$/]]/' > ${fenbi_ripe}

        [ "`stat -c%s $fenbi_ripe`" -gt 80 ]
        xt_ret $? "no data" || return $?
        
        cat ${fenbi_ripe} | JSON.sh -b |
            awk -v code=$code '{
                printf "%s\t%s\t%.2f\t%.2f\t%.2f\n", 
                code,$1,$2/100,$4/100,$3/100
        }' | sed "/${dt}/D" >${cache} 
        xt_ret $? "" || return $?

        cat ${cache} >> ${buffer}
        dt=`tail -1 ${cache} | awk '{print $2}'`
        end=`tail -1 /dev/shm/fenbi/raw | awk -F',' '{print $12}'`
        [ "${dt}" -ge ${end} ] && break

        # exit # uncomment to w3m once
    done

    true && {
        flock 20
        echo "
        TRUNCATE TABLE tmpfb;
        LOAD DATA LOCAL INFILE '${buffer}' INTO TABLE tmpfb;
        INSERT INTO fenbi(code, datetime, trade, volume, amount)
          SELECT code,datetime,trade,sum(volume),sum(amount) FROM 
            (SELECT *,round(datetime%1000000/${mod_fb},0) as grp from tmpfb ORDER by datetime DESC) 
                as newfb GROUP by grp ORDER by datetime;
        " | mysql -t kts 
        xt_ret $? "" || return $?
    } 20<>'/dev/shm/fenbi/lock'
}

function fn_fenbi()
{
    # 数据的延时在30s内
    code=${1}
    fn_iscode ${code}
    xt_ret $? "Usage: fenbi {s|code}" || return $?

    today=`date +%F`
    sql="SELECT max(datetime) FROM fenbi WHERE code=${code}"
    dt=`mysql -N kts <<< "${sql}"`
    fmaxdate=`fn_str_2_date ${dt}`
    # echo ${dt}

    if [ "${dt}" = NULL ]; then
        echo "NULL database, run ./mi5 first"
    else
        sql="SELECT date FROM day WHERE code=${code} and date>'${fmaxdate}' and date<'${today}';"
        dates=(`mysql -N kts <<< "${sql}"`)

        if [ ${#dates[@]} -ne 0 ]; then
            echo "There are dates(${dates[@]}) of ${code} absent, ./mi5 first"
            exit
        else
            echo "Going to update data of ${code}"
        fi
    fi

    # read -p "Type any key to continue, Ctrl-C to interrupt"
    # DELETE FROM  fenbi WHERE datetime > 20150303000000

    fn_hexun $code
    xt_ret $? "" || return $?
    fn_echo_succ "DL and load mini-fenbi of ${code} succ!"
}

function fn_squeeze()
{
    codes=`mysql -N kts<<<'SELECT DISTINCT code FROM fenbi'`
    count0=`mysql -N kts<<<'SELECT count(*) FROM fenbi'`
    
    local i=
    for i in ${codes}; do
        sqls="SELECT date FROM day WHERE code=${i} ORDER by date DESC LIMIT 40,1"
        date=`mysql -N kts<<<"${sqls}"`
        dt=${date//-/}160000
        fn_isdatetime ${dt}
        xt_ret $? "bad format: ${dt}" || return $?
        sqls="DELETE FROM fenbi WHERE code=${i} and datetime<${dt}"
        mysql -N kts<<<"${sqls}"
        echo squeeze ${i} before ${dt} over
    done

    count1=`mysql -N kts<<<'SELECT count(*) FROM fenbi'`
    let count2=count0-count1
    fn_echo_succ "squeeze ${count2} record total"
}


function fn_main()
{
    case $1 in
    s|squeeze)
        fn_squeeze
        ;;
    *)
        fn_fenbi $@
        ;;
    esac

    return $?
}

fn_main $@
