#! /bin/bash -
#---------------------------------------------------------------------------
#          FILE: google
#         USAGE: ./google
#        AUTHOR: chuangxiaomoo (God helps those who help themselves) 
#  ORGANIZATION: 
#       CREATED: 2013-09-04 01:40:57 CST
#      REVISION: 1.0 
#---------------------------------------------------------------------------

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_google() 
{
    key=$1
    echo "w3m -dump 'http://data.stock.hexun.com/include/AjaxSearch2011.ashx?key=$key'"  > /dev/stderr
    w3m -dump "http://data.stock.hexun.com/include/AjaxSearch2011.ashx?key=$key" > ${buffer}
    xt_ret $? "NETWORK" || return $?

    cat $buffer | 
        sed -e 's/*//g'  -e 's/ST//g' |
        tr -d '\n' | tr "'" '"' |
        sed -e 's/^.*= //' -e 's/;$//' |
        sed -e 's/\<[a-z]\{3,\}\>/"&"/g' -e 's/""/"/g' > $memory

    cat ${memory} |
        JSON.sh -b | tr -d '"' | grep '^[630][0-9]'
}


function fn_google0() {
    [ -z "$*" ] && echo "Usage: $0 symbole" && exit 

    local i=
    for i in $@; do
        case $i in +([0-9])) echo $i && continue ;; esac

        host='https://www.google.com.hk/finance/match'
        host="${host}?matchtype=matchall&hl=zh-CN&ei=K6cmUpCpNomukgWYzgE&q="
        host="${host}$i"
        $W3M -dump "${host}" > $buffer
        xt_ret $? "NETWORK" || return $?

        cat $buffer | \
            sed -e 's/\},/&\n/g' -e 's#["{}]##g' -e '1s#^.*\[##g' -e '$s#].*##g' | \
            sed -e 's/[a-z]*://g' > $memory

        awk -F',' '/SHA|SHE/ {printf "%-8s%s\n", $1, $2}' $memory
    done
}


function fn_main() 
{
    # index=2

    [ "${#}" -eq 1 ] || { echo "Usage: $0 {code|symbol}"; exit; }
    if fn_iscode ${1}; then
        codes=$1
    else
        fn_google $@ | tee $cache
        [ 0 -ne  "${PIPESTATUS[0]}" ] && echo google fail && exit 1
        codes=`cat $cache | awk '{print $1}' | xargs`
        codes=${codes// /,}
    fi

    [ -z "${codes}" ] && echo "Error: null codelist" && exit 1
    mysql -t kts<<< "SELECT * FROM cap WHERE code in (${codes}) ORDER by nmc" 
}

fn_main $@

