#! /bin/bash -

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; } 
. /etc/common.rc

function fn_fmt_hexun() {
    awk -F',' -v v_date=$DATE -v v_time=$TIME '{ 
        printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%.2f\t%s\t%s\t%s\t%s\t%s\t%s\n", \
                $1, $3, $4, $5, $6, $7, $8, $9,$10,$11,$12,$13,v_date,v_time
    }' $1
}

function fn_hexun() {
    # sorttype {origin 0} updown {up从大到小}
    local host='http://quote.tool.hexun.com/hqzx/'
    local sh='quote.aspx?type=2&market=1&sorttype=3&updown=up&page=1&count=1200'
    local sz='quote.aspx?type=2&market=2&sorttype=3&updown=up&page=1&count=2000'
    #ocal gem='stocktype.aspx?columnid=5500&type_code=Y0003&sorttype=3&updown=up&page=1&count=500'
    #GEM(growth enterprise market)

    for link in $host$sz $host$sh ; do
        echo $link >> $hx_stderr
        $W3M -dump $link > $hx_rawxml 2>$hx_stderr
        xt_ret $? "NETWORK" || return $?

        cat $hx_rawxml | sed -e '1s/.*\[ //g' -e '$d' | \
            tr -d '\n' | tr -d ' ' | tr -d "'" | tr -d '[' | \
            sed -e 's/\],/\n/g' -e '$s/]];//g'> $hx_ripexml
        fn_fmt_hexun $hx_ripexml
    done > $hx_ripetxt
}

function fn_main() {
    iDATE=`date +%Y-%m-%d`
    DATE=${DATE:-${iDATE}}
    TIME=`date +%H:%M:00`       # no need second

    mkdir -p ${hx_rawxml%/*}

    fn_hexun
    xert $? `$PS8` "fn_hexun fail" || return $?
}

# 
# 1 从统计来看，hexun不统计当日停牌的股票，且较sina要准确

# 2 从速度数据来看，hexun是sina的1/4
#       hexun  sina
#       8s      30s
#       5s      22s
#
# 3 代码 名称 最新价 涨跌幅 昨收 今开 最高 最低 成交量 成交额 换手 振幅 量比
#   成交额以万为单位，成交量以手为单位 (sina成交量是自然单位股)
#
#   code name trade pricechange close open high low volume amount turnoverratio
#   changepercent volumeratio 
#   
# 4 sina比hexun的优势，其有总市值及流通市值数据，以万为单位
#

fn_main $@

