#! /bin/bash

. /etc/common.rc

function fn_main()
{
    YIST=${YIST:-'.soptter.trade'}
    codes=(`cat ${YIST} | awk '/^[036]/{print $1}'`)
    case $1 in
    c)
        [ "${#}" -eq 1 ] && fn_main
        local i=
        for i in ${codes[@]}; do
            ${@:2} ${i} 
            xt_ret $? "error: ${@:2} ${i}" || return $?
        done
        ;;

    g|code2sym)
        [ "${#}" -eq 1 ] && fn_main
        local i=
        for i in ${@:2}; do
            test -f ${i}
            xt_ret $? "error: ${i} not exist" || return $?
        done
        for i in ${codes[@]}; do
            grep --color ${i} ${@:2}
        done
        ;;

    l|list)
        echo ${codes[@]}
        ;;

    s|sym2code)
        cat $YIST | awk '/^[^#]/{print $1}' | xargs -I{} grep {} .codelist
        ;;
    *)
        echo "Usage: YIST=xx $0 c cmd..."
        echo "       YIST=xx $0 {l|list}"
        echo "       YIST=xx $0 {g|grep_code} haystack_files..."
        echo "       YIST=xx $0 {s|sym2code}"
        exit
        ;;
    esac
    
    return $?
}

fn_main $@
