#! /bin/bash -
#---------------------------------------------------------------------------
#       CREATED: 2013-11-12 10:29:02 CST
#---------------------------------------------------------------------------
. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_parser_load()
{
    sed -e 1d -e 's/://g' ${fenbi_raw1} | 
    awk -v code=${code} -v date=${date//-/} '{
        printf "%s\t%s%s\t%s\t%s\t%.2f\n", code,date,$1,$2,$4,$5/100
    }' > ${cache}


    echo "
        TRUNCATE TABLE tmpfb;
        LOAD DATA LOCAL INFILE '${cache}' INTO TABLE tmpfb;
        INSERT INTO fenbi(code, datetime, trade, volume, amount)
          SELECT code,datetime,trade,sum(volume),sum(amount) FROM 
            (SELECT *,round(datetime%1000000/${mod_fb},0) as grp from tmpfb ORDER by datetime DESC) 
                as newfb GROUP by grp;
    " | mysql -t kts 
}



function fn_sina()
{
    today=`date +%F`
    sql="SELECT max(datetime) FROM fenbi WHERE code=${code}"
    datetime=`mysql -N kts <<< "${sql}"`
    fmaxdate=`fn_str_2_date ${datetime}`
    # echo ${datetime}

    [ -n "${datetime}" ]
    xt_ret $? "Try create kts.fenbi and tmpfb mannually" || return $?

    if [ "${datetime}" = NULL ]; then
        sql="SELECT date FROM (SELECT date FROM day WHERE code=${code} ORDER by date DESC LIMIT ${NUM:-20})
                as tbl ORDER by date ASC"
    else
        [ `date +%H%M%S` -gt 153000 ] && equal='='
        sql="SELECT date FROM day WHERE code=${code} and date>'${fmaxdate}' and date<${equal}'${today}';"
    fi

    echo "${sql}"

    dates=(`mysql -N kts <<< "${sql}"`)

    if [ ${#dates[@]} -eq 0 ]; then
        echo "It's latest of ${code}, do fenbi to today"
    fi

    local i
    for (( i=0; i<${#dates[@]}; i+=1 )); do
        date=${dates[$i]}
        sina='http://market.finance.sina.com.cn/downxls.php?'
        [ ${code:0:1} -eq 6 ] && sec=sh || sec=sz

        echo download ${code} on ${date}
        wget "${sina}date=${date}&symbol=${sec}${code}" -O ${fenbi_raw1} 2>/dev/null
        xt_ret $? "" || return $?

        fn_parser_load
        xt_ret $? "" || return $?

        #break;
    done

    return $?
}


function fn_main()
{
    code=${1}
    fn_iscode ${code}
    xt_ret $? "Usage: mi5 code" || return $?

    # volume以手为单位，最终数据倍数是day中的100倍

    fn_sina
    xt_ret $? "sina" || return $?

    fn_echo_succ "DL and load fenbi of ${code} succ!"
    
}

fn_main $@

