#! /bin/bash

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_routine_10()
{
    fn_echo_warn '
    Warning:-----------------------------------------------------------------
    1. 跌不必贱，涨不必贵，水无贵贱。水能载舟，亦能覆舟，上善若水。
    2. 请遵守F5x3有效确认(K线实体站上ma55，即便晚15分，你的成本也很低)
    3. 根据大盘决定整体仓位
    4. (a)保住本金; (b)请永远记住第一条; (c)直至2015-07-30最后5分钟亦可出半仓
    5. 如遇涨停，挂1/2委托单做T+0(不因利小而不为)
    '
}

function fn_routine()
{
    tips_cnt=0
    tips_old=0
    tips_got=''
    >${list_limo}

    while read code symble COND0 tips; do
        # echo "read code=${code} ${COND0}"
        [ "${COND0:-0}" == 0 ] && continue
        if ! ${istest} && [ "$code" != '/' ]; then                              # istest
            echo do fenbi ${code}...
            fenbi ${code} >& ${error}
            xt_ret $? "down ${code}" || { cat ${error}; return $?; }
        fi

        if [ "${code}" = '/' ]; then
            code=$code0
        else
            # sina分时数据缺失会导致ma80(F15)失真，因此
            # macd计算作为BuySell的标配进行，不做任何限制
            echo "do _dif_ ${code}..."
            FM=5 macd ${code}
            xt_ret $? "macd error" || return $?

            FM=15 macd ${code}
            xt_ret $? "macd error" || return $?

            sql='(FM=15)*IF(close>=fa20, 1, -1)*((fa20>=ma5)+(fa20>=ma10)+(fa20>=ma20)+(fa20>=ma40)+(fa20>=ma80))'
            sql="SELECT ${sql} FROM mm55 WHERE code=${code} and FM=15"
            limo=`mysql -N kts <<<"${sql}"`

            # 5日线上，B用4数，S用3数；5日线下，B用3数，S用3数
            sql="SELECT IF(close>ma80,4,3) FROM mm55 WHERE code=${code} and FM=15"
            buyn=`mysql -N kts <<<"${sql}"`
        fi

        case ${COND0:-B} in
        B|b|bm)
            if [ ${COND0} = B ] && [ "${limo}" -gt 0 ] && [ "${limo}" -ge ${buyn:-3} ]; then
                fn_echo_succ "$code.$symble.${FM}.limo ${COND0}"
                let tips_cnt+=100
            fi
            if [ "${COND0}" = bm ]; then
                sql="SELECT IF(macd>0, 1, 0) FROM mm55 WHERE code=${code} and FM=5"
            else
                sql="SELECT IF(dif>0&&close>=fa20, 1, 0) FROM mm55 WHERE code=${code} and FM=5"
            fi
            ret=`mysql -N kts <<<"${sql}"`
            if [ "${ret}" = 1 ]; then
                fn_echo_succ "$code.$symble.${FM}.macd ${COND0}"
                let tips_cnt+=100
            fi
            ;;
        S|s|sm)
            if [ ${COND0} = S ] && [ "${limo}" -le 0 ] && [ "${limo#-}" -lt 3 ]; then
                fn_echo_succ "$code.$symble.${FM}.limo ${COND0}"
                let tips_cnt++
            fi
            if [ "${COND0}" = sm ]; then
                sql="SELECT IF(macd<0, 1, 0) FROM mm55 WHERE code=${code} and FM=5"
            else
                sql="SELECT IF(dif<0&&close<=fa20, 1, 0) FROM mm55 WHERE code=${code} and FM=5"
            fi
            ret=`mysql -N kts <<<"${sql}"`
            if [ "${ret}" = 1 ]; then
                fn_echo_succ "$code.$symble.${FM}.macd ${COND0}"
                let tips_cnt++
            fi
            ;;
        *)
            grep -q -E 'd1|m1' <<< "${COND0}" && macd ${code} f1
            grep -q -E 'dif|macd|d1|m1|ma[12]' <<< "${COND0}" && FM=5 || FM=15
            COND0=${COND0//m6/macd}
            COND0=${COND0//d6/dif}
            # echo ${COND0}; exit
            sql="SELECT IF(${COND0}, 1, 0) FROM mm55 WHERE code=${code} and FM=${FM}"
            ret=`mysql -N kts <<<"${sql}"`
            if [ "${ret}" = 1 ]; then
                fn_echo_succ "$code.$symble.${FM}.cond ${COND0} ${tip}"
                grep -q '>' <<< "${COND0}" && let tips_cnt+=100 || let tips_cnt++
            elif [ "${ret}" = "" ]; then
                fn_echo_fail "bad cond: ${COND0}"
                fn_bell "msg.wav"
            fi
            ;;
        esac

        [ "${tips_cnt}" -gt ${tips_old} ] && echo ${code} >> ${list_limo}
        code0=$code
        tips_old=${tips_cnt}
    done<<<"`grep ${PATTERN:-'^[/036]'} .soptter.macd`"
    
    #echo ${tips_cnt}
    local i
    for (( i=tips_cnt%100; i>0;  i-=3  )); do
        tips_got="${tips_got} duang.wav"            # 卖：2个股+2指数 = 一级戒备
    done

    for (( i=${tips_cnt}; i>99; i-=300 )); do
        tips_got="${tips_got} msg.wav"              # 买：2个股+2指数 = 一级戒备
    done
    #echo ${i}
    #echo ${tips_got}
    if [ -n "${tips_got}" ]; then
         fn_bell "$tips_got"
         YIST=${list_limo} SELECT macd
    fi

    fn_echo_warn "\
    Warning:--------------钱、势、惊、生---------------------------------
    1. 余额宝、钱去哪儿了？(加大打击内幕交易和操纵市场)
    2. 3大指数全绿，徐工机械的盈利只是浮动
    3. 异于平常，即为背离(顺势者聪明钱，聪明钱不逆势)"
    fn_echo_fail "\
    4. 大高开危机：连板开板(光韵达)，6%之上，不买入(弱市)
    5. 大股本危机：高于100亿，每天成交10亿(&市场变)
    6. 大换手危机：连阳高于100%，1日高于前日1.6倍"
    fn_echo_succ "\
    7. 20%涨幅请减半仓
    8. 智者先考虑风险、再考虑盈利。愚者反之。
    "
}

function fn_loop()
{
    while :; do
        fn_isresting && { sleep 150; continue; }
        fn_routine
        echo "to sleeping ${STEP:=62}s"         # F5x3有效突破，即3线之内，低点抬高，高点亦抬高
        sleep ${STEP}                           #               若是大阳线，则不破1/2长度
    done
    return $?
}

function fn_usage()
{
    echo "Usage: nb_macd code"
    echo "       nb_macd l|loop"
    echo "       nb_macd t|test_all"
    exit
}

function fn_test_all()
{
    fn_routine
    xt_ret $? "" || return $?
}

function fn_test_code()
{
    fn_iscode ${1}
    xt_ret $? "bad code ${1}" || return $?

    PATTERN="^${1}" fn_routine
    xt_ret $? "" || return $?

    return $?
}

function fn_main()
{
    istest=false
    case $1 in
    l|loop)
        fn_loop
        ;;
    t|test_all)
        istest=true
        fn_test_all
        ;;
    [0-9][0-9]*)
        fn_test_code ${@}
        ;;
    *)
        fn_usage
        ;;
    esac

    return $?
}

fn_main ${@}
