#! /bin/bash

# 1. up 4 获取当天非停牌股票 > /tmp/mx/soptter.nmc
# 2. LIST=/tmp/mx/soptter.nmc xunner 并写表 tbl_a
# 3. 使用 cap 计算出 turnover
# 4. step2 and step3 的两个数据进行比对。


. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc


function fn_update()
{
    echo "
        SELECT code FROM day WHERE date='$END';
    " | mysql -N kts | sort -u | head -n-1 > ${today}

    split -l 1000 ${today} /tmp/mx/pfx.
    > ${today}.tov

    local i=
    for i in /tmp/mx/pfx.* ; do
        LIST=${i} xunner | tail -n+5 | head -n-1 | grep -v TCL | awk '{printf "%s\t%.3f\n", $1, $7}'
    done >> ${today}.tov
    # ='/tmp/mx/soptter.nmc.tov'

    lines=`cat ${today}.tov | wc -l`
    [ $lines -gt 2000 ]
    xt_ret $? "$lines less than 2000 lines" || return $?
}

function fn_main()
{
    today='/tmp/mx/soptter.nmc'
    mkdir -p ${today%/*}

    CURR=`fn_maxdate`
    END=${END:-${CURR}}

    # fn_update
    # xt_ret $? "" || return $?

    i=tbl_tov
    echo "
    DROP TABLE IF EXISTS $i;
    CREATE TABLE ${i} (
        id          INT     PRIMARY key AUTO_INCREMENT NOT NULL,
        code        INT(6)  ZEROFILL NOT NULL DEFAULT 0,
        tov        DECIMAL(6,2) 
    );
    LOAD DATA LOCAL INFILE '${today}.tov' INTO TABLE ${i} (code,tov);
    " | mysql kts
    xt_ret $? "" || return $?

    echo "
    SELECT d.code, $TURNOV as turnover, t.tov, $TURNOV/t.tov as ratio, c.nmc, c.name
            FROM (SELECT * FROM day WHERE date='$END') as d,cap as c, tbl_tov as t 
            where d.code = c.code and t.code = c.code 
            and tov > 2
            HAVING (abs(ratio-1)>.3) and turnover > 2
	" | mysql -t kts
}
# UPDATE cap SET nmc=  WHERE code=; 
fn_main
