#! /bin/bash

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_peel() {
    # from SINA
    # http://www.cnblogs.com/chuncn/archive/2009/06/26/1400997.html
    record=(`grep $1 ${rt_ripetxt} | tr ',' ' '`)
    [ -z "${record[*]}" ] && { echo "code[$1] get error" | fn_write; } && exit
    record=(${record[@]:1})     

     name=${record[0]} 
     open=${record[1]} 
 yesclose=${record[2]} 
    trade=${record[3]} 
     high=${record[4]} 
      low=${record[5]} 
   volume=${record[8]} 
   amount=${record[9]} 
     time=${record[31]}

     echo '$name $open $yesclose $trade $high $low $volume   $amount     $time'
     echo $name $open $yesclose $trade $high $low $volume $amount $time

      buy=`echo "($trade - $low ) > ( $low * $thrxhold)" | bc -l`
     sell=`echo "($high - $trade) > ($high * $thrxhold)" | bc -l`
}

# 实时探测
fn_realtime() {
    comma_sepa_list=`echo $@ | awk '{
        for (i=1; i<=NF; i++) {
            if ($i ~ /^6/) {
                printf "sh%s ", $i
            } else {
                printf "sz%s ", $i
            }
        }
    }' | tr ' ' ',' | sed 's/,$//g'`

    $W3M -dump "http://hq.sinajs.cn/list=$comma_sepa_list" > ${rt_stdout} 
    xt_ret $? "NETWORK" || return $?

    cat ${rt_stdout} | \
        sed -e 's/var hq_str_//g' -e 's/=/,/g' | \
        tr -d '"' | tr -d ';' | tr ':' '.' > ${rt_ripetxt} 

    for code in ${@}; do
        fn_peel $code

        if [ "$sell" -eq 1 ] ; then
            echo "$code     $trade      $time" | fn_write
            exit
        fi
    done
}

function fn_main() {
    
    mkdir -p ${rt_stdout%/*}
    codelist=( 000001 )
    thrxhold=.01               # .00382 .00618 .01 .01618

    while :; do
        fn_realtime ${codelist[@]}
        sleep 5
    done
}

fn_main
