#! /bin/bash
#---------------------------------------------------------------------------
#          FILE: SCREENER.sh
#         USAGE: ./SCREENER.sh
#   DESCRIPTION:
#        AUTHOR: chuangxiaomoo (God helps those who help themselves)
#  ORGANIZATION:
#       CREATED: 2013-12-11 08:46:51 AM
#      REVISION: 1.0
#---------------------------------------------------------------------------

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_dugu9jian()
{
    if [ "${TBL}" = windbell_codes ] && [ "`cat ${filewb}`" != ${CURR} ]; then
        echo "windbell_codes is out of day. continue to run [./up 22]"
        exit 1
    fi

    END=${1:-${END}}
    TBL=${TBL:-'cap'}
    NUM=${NUM:-81}        # 34太小，300104 2014-07-17 被漏掉了

    fn_isdate ${END} 
    xt_ret $? "    Usage: #{1} must be date like 2008-08-08" || return $?

    echo "
    To visit `mysql -N kts<<<"SELECT count(*) FROM ${TBL}"` codes on table $TBL...
    "

    echo "
    SET @END='$END';
    SET @NUM=${NUM};
    SET @NMC_RATIO=${NMC_RATIO:-1};
    call sp_visit_tbl('$TBL', @fn_dugu9jian);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?

    [ "${inwind}" = 1 ] || SELECT dugu9jian ${2:-wchng}
}

function fn_6maishenjian()
{
    END=${1:-${END}}
    TBL=${TBL:-'cap'}
    NUM=${NUM:-90}

    fn_isdate ${END} 
    xt_ret $? "    Usage: #{1} must be date like 2008-08-08" || return $?

    echo "
    To visit `mysql -N kts<<<"SELECT count(*) FROM ${TBL}"` codes on table $TBL...
    "

    echo "
    SET @END='$END';
    SET @NUM=${NUM};
    SET @NMC_RATIO=${NMC_RATIO:-1};
    call sp_visit_tbl('$TBL', @fn_6maishenjian);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?

    SELECT 6maishenjian ${2:-down}
}

function fn_taox_ratio0()
{
   #columns=date_p,date_c,off_p,off_c,tnov_p,tnov_c,avrg_p,avrg_c,ratio
    columns=date_p,off_p,date_c,off_c,tnov_c,avrg_p,avrg_c,ratio,wchng
    columns=${columns:-'*'}
    columns=t.${columns//,/,t.}

    echo ----- COND: $COND -----
    function fn_get_tbl_taox_dive()
    {
        tbl_super_dive="
        SELECT t.code,  ${columns}, c.nmc,c.name 
           FROM ${tablex:-tbl_taox} as t, cap as c 
           WHERE t.code = c.code HAVING 1 ${COND} 
           ORDER by ${1:-ratio} ${ASC:-asc} limit ${LIMIT:-24}
        "
        echo "${tbl_super_dive}"
    }

    fn_get_tbl_taox_dive $1
    mysql $mo -t kts <<< "${tbl_super_dive}" |\
        sed -e '1,3s/----+$/\+/g' -e '$s/----+$/\+/g' -e '2s/    |$/|/g'
    xt_ret ${PIPESTATUS[0]} "${FUNCNAME}" || return $?
}

function fn_taox_ratio()
{
    iEND=${1:-${END}}
    TBL=${TBL:-'cap'}
    NUM=${NUM:-240}        # 需要200%，所以应该比较大

    fn_isdate ${iEND} 
    xt_ret $? "    Usage: #{1} must be date like 2008-08-08" || return $?

    # echo "
    # To visit `mysql -N kts<<<"SELECT count(*) FROM ${TBL}"` codes on table $TBL...
    # "

    head -n -5 $mps_org > $mps_god
    echo "
    SET @END='$iEND';
    SET @NUM=${NUM};
    SET @FORCE=${FORCE:-0};
    SET @NMC_RATIO=${NMC_RATIO:-1};
    call sp_visit_tbl('$TBL', @fn_taox_ratio);
    " >> $mps_god # | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?

    [ "fn_tao5" = ${FUNCNAME[1]} ] || \
    fn_taox_ratio0 ${2:-ratio}
}

function fn_fbi_ratio()
{
    iDT=${1:-${DT}}
    TBL=${TBL:-'cap'}
    NUM=${NUM:-900}        # 30/day

    head -n -5 $mps_org > $mps_god
    echo "
    SET @DT=${iDT};
    SET @NUM=${NUM};
    SET @NMC_RATIO=${NMC_RATIO};
    call sp_visit_tbl('$TBL', @fn_fbi_ratio);
    " >> $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?
}

function fn_9jian()
{
    test -n "${1}" && fn_iscode ${1}       
    xt_ret $? "invalid code[$1]" || return $?

    local code=`sed 's/^0*//g' <<< $1 | xargs printf "%06d"`
    TBL=tbl_cost9 up file_to_table ${code}
    TBL=tbl_cost9 NUM=${NUM:-240} fn_dugu9jian
}

function fn_6jian()
{
    test -n "${1}" && fn_iscode ${1}       
    xt_ret $? "invalid code[$1]" || return $?

    local code=`sed 's/^0*//g' <<< $1 | xargs printf "%06d"`
    TBL=tbl_cost6 up file_to_table ${code}
    daysql="SELECT * FROM day WHERE code=${code} and date<='${END}' ORDER by date DESC limit 1"
    daysql=${daysql} TBL=tbl_cost6 NUM=${NUM:-240} fn_6maishenjian ${2:-$END} ${3:-wchng}
}

function fn_flush_code()
{
    echo "
    CREATE TABLE IF NOT EXISTS ${TBL} (
        id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0
    );
    TRUNCATE TABLE ${TBL};
    INSERT INTO ${TBL}(code) VALUES(${1});
    " | mysql -N -B kts
    
    return $?
}

function fn_tao()
{
    test -n "${1}" && fn_iscode ${1}       
    xt_ret $? "invalid code[$1]" || return $?
    fn_isdate ${2:-$END} 
    xt_ret $? "invalid date[$2]" || return $?

    local code=`sed 's/^0*//g' <<< $1 | xargs printf "%06d"`
    TBL=tbl_tao1 fn_flush_code ${code}
    TBL=tbl_tao1 NUM=${NUM:-240} fn_taox_ratio ${2:-$END} ${3:-ratio}
}

function fn_nmemb_of_10percent()
{
    # percent=5
    turnov200="
    SELECT sum(volume) FROM 
        (SELECT * FROM day WHERE code=${code} and date<='${END}' ORDER by date DESC LIMIT 200)
        as tbl INTO @sum_vol_200d;
        SELECT round((100*@sum_vol_200d/shares),2) FROM cap WHERE code = ${code};
    " 
    # mysql -N -B kts <<< "${turnov200}" ;exit

    nmemb=`echo "
    SELECT sum(volume) FROM 
        (SELECT * FROM day WHERE code=${code} and date<='${END}' ORDER by date DESC LIMIT 100)
        as tbl INTO @sum_vol;
    SELECT floor(${percent:-10}/(@sum_vol/shares)) FROM cap WHERE code = ${code};
    " | mysql -N -B kts`
    [ "${nmemb}" -ne 0 ] || nmemb=1
    return $?
}


function fn_clr_exitcode()
{
    echo "
     CREATE table IF NOT EXISTS exitcode (
     code   INT(6) ZEROFILL NOT NULL DEFAULT 0
     );
     truncate TABLE exitcode;
    " | mysql kts
    return $?
}

function fn_sql_exitsucc()
{
    return `mysql -N -B kts <<<"SELECT count(code) FROM exitcode"`
}

function fn_tao5()
{
    test -n "${1}" && fn_iscode ${1}       
    xt_ret $? "invalid code[$1]" || return $?
    local END=${2:-$END}
    fn_isdate ${END} 
    xt_ret $? "invalid date[$2]" || return $?

    local code=`sed 's/^0*//g' <<< $1 | xargs printf "%06d"`
    TBL=tbl_tao1 fn_flush_code ${code}

    # 强制 nmemb 以改变ratio粒度
    test -n "$nmemb" || fn_nmemb_of_10percent
    xt_ret $? "" || return $?

    ZIZE=${ZIZE:-10}  # 默认 2时为300%，调整以查看更多

    local sql="SELECT date from day WHERE code = ${code} and date<='${END}'"
    dates=(`mysql -N kts <<< "${sql} ORDER by date DESC" | 
                awk -v nmemb=${nmemb} '{if (! (a++%nmemb) ) print $1}'`)

    local size=${#dates[@]}
    let   idx=${size}-1
    local iNUM=${NUM:-300}

    echo "
    size: ${size} nmemb: ${nmemb} iNUM:${iNUM}
    going to list ${ZIZE} recodrs ${dates[$idx]} ~ ${dates[0]} ...
    "

    mysql kts <<<"truncate TABLE tbl_tao5"
    xt_ret $? "Don't worry, this error show when run 1st time"
    fn_clr_exitcode
    xt_ret $? "try create tbl_tao5: SCREENER tao 2" || return $?

    local i=0
    for (( i=0; i<${ZIZE}; i+=1 )); do
        [ "${i}" -eq 0 ] && b4=3 || b4=0
        FORCE=1 TBL=tbl_tao1 NUM=${iNUM} fn_taox_ratio ${dates[$i]} # | grep -B${b4} ${code}
        xt_ret ${PIPESTATUS[0]} "" || return $?

        if ! fn_sql_exitsucc; then
            fn_echo_warn "    so_little_data[$i ${dates[$i]}], try: up day ${code} ${dates[$idx]} 600\n"
            local RETCODE=1
            break
        fi
    done

    [ "fn_bei" = "${call}" ] || \
    SELECT tao5
    xt_ret $? "" || return $?

    col='code,date_p,date_c,off_p,off_c,tnov_p,tnov_c'
    col="${col},avrg_p,avrg_c,ratio,wchng"
    colA="A.${col//,/,A.}"
    echo "
    INSERT INTO tbl_rdiff(${col},cdiff,rdiff,dbrat)
    SELECT ${colA}, (A.avrg_c-B.avrg_c) as cdiff, (A.ratio-B.ratio) as rdiff,
                    100*(2*A.close-(A.avrg_p+A.avrg_c))/(A.avrg_p+A.avrg_c) as dbrat FROM tbl_tao5 A 
    INNER JOIN tbl_tao5 B on(A.id<B.id) GROUP BY A.id;
    " | mysql -N kts
    xt_ret $? "" || return $?

    return ${RETCODE:-0}
}

function fn_bei()
{
    [ -z "$1" ] && echo "Usage: bei {file|code...}" && exit 1
    [ -f "${1}" ] && lst=(`awk '/^[^#]/{print $1}' ${*} | sort -u`) || lst=(${@})

    echo "
    to visit ${#lst[@]} codes
    "

    # DROP TABLE tbl_tao5;
    # DROP TABLE tbl_tao1;
    # DROP TABLE tbl_taox;
    # DROP TABLE tbl_rdiff;
    # DROP TABLE tbl_fdiff;
    mysql kts <<<"truncate table tbl_rdiff;"
    xt_ret $? "try create tbl_rdiff: SCREENER tao 2" || return $?

    local i=
    for i in ${lst[@]}; do
        echo "# $i" # | tee /dev/stderr
       #ZIZE=${ZIZE:-5} call=fn_bei SCREENER tao5 ${i}
        ZIZE=${ZIZE:-3} call=fn_bei fn_tao5 ${i}
    done

    SELECT rdiff
    return $?
}


function fn_insert_codes_2_table()
{
    [ -z "${1}" ] && echo "Usage: insert tbl_name" && exit 1
    echo "
    INSERT INTO ${1}(code) SELECT code FROM ${tbl_ma_date} WHERE ${COND0};
    " | mysql kts
}

function fn_get_ma513()
{
    tbl_ma_date=tbl_mx_${END//-/_}

    if mysql kts<<<"SHOW TABLES" | grep -q ${tbl_ma_date}; then
        # 表 ${tbl_ma_date} 存在，且是闭市后构建
        # 表 tbl_ma513 是TBL的分析结果，供后续处理分析。
        if [ -f /tmp/mx/${tbl_ma_date} ]; then
            if [ "cap" = "${TBL:-cap}" ]; then
                fn_cp_tbl ${tbl_ma_date} tbl_ma513;
            else
                echo "
                DELETE from tbl_ma513;
                INSERT INTO tbl_ma513 SELECT * FROM ${tbl_ma_date}
                            WHERE code in (SELECT code FROM ${TBL});
                " | mysql kts # | tee /dev/stderr
                echo
            fi
            return 0
        fi
    fi

    echo "    build on ${TBL:-cap}..."

    echo "
    SET @END='$END';
    call sp_visit_tbl('${TBL:-cap}', @fn_get_ma513);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?

    if [ "${TBL:-cap}" = "cap" ] ; then
        fn_cp_tbl tbl_ma513 ${tbl_ma_date}
        xt_ret $? "fn_cp_tbl" || return $?

        # tag a tag, touch file the fisttime after $sec_1500
        sec_1500=$(date +%s -d "15:00:00")
        sec_curr=$(date +%s)
        # ! must append with a whitespace
        if ! ([ "${END}" = "${CURR}" ] && [ "${sec_curr}" -lt "${sec_1500}" ]); then
            mkdir -p /tmp/mx/
            touch /tmp/mx/${tbl_ma_date}
        fi
    fi
}

function fn_ma_ray()
{
    echo "build ${END}..."
    fn_reset_sqlsource
    fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    mysql -N kts<<<"SELECT code FROM tbl_ma513 WHERE
                    ma5>ma13 and ma13>ma34 ${COND}" | \
        xargs -n4 | tee /dev/stderr | xargs up file_to_table
    return
}

function fn_select_tbl_ma513()
{
    local sqls="(SELECT * FROM day WHERE date='${END}') as d"
    local conds="m.code=d.code and ${COND1} ${COND}"

    echo "
    SELECT m.code FROM tbl_ma513 as m, ${sqls} WHERE ${conds}
    " | tee /dev/stderr | mysql -N kts > ${soptter_zxg}
    xt_ret $? "${FUNCNAME}" || return $?

    cat ${soptter_zxg} | xargs -n6 | tee /dev/stderr | TBL=zxg_ma513 xargs up file_to_table
    xt_ret $? "cat ${soptter_zxg}" || return $?

    [ "${CHAO:=0}" -eq 0 ] && echo "----- CHAO:${CHAO} -----" && return

    echo "
    # cascading CHAO!
    SELECT code FROM zxg_ma513 WHERE code in (SELECT code FROM chao)
    " | tee /dev/stderr | mysql -N kts | tee .soptter.chao | \
        xargs -n6 | tee /dev/stderr | TBL=zxg_chao513 xargs up file_to_table
}

function fn_trd_cross_maX()
{
    echo "build ${PREV}..."
    fn_reset_sqlsource
    END=${PREV} fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    fn_create_tbl_codes tbl_fr_ma_where_cond0
    xt_ret $? "create tbl error" || return $?

    COND0="${COND0}" fn_insert_codes_2_table tbl_fr_ma_where_cond0
    xt_ret $? "insert codes table" || return $?

    echo "build ${END}..."
    fn_reset_sqlsource
    TBL=tbl_fr_ma_where_cond0 fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    fn_select_tbl_ma513
    xt_ret $? "" || return $?
}

function fn_hop_cross_maX()
{
    fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    fn_select_tbl_ma513
    xt_ret $? "" || return $?
}

function fn_hop_cross_ma5()
{
    # ma5<ma13 --> 2次上穿ma5
    # COND1="ma5<ma13 and d.yesc>ma5 and d.low<ma5 and d.close>ma5" fn_hop_cross_maX
    # xt_ret $? "xx" || return $?
    iEND=`STEP=1 fn_get_prev`
    iPREV=`STEP=${STEP} END=${iEND} fn_get_prev`

    PREV=${iPREV} END=${iEND} fn_trd_cross_ma5
    xt_ret $? "${FUNCNAME}" || return $?

    fn_cp_tbl zxg tbl_cross_ma5

    TBL=tbl_cross_ma5 COND1="ma5<ma13 and d.low<ma5 and d.close>ma5" fn_hop_cross_maX

    xt_ret $? "${FUNCNAME}" || return $?

    echo "    2次上穿ma5分析over..."
}

function fn_trd_cross_ma5()
{
    COND0="close<ma5 and ma5<ma13" COND1="m.close>ma5" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}

function fn_trd_cross_ma13()
{
    COND0="close<ma13" COND1="m.close>ma13" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}

function fn_trd_cross_5_13()
{
    COND0="close<ma5 and close<ma13" COND1="m.close>ma5 and m.close>ma13" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}


function fn_ma5_cross_ma13()
{
    COND0="ma5<ma13" COND1="ma5>ma13" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}

function fn_hii_cross_ma5()
{
    COND0="close<ma5" COND1="d.high>ma5 and m.close<ma5" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}

function fn_trd_rally_ma5() 
{
    read -p "
    make sure you have done below points:
    ./SCREENER ana_chao
    type any key to continue."

    echo "build ${PREV}..."
    fn_reset_sqlsource
    END=${PREV} fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    # 昨未穿ma5，今上涨，今放大上涨上穿ma5
    SCALE=1.3
    COND1="m.close<m.ma5 and d.close>d.yesc"
    COND1="${COND1} and (d.close+(d.close-d.yesc)*${SCALE})>m.ma5"
    fn_select_tbl_ma513
    xt_ret $? "" || return $?

}

function fn_ana_ma513()
{
    # 可以配合分时线及上涨进行预测
    # 采用双表联合查询来解决分析的困境
    # ana 的关键在于 cross & 收敛 & 放量上行

    # 更成熟的分类时，END在命令行环境变量中指定
    END=${2:-${END}}

    sqls="SELECT date FROM day WHERE code=900001 and date='$END'"
    if ! mysql -N kts<<<"${sqls}" | grep -q ${END}; then
        echo "Error: ${END} is not a open day!!!" && exit 1
    fi
    sqls="SELECT date FROM day WHERE code=900001 and date<='$END'"

    # --------- 做分支 ---------------
    cmdlist=(
    "ma_ray             # ma5 > ma13 > ma34"
    "trd_rally_ma5      #       上穿 ma5 predicting"
    "trd_cross_ma5      # close 上穿 ma5"
    "trd_cross_ma13     # close 上穿 ma13"
    "trd_cross_5_13     # close 上穿 ma5 and ma13"
    "hop_cross_ma5      # trd re上穿 ma5, STEP设置天数"
    "ma5_cross_ma13     # ma5   上穿 ma13"
    "hii_cross_ma5      # high  上穿 ma5, !close"
    )
    fn_execute "$@" || return $?
}

function fn_ana_chao()
{
    #
    # 从`SCREENER 1`得到超跌股票，并写入表zxg。
    # 再通过ma5进行过滤。
    #
    function fn_exe_usage()
    {
    echo "
    Usage:
    1. SCREENER 1 backward_14th_day #{PREV} # 得到超跌数据tbl_sink
    2. .c                                   # 全能TBL=chao
    3. SELECT   1                           # SELECT => TBL=chao xargs up 6

    4. SCREENER 3 1                         # 上涨预测
    " | sed 's/^  //g'
    }

    fn_exe_usage
}

function fn_ana_ma240()
{
    fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    # 条件进行分类
    # 且不要长得太多，已经过去的，要抓住现在

    local sqls="SELECT s.code FROM tbl_ma513 as s, tbl_ma240 as l"
    local conds=(                                           # 2014-04-14
        's.code=l.code and'                                 # 关联code
        '(l.high-l.low)/l.low<.23 and'                      # 年振幅45%，参照佛山照明、福建水泥
        's.ma5>s.ma13 and (s.close-s.ma13)/s.ma13<.05 and'  # 345中线：ma5上穿ma13
        '(s.close-l.low)/l.low<.05 and'                     # 345中线：ma5上穿ma13
       #'s.ma13>l.ma34 and (s.ma13-l.ma34)/l.ma34<.05 and'  # 345长线：ma13上穿ma34
        's.close>3'                                         # 价格无关，上海莱士，福建水泥
    )
        # abs(ma34-ma60)/ma34<.05 and abs(ma120-ma240)/ma120<.03

    mysql -N kts<<<"${sqls} WHERE ${conds[@]}" |
                xargs -n6 | tee /dev/stderr | xargs up file_to_table
    xt_ret $? "${FUNCNAME}" || return $?

    return 0
}

function fn_c144()
{
    fn_iscode $1 
    xt_ret $? "" || { echo "Usage: 144 code... {END}" && exit; }

    codes=(`xargs -n1 <<<"${*}" | sed 's/^0*//g' | xargs printf "%06d "`)

    up file_to_table ${codes[@]}
    END=${END} TBL=zxg up up_tbl_ma144_all

    sqls="SELECT t.code,t.date,t.close,ma144,100*(t.close-ma144)/ma144 as rise, c.name "
    sqls="${sqls} FROM tbl_ma144 as t, cap as c, zxg  WHERE t.code = c.code and t.code = zxg.code"
    sqls="${sqls} ${HAVING} ORDER by ${ASC:-zxg.id}"
    mysql -t kts<<<"${sqls}"
    xt_ret $? "${FUNCNAME}" || return $?

    return 0
}

function fn_ana_ma144()
{
    # 上海莱士，福建水泥
    # 若开涨了，预估起点与终点 
    #
    # 1. 

    local sqls="SELECT code FROM tbl_ma144 as m"
    local conds=(
        "m.close > ma13 and ma13>ma34*0.99 and "
        "m.width < .2 and "                       # 窄幅振荡
        "m.close > ma144*.9 and "                 # close接近ma144
        "m.close < ma144*${RISED:-1.10}"          # +10%涨幅内
    )

    local codes=(`mysql -N kts<<<"${sqls} WHERE ${conds[@]}"`)
    xt_ret $? "${FUNCNAME}" || return $?

    up file_to_table ${codes[@]}
    xt_ret $? "${FUNCNAME}" || return $?

    codes=${codes[@]}
    sqls="SELECT code,width FROM tbl_ma144 WHERE code in (${codes// /,}) ORDER by width ASC"
    mysql -N kts<<<"${sqls}" | xargs -n8
    xt_ret $? "${FUNCNAME}" || return $?

    return 0
}


function fn_focus()
{
    local file=${YIST:-'.soptter.focus'}

    test -f ${file}
    xt_ret $? "${file} not exist" || return $?

    up file_to_table ${file}
    TBL=zxg fn_dugu9jian ${END} ${2:-wchng}

    return $?
}


function fn_auto_nmemb()
{
    [ -z "${NMC_RATIO}" ] && return
    nrat=`mysql -N<<<"SELECT round(100*${NMC_RATIO}, 0)"`

    if [ "${nrat}" -le 30 ]; then
        let nmemb0=150/${nrat}
    else
        fn_echo_fail "
        ERROR: NMC_RATIO[${NMC_RATIO}] must less than .20
        "
        exit
    fi

    nmemb=${nmemb:-${nmemb0}}
    #echo ${nmemb}; exit
    return $?
}

function fn_fbi()
{
    # 最大日换手为20%，以1%为粒度，可以得出`10min`是一个很好的单位，得日数据25单位
    # 若是日换手为4%，以nmemb=7=30/4   <-- 30 即1日数据组（有效取28）
    # 取mi5的NUM=20，即便是歌尔日换手1.5%，亦可得到10组diff数据
    # NMC_RATIO即tov5
    # nmemb = 1%换手公差时之数据组数 = 30/最大日换手 = 30/(tov5/5) = 150/tov5
    # ZIZE取20，太远时，日成交翻番后，往前的数据会不准确
    # 工作条件: volume >= ZIZE+(2*NMC_RATIO)，否则会报 so_little_data，
    fn_auto_nmemb
    NMC_RATIO=${NMC_RATIO:-.2}
    nmemb=${nmemb:-7}
    ZIZE=${ZIZE:-20}

    fn_iscode ${code:=$1}
    xt_ret $? "invalid code[$1]" || return $?

    sql="SELECT max(datetime) FROM fenbi WHERE code=${1}"
    dt=`mysql -N kts <<< "${sql}"`

    # 20140707.14{o|h}  
    DT=${DT/./}
    DT=${DT/o/0000}     # o(o'clock)
    DT=${DT/h/3000}     # h(half-clock)
    DT=${DT:-$dt}
    fn_isdatetime ${DT} 
    xt_ret $? "invalid datetime[$DT]" || return $?

    TBL=tbl_fbi1 fn_flush_code ${code}

    local sql="SELECT datetime from fenbi WHERE code=${code} and datetime<=${DT}"
    dates=(`mysql -N kts <<< "${sql} ORDER by datetime DESC" | 
                awk -v nmemb=${nmemb} '{if (! (a++%nmemb) ) print $1}'`)
    test ${#dates[@]} -ne 0
    xt_ret "${PIPESTATUS[0]}" || return $?

    local size=${#dates[@]}
    let   idx=${size}-1
    local iNUM=${NUM:-900}          # 30/day

    echo "
    size: ${size} nmemb: ${nmemb} iNUM:${iNUM} (hour=nmemb[6])
    going to list ${ZIZE} recodrs ${dates[$idx]} ~ ${dates[0]} ...
    "

    mysql kts <<<"truncate TABLE tbl_fbi5; truncate TABLE tbl_fdiff;"
    xt_ret $? "Don't worry, this error show when run 1st time"
    fn_clr_exitcode
    xt_ret $? "clr exitcode" || return $?

    local i=0
    for (( i=0; i<${ZIZE}; i+=1 )); do
        TBL=tbl_fbi1 NUM=${iNUM} fn_fbi_ratio ${dates[$i]}
        xt_ret ${?} "" || return $?

        if ! fn_sql_exitsucc; then
            tovf=`echo "
            SELECT round(sum(volume)/cap.shares, 2) as tov FROM fenbi,cap 
            WHERE fenbi.code=${code} and fenbi.code=cap.code
            " | mysql kts -N`

            fn_echo_warn "    so_little_data[$i ${dates[$i]}], tov[${tovf}], try: mi5 ${code}\n"
            local RETCODE=1
            break
        fi
    done

    col='code,datetime_p,datetime_c,off_p,off_c,tnov_p,tnov_c'
    col="${col},avrg_p,avrg_c,ratio,wchng"
    colA="A.${col//,/,A.}"
    echo "
    INSERT INTO tbl_fdiff(${col},cdiff,rdiff,dbrat)
    SELECT ${colA}, (A.avrg_c-B.avrg_c) as cdiff, (A.ratio-B.ratio) as rdiff,
                    100*(2*A.close-(A.avrg_p+A.avrg_c))/(A.avrg_p+A.avrg_c) as dbrat FROM tbl_fbi5 A 
    INNER JOIN tbl_fbi5 B on(A.id<B.id) GROUP BY A.id;
    " | mysql -N kts
    xt_ret $? "" || return $?

    [ "${RETCODE:-0}" -eq 0 ] && SELECT fbi
    return ${RETCODE:-0}
}


function fn_acc()
{
    fn_iscode ${code:=$1}
    xt_ret $? "invalid code[$1]" || return $?

    cp ${mps_acc} ${mps_god}

    echo "
    SET @END='${END}';
    SET @NUM=${NUM:-500};
    SET @PARTS=${PARTS:-20};
    SET @PPLUS=${PPLUS:-5};
    SET @NMC_RATIO=${NMC_RATIO:-1};
    call sp_visit_code(${code});
    " >> $mps_god # | tee -a $mps_god
    fn_clr_exitcode
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?
    if ! fn_sql_exitsucc; then
        fn_echo_warn "so_little_data"
        exit
    fi

    SELECT acc
}

function fn_acf()
{
    fn_iscode ${code:=$1}
    xt_ret $? "invalid code[$1]" || return $?

    cp ${mps_acf} ${mps_god}

    sql="SELECT max(datetime) FROM fenbi WHERE code=${1}"
    dt=`mysql -N kts <<< "${sql}"`

    # 20140707.14{o|h}  
    DT=${DT/./}
    DT=${DT/o/0000}     # o(o'clock)
    DT=${DT/h/3000}     # h(half-clock)
    DT=${DT:-$dt}
    fn_isdatetime ${DT} 
    xt_ret $? "invalid datetime[$DT]" || return $?

    echo "
    SET @DT='${DT}';
    SET @PARTS=${PARTS:-20};
    SET @PPLUS=${PPLUS:-5};
    SET @NMC_RATIO=${NMC_RATIO:-.20};
    call sp_visit_code(${code});
    " >> $mps_god # | tee -a $mps_god
    fn_clr_exitcode
    mysql $mo kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?
    if ! fn_sql_exitsucc; then
        fn_echo_warn "so_little_data"
        exit
    fi

    SELECT acf
}

function fn_main()
{
    CURR=`fn_maxdate`
    END=${END:-${CURR}}
    PREV=`fn_get_prev`

    fn_isdate ${END} 
    xt_ret $? "invalid END[$2]" || return $?
    # SCREENER的宗旨，弃子取势
    # xet_block_info 为 sp_visit_tbl() 选定相应的BLOCK
    cmdlist=(
    "dugu9jian            [end [field]]         # NUM=61 .NMC end.close analyze"
    "6maishenjian         [end [field]]         # NUM=61 min(close) sort by #{COL}"
    "9jian                code [end [field]]    # #{NUM}日，个股成本分析"
    "6jian                code [end [field]]    # #{NUM}日，个股成本分析"
    "c144                 code...               # cost:ma144 & sort by #{ASC:id}"
    "focus                [field]               # #{YIST:-.soptter.focus}->zxg and 9jian"
    "tao                  code [end [field]]    # #{nmemb}"
    "tao5                 code [end]            # #{nmemb} #{ZIZE}"
    "bei                  {code...|file}        # #{nmemb} #{ZIZE}"
    "fbi                  {code...|file}        # #{nmemb} #{ZIZE} DT=20140707.14{o|h}"
    "acc                  {code...|file}        # Acceleration"
    "acf                  {code...|file}        # Acceleration of fb"
    "get_ma513                                  # /tmp/mx/"
    "ana_ma513            index [end]           # 分析ma 5 13 34 55"
    "ana_ma240                                  # 分析ma 34 60 120 240"
    "ana_ma144                                  # 分析ma144"
    "ana_chao                                   # 分析超跌反弹"
    )

    # 存储过程函数文件的最后5行都是注释
    cd $workdir
    head -n -5 $mps_org > $mps_god

    # 为提高效率，可能使用临时表，必要请备份相应文件 call sp_cp_tbl('fr', 'to');
    fn_execute "$@" || return $?
}

fn_main "$@"
# fn_main 4
