#! /bin/bash
#---------------------------------------------------------------------------
#          FILE: SCREENER.sh
#         USAGE: ./SCREENER.sh
#   DESCRIPTION:
#        AUTHOR: chuangxiaomoo (God helps those who help themselves)
#  ORGANIZATION:
#       CREATED: 2013-12-11 08:46:51 AM
#      REVISION: 1.0
#---------------------------------------------------------------------------

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_get_block_info()
{
    # 显示当前选中，及可选BLOCK列表
    # "show create table test;" | grep 'COMMENT='

    return 1
}

function fn_set_block_info()
{
    # 从列表中选择BLOCK
    # "alter table 表名 comment '注释';"

    return 1
}

function fn_get_13d_20psink()
{
    cat <<-"HERE"
    4日内从历史最高点回落时选择，
    前期上升速度必须快，8日涨幅30%，13日涨幅在40%以上。
    如观察日2013-12-12，
    失败案例：
    新宁物流(300013) 由于是从最高点的第2波下降，必也以“疲惫”

    成功案例：
    北京君正(300223) 13日涨幅 83% = (33-18)/18
    潜能恒信(300191) 13日涨幅 73% = (33-19)/19

    如此，可选
    奥普光电 002338
    麦捷科技 300319
    奋达科技 002681


    此类波动频繁之属，做好波段操作，特别是大盘行情不好的日子。大着眼，小着手。
	HERE

    echo "
    call sp_visit_tbl('cap', 2);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?
}

# 大写变量作为全局，小写作为内部
function fn_get_1_swing_num()
{
    percent=${1:-8}
    if [ "${percent%.*}" -lt 0 ] ; then
        swing_cmd="HAVING rise < $percent"
    else
        swing_cmd="HAVING rise > $percent"
    fi
    echo "
    DELETE from tbl_visit;
    INSERT INTO tbl_visit(code,sink)
    SELECT code,100*(close-yesc)/yesc as rise FROM day
        WHERE date='$END' $swing_cmd ORDER by rise ${ASC:-DESC};
    " | mysql $mo kts
    fn_cp_tbl tbl_visit pipe
    ./up add_tbl_visit_2_zixuangu   # 添加到ZXG，可根据需要再进行排序
    ./SELECT app_nmc_name               # 追加表名打印
    # no need source
    exit
}

function fn_sort_amount()
{
    # 可扩展 'tbl_visit' 的表定义
    # where d.code = c.code 非常重要
    # as 语句可在 FROM 子句中
    echo "
    DELETE from tbl_visit;
    INSERT INTO tbl_visit(code,sink,amount,turnover)
    SELECT d.code, $RISE as rise,
        amount, $TURNOV as turnover FROM day as d, cap as c
        WHERE d.code = c.code and d.date='$END'
        ${COND} ORDER by amount ${ASC:-DESC} limit ${LIMIT:-48};
	" | mysql -t kts
    fn_cp_tbl tbl_visit pipe
    ./up add_tbl_visit_2_zixuangu       # 添加到ZXG，可根据需要再进行排序
    ./SELECT app_nmc_name amount        # 追加表名打印
}


function fn_sort_turnover()
{
    echo "
    DELETE from tbl_visit;
    INSERT INTO tbl_visit(code,sink,amount,turnover)
    SELECT d.code, $RISE as rise,
        amount, $TURNOV as turnover FROM day as d, cap as c
        WHERE d.code = c.code and d.date='$END'
        ${COND} ORDER by turnover ${ASC:-DESC} limit ${LIMIT:-48};
	" | mysql -t kts
    fn_cp_tbl tbl_visit pipe
    ./up add_tbl_visit_2_zixuangu       # 添加到ZXG，可根据需要再进行排序
    ./SELECT app_nmc_name turnover      # 追加表名打印

}

function fn_get_n_swing_num()
{
    echo "
    这些类股都是振荡股，莫作留恋。
    "
    [ "$#" -eq 1 ] && echo "Usage: 要么不带参数，要么两个参数" && exit
    tailrise=8
    daynum=${1:-2}
    fullrise=${2:-17}

    # SELECT * FROM day WHERE date=$END and (close-yesc)/yesc > 0.08;
    # date=''需要单引号
    echo "
    DROP TABLE IF EXISTS codes;
    CREATE TABLE codes (
        id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0
    );
    INSERT INTO codes(code)
    SELECT code FROM day WHERE date='$END' and 100*(close-yesc)/yesc > $tailrise;
    " | mysql $mo kts

    if [ "$fullrise" -lt 0 ] ; then
        intbl=cap
    else
        intbl=codes
    fi

    echo "
    SET @argv_change = $fullrise;
    SET @argv_n = $daynum;
    call sp_visit_tbl('$intbl', @fn_flt_n_day_change);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?
}


function fn_get_stat_turnov()
{
    local usage="Usage: ${FUNCNAME[0]} code start [end]"
    fn_is_digit $1
    xt_ret $? "$usage" || return $?

    [ -n "${START:=${2}}" ]
    xt_ret $? "$usage" || return $?

    END=${3:-${END}}

    echo "
    SET @START='$START';
    SET @END='$END';
    SET @NUM=`mysql -N kts<<<"SELECT count(*) FROM day WHERE code=900001 and date>='$START' and date<='$END'"`
    call sp_stat_turnov('$1');
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?
}

function fn_get_down_turnov()
{
    START=${1:-${START}}
    END=${2:-${END}}

    [ -z "${START}" ] && START=`./SELECT get_open_days | head -1`

    echo "
    From ${START} to ${END}...
    "

    # 指定环境变量TBL来进行测试
    TBL=${TBL:-'cap'}

    # 注意更新表 $TBL
    echo "
    To visit `mysql -N kts<<<"SELECT count(*) FROM ${TBL}"` codes on table $TBL...
    "

    echo "
    SET @DOWNSLOPE='${DOWNSLOPE:-1}';
    SET @START='$START';
    SET @END='$END';
    SET @NUM=`mysql -N kts<<<"SELECT count(*) FROM day WHERE code=900001 and date>='$START' and date<='$END'"`;
    call sp_visit_tbl('$TBL', @fn_get_down_turnov);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?

    echo '
    提示1: 考虑双日顶，high日绿，边界前移一日，`300301 2014-01-22`构筑3日顶.
    提示2: 最高价日为红，则70%计入下跌换手; 为绿，全为下跌换手
    提示3: ------------------------- 操作要合ma5 -------------------------
    '
}

function fn_dugu9jian()
{
    if [ "${TBL}" = windbell_codes ] && [ "`cat ${filewb}`" != ${CURR} ]; then
        echo "windbell_codes is out of day. continue to run [./up 22]"
        exit
    fi

    END=${1:-${END}}
    TBL=${TBL:-'cap'}
    NUM=${NUM:-81}        # 34太小，300104 2014-07-17 被漏掉了

    fn_isdate ${END} 
    xt_ret $? "    Usage: #{1} must be date like 2008-08-08" || return $?

    echo "
    To visit `mysql -N kts<<<"SELECT count(*) FROM ${TBL}"` codes on table $TBL...
    "

    echo "
    SET @END='$END';
    SET @NUM=${NUM};
    SET @NMC_RATIO=${NMC_RATIO:-1};
    call sp_visit_tbl('$TBL', @fn_dugu9jian);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?

    [ "${inwind}" = 1 ] || SELECT dugu9jian ${2:-wchng}
}

function fn_6maishenjian()
{
    END=${1:-${END}}
    TBL=${TBL:-'cap'}
    NUM=${NUM:-61}

    fn_isdate ${END} 
    xt_ret $? "    Usage: #{1} must be date like 2008-08-08" || return $?

    echo "
    To visit `mysql -N kts<<<"SELECT count(*) FROM ${TBL}"` codes on table $TBL...
    "

    echo "
    SET @END='$END';
    SET @NUM=${NUM};
    call sp_visit_tbl('$TBL', @fn_6maishenjian);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?

    SELECT 6maishenjian ${2:-down}
}

function fn_taox_ratio()
{
    END=${1:-${END}}
    TBL=${TBL:-'cap'}
    NUM=${NUM:-240}        # 需要200%，所以应该比较大

    fn_isdate ${END} 
    xt_ret $? "    Usage: #{1} must be date like 2008-08-08" || return $?

    echo "
    To visit `mysql -N kts<<<"SELECT count(*) FROM ${TBL}"` codes on table $TBL...
    "

    echo "
    SET @END='$END';
    SET @NUM=${NUM};
    SET @FORCE=${FORCE:-0};
    SET @NMC_RATIO=${NMC_RATIO:-1};
    call sp_visit_tbl('$TBL', @fn_taox_ratio);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?

    SELECT taox_ratio ${2:-ratio}
}

function fn_9jian()
{
    test -n "${1}" && fn_iscode ${1}       
    xt_ret $? "invalid code[$1]" || return $?
    fn_isdate ${2:-$END} 
    xt_ret $? "invalid date[$2]" || return $?

    local code=`sed 's/^0*//g' <<< $1 | xargs printf "%06d"`
    TBL=tbl_cost9 up add_codes_2_dzh2tbl ${code}
    TBL=tbl_cost9 NUM=${NUM:-240} fn_dugu9jian ${2:-$END} ${3:-wchng}
}

function fn_6jian()
{
    test -n "${1}" && fn_iscode ${1}       
    xt_ret $? "invalid code[$1]" || return $?
    fn_isdate ${2:-$END} 
    xt_ret $? "invalid date[$2]" || return $?

    local code=`sed 's/^0*//g' <<< $1 | xargs printf "%06d"`
    TBL=tbl_cost6 up add_codes_2_dzh2tbl ${code}
    TBL=tbl_cost6 NUM=${NUM:-240} fn_6maishenjian ${2:-$END} ${3:-wchng}
}

function fn_tao()
{
    test -n "${1}" && fn_iscode ${1}       
    xt_ret $? "invalid code[$1]" || return $?
    fn_isdate ${2:-$END} 
    xt_ret $? "invalid date[$2]" || return $?

    local code=`sed 's/^0*//g' <<< $1 | xargs printf "%06d"`
    TBL=tbl_tao1 up add_codes_2_dzh2tbl ${code}

    TBL=tbl_tao1 NUM=${NUM:-240} fn_taox_ratio ${2:-$END} ${3:-ratio}
}

function fn_tao5()
{
    test -n "${1}" && fn_iscode ${1}       
    xt_ret $? "invalid code[$1]" || return $?
    END=${2:-$END}
    fn_isdate ${END} 
    xt_ret $? "invalid date[$2]" || return $?

    local code=`sed 's/^0*//g' <<< $1 | xargs printf "%06d"`
    TBL=tbl_tao1 up add_codes_2_dzh2tbl ${code}

    # count off
    offset=`mo=-B NMC_RATIO=1.5 fn_9jian ${code} ${END} | awk /${code}/'{print $4}'`
    offset=${offset:-100}

    if [ "${offset}" -lt 15 ] ; then        # turnover 10%   5%单位为一组
        grp=1
    elif [ "${offset}" -lt 30 ] ; then      # turnover 5%
        grp=2
    elif [ "${offset}" -lt 60 ] ; then      # turnover 2.5%
        grp=4
    elif [ "${offset}" -lt 100 ] ; then     # turnover 1.5%
        grp=7
    else                                    # turnover < 1.5%
        grp=5
    fi

    #   grp=5                               # 强制 grp 以查看更广的ratio变化
    let iLIMIT=offset*${grp}*4              # 默认 2时为300%，调整以查看更多

    local sql="SELECT date from day WHERE code = ${code} and date<='${END}'"
    dates=(`mysql -N kts <<< "${sql} ORDER by date DESC limit ${iLIMIT:-240}" | \
            xargs -n${grp} | awk '{print $1}'`)

    local len=${#dates[@]}
    local idx=`expr ${len} - 1`
    echo "    
    off: ${offset} grp: ${grp}
    going to list ${len} recodrs ${dates[$idx]} ~ ${dates[0]} ..."

    local i=0
    local iNUM=${NUM:-240}
    TBL=tbl_tao1 NUM=${iNUM} fn_taox_ratio ${dates[$i]}
    xt_ret $? "" || return $?

    for (( i=1; i<${len}; i+=1 )); do
        FORCE=1 TBL=tbl_tao1 NUM=${iNUM} fn_taox_ratio ${dates[$i]} | \
            grep ${code} | tee -a /dev/stderr | grep -q "so_little_taox_data"
        [ "${?}" -eq 0 ] && { echo so_little_taox_data@${dates[$i]}; return ;}
    done
}


function fn_get_rise_turnov()
{
    DOWNSLOPE=0
    fn_get_down_turnov $@
}

function fn_insert_codes_2_table()
{
    [ -z "${1}" ] && echo "Usage: insert tbl_name" && exit 1
    echo "
    INSERT INTO ${1}(code) SELECT code FROM ${tbl_ma_date} WHERE ${COND0};
    " | mysql kts
}

function fn_get_ma513()
{
    END=${1:-${END}}
    tbl_ma_date=tbl_mx_${END//-/_}

    if mysql kts<<<"SHOW TABLES" | grep -q ${tbl_ma_date}; then
        # 表 ${tbl_ma_date} 存在，且是闭市后构建
        # 表 tbl_ma513 是TBL的分析结果，供后续处理分析。
        if [ -f /tmp/mx/${tbl_ma_date} ]; then
            if [ "cap" = "${TBL:-cap}" ]; then
                fn_cp_tbl ${tbl_ma_date} tbl_ma513;
            else
                echo "
                DELETE from tbl_ma513;
                INSERT INTO tbl_ma513 SELECT * FROM ${tbl_ma_date}
                            WHERE code in (SELECT code FROM ${TBL});
                " | mysql kts # | tee /dev/stderr
                echo
            fi
            return 0
        fi
    fi

    echo "    build on ${TBL:-cap}..."

    echo "
    SET @END='$END';
    call sp_visit_tbl('${TBL:-cap}', @fn_get_ma513);
    " | tee -a $mps_god
    mysql $mo -t kts <<< "source $mps_god"
    xt_ret $? "${FUNCNAME}" || return $?

    if [ "${TBL:-cap}" = "cap" ] ; then
        fn_cp_tbl tbl_ma513 ${tbl_ma_date}
        xt_ret $? "fn_cp_tbl" || return $?

        # tag a tag, touch file the fisttime after $sec_1500
        sec_1500=$(date +%s -d "15:00:00")
        sec_curr=$(date +%s)
        # ! must append with a whitespace
        if ! ([ "${END}" = "${CURR}" ] && [ "${sec_curr}" -lt "${sec_1500}" ]); then
            mkdir -p /tmp/mx/
            touch /tmp/mx/${tbl_ma_date}
        fi
    fi
}

function fn_ma_ray()
{
    echo "build ${END}..."
    fn_reset_sqlsource
    fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    mysql -N kts<<<"SELECT code FROM tbl_ma513 WHERE
                    ma5>ma13 and ma13>ma34 ${COND}" | \
        xargs -n4 | tee /dev/stderr | xargs up add_codes_2_dzh2tbl
    return
}

function fn_select_tbl_ma513()
{
    local sqls="(SELECT * FROM day WHERE date='${END}') as d"
    local conds="m.code=d.code and ${COND1} ${COND}"

    echo "
    SELECT m.code FROM tbl_ma513 as m, ${sqls} WHERE ${conds}
    " | tee /dev/stderr | mysql -N kts > ${soptter_zxg}
    xt_ret $? "${FUNCNAME}" || return $?

    cat ${soptter_zxg} | xargs -n6 | tee /dev/stderr | TBL=zxg_ma513 xargs up add_codes_2_dzh2tbl
    xt_ret $? "cat ${soptter_zxg}" || return $?

    [ "${CHAO:=0}" -eq 0 ] && echo "----- CHAO:${CHAO} -----" && return

    echo "
    # cascading CHAO!
    SELECT code FROM zxg_ma513 WHERE code in (SELECT code FROM chao)
    " | tee /dev/stderr | mysql -N kts | tee .soptter.chao | \
        xargs -n6 | tee /dev/stderr | TBL=zxg_chao513 xargs up add_codes_2_dzh2tbl
}

function fn_trd_cross_maX()
{
    echo "build ${PREV}..."
    fn_reset_sqlsource
    END=${PREV} fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    fn_create_tbl_codes tbl_fr_ma_where_cond0
    xt_ret $? "create tbl error" || return $?

    COND0="${COND0}" fn_insert_codes_2_table tbl_fr_ma_where_cond0
    xt_ret $? "insert codes table" || return $?

    echo "build ${END}..."
    fn_reset_sqlsource
    TBL=tbl_fr_ma_where_cond0 fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    fn_select_tbl_ma513
    xt_ret $? "" || return $?
}

function fn_hop_cross_maX()
{
    fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    fn_select_tbl_ma513
    xt_ret $? "" || return $?
}

function fn_hop_cross_ma5()
{
    # ma5<ma13 --> 2次上穿ma5
    # COND1="ma5<ma13 and d.yesc>ma5 and d.low<ma5 and d.close>ma5" fn_hop_cross_maX
    # xt_ret $? "xx" || return $?
    iEND=`STEP=1 fn_get_prev`
    iPREV=`STEP=${STEP} END=${iEND} fn_get_prev`

    PREV=${iPREV} END=${iEND} fn_trd_cross_ma5
    xt_ret $? "${FUNCNAME}" || return $?

    fn_cp_tbl zxg tbl_cross_ma5

    TBL=tbl_cross_ma5 COND1="ma5<ma13 and d.low<ma5 and d.close>ma5" fn_hop_cross_maX

    xt_ret $? "${FUNCNAME}" || return $?

    echo "    2次上穿ma5分析over..."
}

function fn_trd_cross_ma5()
{
    COND0="close<ma5 and ma5<ma13" COND1="m.close>ma5" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}

function fn_trd_cross_ma13()
{
    COND0="close<ma13" COND1="m.close>ma13" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}

function fn_trd_cross_5_13()
{
    COND0="close<ma5 and close<ma13" COND1="m.close>ma5 and m.close>ma13" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}


function fn_ma5_cross_ma13()
{
    COND0="ma5<ma13" COND1="ma5>ma13" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}

function fn_hii_cross_ma5()
{
    COND0="close<ma5" COND1="d.high>ma5 and m.close<ma5" fn_trd_cross_maX
    xt_ret $? "xx" || return $?
}

function fn_trd_rally_ma5() 
{
    read -p "
    make sure you have done below points:
    ./SCREENER ana_chao
    type any key to continue."

    echo "build ${PREV}..."
    fn_reset_sqlsource
    END=${PREV} fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    # 昨未穿ma5，今上涨，今放大上涨上穿ma5
    SCALE=1.3
    COND1="m.close<m.ma5 and d.close>d.yesc"
    COND1="${COND1} and (d.close+(d.close-d.yesc)*${SCALE})>m.ma5"
    fn_select_tbl_ma513
    xt_ret $? "" || return $?

}

function fn_ana_ma513()
{
    # 可以配合分时线及上涨进行预测
    # 采用双表联合查询来解决分析的困境
    # ana 的关键在于 cross & 收敛 & 放量上行

    # 更成熟的分类时，END在命令行环境变量中指定
    END=${2:-${END}}

    sqls="SELECT date FROM day WHERE code=900001 and date='$END'"
    if ! mysql -N kts<<<"${sqls}" | grep -q ${END}; then
        echo "Error: ${END} is not a open day!!!" && exit 1
    fi
    sqls="SELECT date FROM day WHERE code=900001 and date<='$END'"

    # --------- 做分支 ---------------
    cmdlist=(
    "ma_ray             # ma5 > ma13 > ma34"
    "trd_rally_ma5      #       上穿 ma5 predicting"
    "trd_cross_ma5      # close 上穿 ma5"
    "trd_cross_ma13     # close 上穿 ma13"
    "trd_cross_5_13     # close 上穿 ma5 and ma13"
    "hop_cross_ma5      # trd re上穿 ma5, STEP设置天数"
    "ma5_cross_ma13     # ma5   上穿 ma13"
    "hii_cross_ma5      # high  上穿 ma5, !close"
    )
    fn_execute "$@" || return $?
}

function fn_ana_chao()
{
    #
    # 从`SCREENER 1`得到超跌股票，并写入表zxg。
    # 再通过ma5进行过滤。
    #
    function fn_exe_usage()
    {
    echo "
    Usage:
    1. SCREENER 1 backward_14th_day #{PREV} # 得到超跌数据tbl_sink
    2. .c                                   # 全能TBL=chao
    3. SELECT   1                           # SELECT => TBL=chao xargs up 7

    4. SCREENER 3 1                         # 上涨预测
    " | sed 's/^  //g'
    }

    fn_exe_usage
}

function fn_ana_ma240()
{
    fn_get_ma513
    xt_ret $? "${FUNCNAME}" || return $?

    # 条件进行分类
    # 且不要长得太多，已经过去的，要抓住现在

    local sqls="SELECT s.code FROM tbl_ma513 as s, tbl_ma240 as l"
    local conds=(                                           # 2014-04-14
        's.code=l.code and'                                 # 关联code
        '(l.high-l.low)/l.low<.23 and'                      # 年振幅45%，参照佛山照明、福建水泥
        's.ma5>s.ma13 and (s.close-s.ma13)/s.ma13<.05 and'  # 345中线：ma5上穿ma13
        '(s.close-l.low)/l.low<.05 and'                     # 345中线：ma5上穿ma13
       #'s.ma13>l.ma34 and (s.ma13-l.ma34)/l.ma34<.05 and'  # 345长线：ma13上穿ma34
        's.close>3'                                         # 价格无关，上海莱士，福建水泥
    )
        # abs(ma34-ma60)/ma34<.05 and abs(ma120-ma240)/ma120<.03

    mysql -N kts<<<"${sqls} WHERE ${conds[@]}" |
                xargs -n6 | tee /dev/stderr | xargs up add_codes_2_dzh2tbl
    xt_ret $? "${FUNCNAME}" || return $?

    return 0
}

function fn_c144()
{
    fn_iscode $1 
    xt_ret $? "" || { echo "Usage: 144 code... {END}" && exit; }

    codes=(`xargs -n1 <<<"${*}" | sed 's/^0*//g' | xargs printf "%06d "`)

    up add_codes_2_dzh2tbl ${codes[@]}
    END=${END} TBL=zxg up up_tbl_ma144_all

    sqls="SELECT t.code,t.date,t.close,ma144,100*(t.close-ma144)/ma144 as rise, c.name "
    sqls="${sqls} FROM tbl_ma144 as t, cap as c, zxg  WHERE t.code = c.code and t.code = zxg.code"
    sqls="${sqls} ${HAVING} ORDER by ${ASC:-zxg.id}"
    mysql -t kts<<<"${sqls}"
    xt_ret $? "${FUNCNAME}" || return $?

    return 0
}

function fn_ana_ma144()
{
    # 上海莱士，福建水泥
    # 若开涨了，预估起点与终点 
    #
    # 1. 

    local sqls="SELECT code FROM tbl_ma144 as m"
    local conds=(
        "m.close > ma13 and ma13>ma34*0.99 and "
        "m.width < .2 and "                       # 窄幅振荡
        "m.close > ma144*.9 and "                 # close接近ma144
        "m.close < ma144*${RISED:-1.10}"          # +10%涨幅内
    )

    local codes=(`mysql -N kts<<<"${sqls} WHERE ${conds[@]}"`)
    xt_ret $? "${FUNCNAME}" || return $?

    up add_codes_2_dzh2tbl ${codes[@]}
    xt_ret $? "${FUNCNAME}" || return $?

    codes=${codes[@]}
    sqls="SELECT code,width FROM tbl_ma144 WHERE code in (${codes// /,}) ORDER by width ASC"
    mysql -N kts<<<"${sqls}" | xargs -n8
    xt_ret $? "${FUNCNAME}" || return $?

    return 0
}


function fn_focus()
{
    local file=${YIST:-'.soptter.focus'}

    test -f ${file}
    xt_ret $? "${file} not exist" || return $?

    up add_codes_2_dzh2tbl ${file}
    TBL=zxg fn_dugu9jian ${END} ${2:-wchng}

    return $?
}

function fn_main()
{
    CURR=`fn_maxdate`
    END=${END:-${CURR}}
    PREV=`fn_get_prev`
    # SCREENER的宗旨，弃子取势
    # xet_block_info 为 sp_visit_tbl() 选定相应的BLOCK
    cmdlist=(
    "dugu9jian            [end [field]]         # NUM=61 .NMC end.close analyze"
    "6maishenjian         [end [field]]         # NUM=61 min(close) sort by #{COL}"
    "taox_ratio           [end [field]]         # NUM=61 套现比例分析"
    "tao                  code [end [field]]    # #{NUM}日，套现比例分析"
    "c144                 code... [end]         # cost:ma144 & sort by #{ASC:id}"
    "focus                [field]               # #{YIST:-.soptter.focus}->zxg and 9jian"
    "tao5                 code [end ]           # #{NUM}日，套现比例分析"
    "9jian                code [end [field]]    # #{NUM}日，个股成本分析"
    "6jian                code [end [field]]    # #{NUM}日，个股成本分析"
    "get_down_turnov      [start:curr-13] [end] # 100%下降净换手"
    "get_ma513            [end]                 # ma 5 13 34 55"
    "ana_ma513            index [end]           # 分析ma 5 13 34 55"
    "ana_ma240                                  # 分析ma 34 60 120 240"
    "ana_chao                                   # 分析超跌反弹"
    "get_rise_turnov      start [end]           # 100%上升净换手"
    "get_13d_20psink                            # 8日13日SINK超20%"
    "get_1_swing_num      [RISE_PERCENT:-8]     # 单日振幅，小于0计算跌幅"
    "get_n_swing_num      [SWING_PERCENT:-16]   # 双日振幅，小于0计算跌幅"
    "ana_ma144                                  # 分析ma144"
    "get_stat_turnov      code start [end]      # 个股区间换手统计"
    "sort_amount          [LIMIT_NUM:-48]       # --- 成交量排名"
    "sort_turnover        [LIMIT_NUM:-48]       # 最新日换手排名"
    # ----------------    ABOVE FIXED SEQUENCE  -------------------
    "get_block_info                             # 查看当前BLOCK"
    "set_block_info                             # 设置当前BLOCK"
    )

    # 存储过程函数文件的最后5行都是注释
    cd $workdir
    head -n -5 $mps_org > $mps_god

    # 为提高效率，可能使用临时表，必要请备份相应文件 call sp_cp_tbl('fr', 'to');
    fn_execute "$@" || return $?
}

fn_main "$@"
# fn_main 4
