#! /bin/bash -
#---------------------------------------------------------------------------
#          FILE: soptter
#         USAGE: ./soptter
#   DESCRIPTION: 
#        AUTHOR: chuangxiaomoo (God helps those who help themselves) 
#  ORGANIZATION: 
#       CREATED: 2014-02-24 09:35:42 PM
#      REVISION: 1.0 
#---------------------------------------------------------------------------

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

fn_realtime() 
{
    comma_sepa_list=`echo $@ | awk '{
        for (i=1; i<=NF; i++) {
            if ($i ~ /^[56]/) {
                printf "sh%s ", $i
            } else {
                printf "sz%s ", $i
            }
        }
    }' | tr ' ' ',' | sed 's/,$//g'`

    # 深证综指 sz399106
    indexlist='sh000016,sz399300,sz399004,sz399005,,sz399006'
    $W3M -dump "http://hq.sinajs.cn/list=${indexlist},${comma_sepa_list}" > ${rt_stdout} 
    xt_ret $? "NETWORK" || return $?

    printf "%6s\t%s\t\t%s\t%-5s\t%5s\t%s\n" \
            symbole trade pcnt  pcnt_hi pcnt_lo __name

    cat ${rt_stdout} | \
        sed -e '1s/sh000001/sh900001/' -e 's/var hq_str_..//g' -e 's/="/,/g' | \
        sed -n '1,5p' | awk -F',' '{
                printf "%06d\t%-8.2f\t%.2f\t%.2f\t%.2f\t%s\n", 
                     $1,
                     $5, 
                100*($5-$4)/$4, 
                100*($5-$6)/$4, 
                100*($5-$7)/$4, 
                $2;
            }'  | sort -g -r -k3

    cat ${rt_stdout} | \
        sed -e '1s/sh000001/sh900001/' -e 's/var hq_str_..//g' -e 's/="/,/g' | \
        sed -n '6,$p' | awk -F',' '{
                printf "%06d\t%.2f\t\t%.2f\t%.2f\t%.2f\t%s\n", 
                     $1,
                     $5, 
                100*($5-$4)/$4, 
                100*($5-$6)/$4, 
                100*($5-$7)/$4, 
                $2;
            }'  | sort -g -r -k3

    printf "%6s\t%s\t\t%s\t%-5s\t%5s\t%s\n" \
            symbole trade pcnt  pcnt_hi pcnt_lo __name
}

function fn_main()
{
    mkdir -p ${rt_stdout%/*}
#   YIST=${YIST:-'.blk.sc40'}
#   YIST=${YIST:-'.etf.50'}
#   YIST=${YIST:-'.blk.300dc'}
#   YIST=${YIST:-'.blk.bxy'}
#   YIST=${YIST:-'.blk.qs'}
#   YIST=${YIST:-'.blk.yhy'}
#   YIST=${YIST:-'.blk.cybz'}
#   YIST=${YIST:-'.soptter.etf'}
#   YIST=${YIST:-'.soptter.obor'}
#   YIST=${YIST:-'.soptter.lin'}
#   YIST=${YIST:-'.soptter.ying'}
#   YIST=${YIST:-'.soptter.ever'}
#   YIST=${YIST:-'.soptter.hljr'}
#   YIST=${YIST:-'.soptter.focus'}
    YIST=${YIST:-'.soptter.trade'}
    codelist=`cat ${YIST}|awk '/^[^#]/{print $1}'`
    fn_realtime ${codelist}
}

fn_main
