#! /bin/bash

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

url="http://stock.gtimg.cn/data/get_hs_xls.php?id=ranka&type=1&metric=name"
wget "$url" -O /tmp/kts/tecent.xls
excel2txt /tmp/kts/tecent.xls -o /tmp/kts

SRC='/tmp/kts/tecent.txt'

