#! /bin/bash

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

#
# ------  common part over -----------
#

function fn_cap()
{
    if [ "$1" = "--keep.FIN" ] || [ "$1" = "-k" ]; then
        echo "keep $p_bin/full.FIN"
    else
        read -p "
        Make sure U have down full.FIN?
        cp /dzh2/Download/FIN/full.FIN $p_bin"
        cp /dzh2/Download/FIN/full.FIN $p_bin
        xt_ret $? "" || return $?
    fi

    $workdir/sina
    xt_ret $? "sina fail" || return $?

    lines=`cat $sn_cap_nmc | wc -l`
    [ $lines -gt 2000 ] && [ $lines -lt 3000 ]
    xt_ret $? "$sn_cap_nmc lines $lines not in [2000,3000]" || return $?

    echo "
    DROP TABLE IF EXISTS cap;
    CREATE TABLE cap (
        id      int(4) ZEROFILL PRIMARY key AUTO_INCREMENT NOT NULL,
        code    INT(6)  ZEROFILL,
        date    DATE NOT NULL,
        close   DECIMAL(6,2) NOT NULL,
        cap     INT(14),
        nmc     INT(14),
        shares  DECIMAL(12,2) DEFAULT 0,
        name    CHAR(16),
        INDEX(code,date)
    );

    LOAD DATA LOCAL INFILE '$sn_cap_nmc' INTO 
    TABLE cap(code, date, close, cap, nmc, name);
    " | mysql -u root kts

    echo "
    INFILE '$sn_cap_nmc'
    update shares from dzh2 full.FIN...
    UPDATE cap SET nmc=close*shares WHERE nmc/close<shares;
    为兼容旧代码，最后的shares=nmc/close（只更新nmc，不更新shares）
    "

    # 修正 nmc & shares
    cd ${workdir}/bin
    ./fin > /dev/shm/fin
    mysql kts < /dev/shm/fin

    echo "
    UPDATE cap SET nmc=close*shares WHERE nmc/close<shares;
    " | mysql -u root kts

    # update .codelist
    cd ${workdir}
    mysql -N -B kts<<<"SELECT code,name FROM cap order by code asc;" | sed 's/ //g' > .codelist


    if [ `wc -l<.codelist` -gt 3000 ]; then
        fn_echo_fail "more than 3000 codes, please check it!"
        exit 1
    fi

    ./dbank 1
}

function fn_add_yesclose()
{
    local p_znz="$warehs/znz_day"
    local p_sql="$warehs/mysql"
    local day_del='2013-10-08'

    mkdir -p $p_sql
    cd $p_znz

    local i=
    for i in *; do
        sort -k2 -g $i | awk '{
            printf "%s\t%s\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\n" ,
            $1,$2, yesc, $3, $4, $5, $6, $7, $8;
            yesc=$6
        }' | sed "/$day_del/d" > $p_sql/$i
    done
}

# min/2013-09-30/14.59.01
#         TRADE           昨收    今开    最高 最低
# 000002  9.13    0.77    9.06    9.08    9.18 9.03 633756.30   576146571
#         $2                      $5      $6   $7
#
# day/000002
# 日期        开盘价  最高价  最低价  收盘价      成交量（万股）  成交额（万元）
# 2013-09-30  9.08    9.18    9.03    9.13        6337.56     57614.66

function fn_hexun_day()
{
    {
        echo "    try flock 19..."
        flock 19
        echo "    got flock 19..."
        fn_hexun_day0
        xt_ret $? "fail: day0" || return $?
    } 19<>'/dev/shm/up2'
}

function fn_hexun_day0()
{
    mkdir -p ${hx_dayclose%/*}

    unarm_close_forbid=true \
    fn_timestamp_market
    xt_ret $? "${FUNCNAME}" || return $?

    echo "    add hexun_day ${DATE}..."

    if [ "${FINA:-0}" -eq 1 ] ; then
        ./sina 
        xt_ret $? "sina" || return $?
        cp $sn_ripetxt $hx_dayclose
    else
        $workdir/hexun || {
            echo "try again..."
            sleep 2; $workdir/hexun || { fn_echo_fail "try 2 times fail"; return 1 ; }
        }

        awk '{
            printf "%06d\t%s\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\n",
                      $1, $13, $4, $5,  $6,  $7,  $2, ($8/100), ($9/10000)
        }'  $hx_ripetxt > $hx_dayclose
    fi


    $W3M -dump ${url_sh000001} | awk -F',' '{
        printf "%06d\t%s\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\n",
            '900001', $31, $3, $2, $5, $6, $4, ($9/100), ($10/10000);
    }' >> $hx_dayclose
    xt_ret $? "NETWORK" || return $?

    hx_lines=`cat $hx_dayclose | wc -l`
    if [ $hx_lines -lt ${baselines:=1300} ]; then
        wall <<< "up:${BASH_LINENO[0]} $hx_lines less than ${baselines} lines" 
        return 1
    fi

    grep -q 900001 $hx_dayclose || { echo "Error: 900001" && return 1 ;}

    mysql<<<"INSERT INTO kts.stamp_day values(DEFAULT, '$OPENDATE', '$OPENTIME')"
    xt_ret $? "" || return $?

    p_hx_day="$warehs/hx_day"
    mkdir -p $p_hx_day
    cp $hx_dayclose $p_hx_day/$DATE

    echo "
    DELETE FROM day WHERE date='${DATE}';
    LOAD DATA LOCAL INFILE '${hx_dayclose}' INTO TABLE day;
    " | mysql kts
}

function fn_trace()
{
    frog='/root/bin/stk/sql/trace.md'
    colA="date,curr_asset,frozen"       # ,sh,cyb"
    colA="A.${colA//,/,A.}"

    grep -v '^#' ${frog} | sed 's/  */\t/g'> ${buffer}

    echo "
        DROP TABLE IF EXISTS trace;
        CREATE TABLE trace (
            id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
            date        date,
            curr_asset  DECIMAL(9,1) DEFAULT 0,
            frozen      DECIMAL(9,1) DEFAULT 0,
            sh          DECIMAL(9,2) DEFAULT 0,
            cyb         DECIMAL(9,2) DEFAULT 0
        );

        LOAD DATA LOCAL INFILE '${buffer}' INTO TABLE trace(date,curr_asset,frozen,sh,cyb);

           SELECT ${colA}, 
               (A.curr_asset-B.curr_asset) as earning, 
               round(100*(A.curr_asset-B.curr_asset)/B.curr_asset, 2) as RoE,
               round(100*(A.curr_asset-B.curr_asset)/(B.curr_asset-A.frozen), 2) as RoE_real,
            -- (A.sh-B.sh) as earning_sh, 
            -- (A.cyb-B.cyb) as earning_cyb, 
               round(100*(A.sh-B.sh)/B.sh, 2) as RoE_sh,
               round(100*(A.cyb-B.cyb)/B.cyb, 2) as RoE_cyb
               FROM trace A INNER JOIN 
                    trace B on(A.id=B.id+1) GROUP BY A.id;

        -- SELECT *,
        --     round(100*(curr_asset-prev_asset)/prev_asset, 2) as RoE,
        --     round(100*(curr_asset-prev_asset)/(prev_asset-frozen), 2) as RoE_real
        --     FROM trace;
    " | mysql -t kts
    
    return $?
}

function fn_power()
{
    file0='/root/bin/stk/.soptter.power10'
    file1='/tmp/kts/power10'
    colA="code,quarter,power10,jigou,jgnewin,sholders,name"
    colA="A.${colA//,/,A.}"

    grep -v '^#' ${file0} > ${file1}
    echo "
        DROP TABLE IF EXISTS power10;
        CREATE TABLE power10 (
            id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
            quarter     INT DEFAULT 0,
            power10     DECIMAL(6,2) DEFAULT 0,
            jigou       INT DEFAULT 0,
            jgnewin     INT DEFAULT 0,
            code        INT(6)  ZEROFILL,
            sholders    INT DEFAULT 0,
            name        CHAR(16),
            INDEX(code)
        );

        LOAD DATA LOCAL INFILE '${file1}' INTO TABLE 
            power10(code,name,quarter,power10,jigou,jgnewin,sholders);
        SELECT ${colA} FROM power10 as A;
    " | mysql -t kts
    
    return $?
}

function fn_del_hexun_day()
{
    unarm_close_forbid=true \
    is_del_routine=true \
    fn_timestamp_market
    xt_ret $? "${FUNCNAME}" || return $?

    echo "
    del hexun_day ${DATE}...
    "

    mysql<<<"DELETE FROM kts.day WHERE date = '${OPENDATE}';"
    xt_ret $? "${FUNCNAME}" || return $?
}

function fn_redo_hexun_day()
{
    fn_hexun_day
    xt_ret $? "fail: day" || return $?

    sql="SELECT count(code) FROM day WHERE date='${OPENDATE}' and ((close-yesc)/yesc > .101)"
    num_gt10=`mysql kts -N <<<"${sql}"`
    if [ "${num_gt10}" -ge 30 ]; then
        # 修正yesc数据
        # iPREV=`END=${OPENDATE} fn_get_prev`
        # echo "
        # UPDATE day as dd,(SELECT * FROM day WHERE date='${iPREV}') as yy SET dd.yesc=yy.close WHERE dd.code=yy.code && dd.date='${OPENDATE}'
        # " | mysql kts
        fn_echo_warn "${sql}"
        fn_bell "msg.wav msg.wav"
    fi

    if [ "$?" -eq 0 ]; then
        echo "    redo hexun_day succ ^_^ @`date +%T`
        "
    else
        echo "    redo hexun_day fail #_#
        "
    fi
}

function fn_load_directory()
{
    local tbl_name='day'
    local f_sql="$warehs/znz.xRD"
    # 做成一个大文件会快得多
    cd ${znzday}
    cat * > $f_sql
    echo "
    LOAD DATA LOCAL INFILE '$f_sql' INTO TABLE $tbl_name
    " | mysql kts

    return $?
}

function fn_file_to_table_quick()
{
    f_yist='/tmp/kts/yist'
    cat ${YIST}|awk '/^[036]/{print $1}' > $f_yist
    echo "
    DROP TABLE IF EXISTS yist;
    CREATE TABLE yist (
        id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0
    );
    LOAD DATA LOCAL INFILE '$f_yist' INTO TABLE yist(code);
    " | mysql kts
}

function fn_file_to_table()
{
    if [ -f "${1}" ]; then
        [ ! -s "${1}" ] && fn_echo_fail "Error: file ${$1} is empty" && exit 1
        lst=(`awk '/^[036]/{print $1}' ${*}`)
        file_fr="from $1"
    elif [ -n "${1}" ]; then
        lst=(${@})
    else
        fn_echo_fail "Usage: file_to_table {file|code...}" && exit 1
    fi

    echo "
        DROP TABLE IF EXISTS ${TBL:=zxg};
        CREATE TABLE ${TBL} (
            id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
            code        INT(6) ZEROFILL NOT NULL DEFAULT 0
        );
        INSERT INTO ${TBL} (code) VALUES
        `sed -e 's/^/(/' -e 's/ /),(/g' -e 's/$/);/' <<< "${lst[@]}"` 
    " > ${sql_temp}

    mysql kts < ${sql_temp}
    xt_ret $? "${FUNCNAME}" || return $?
}

function fn_table_to_file()
{
    mysql -N -B kts <<< "SELECT code FROM ${1:-chao} ORDER by code asc;" > /tmp/zxg
    echo "    add `wc -l /tmp/zxg` code to /tmp/zxg over."
}

function fn_up_tbl_xRD()
{
    if [ "$1" = "--keep.PWR" ] || [ "$1" = "-k" ]; then
        echo "keep $p_bin/full.PWR"
    else
        echo "cp /dzh2/Download/PWR/full.PWR $p_bin"
        cp /dzh2/Download/PWR/full.PWR $p_bin
        xt_ret $? "" || return $?
    fi

    [ ! -f "$p_bin/xRD" ] && echo "xRD not exist" && exit
    cd $p_bin
    ./xRD | sort -r -k2 > $p_bin/xRD.list

    echo "
    DROP TABLE IF EXISTS xRD;
    CREATE TABLE xRD (
        code        INT(6)  ZEROFILL,
        date        DATE NOT NULL,
        song_ratio  DECIMAL(8,5) NOT NULL,
        pei_ratio   DECIMAL(8,5) NOT NULL,
        pei_price   DECIMAL(8,5) NOT NULL,
        div_ratio   DECIMAL(8,5) NOT NULL,
        INDEX(code,date)
    );

    LOAD DATA LOCAL INFILE '$p_bin/xRD.list' INTO TABLE xRD;
    " | mysql -u root kts


    if [ "$?" -eq 0 ] ; then
        echo "Update TABLE xRD SUCCESS" && return 0
    else
        echo "Update TABLE xRD FAILURE" && return 1
    fi
}

function fn_dump_day_2_tmp()
{
    # 对 /tmp 有写权限，其它的则需要设置
    chmod 777 ${daydump%/*}
    rm -f ${daydump}
    echo "
    SELECT * FROM day WHERE date>='${1:-$END}' and date<='${2:-$END}' INTO OUTFILE '${daydump}';
    " | mysql kts
}

function fn_trs_min_2_day()
{
    # 指南针数据是经过除权的数据，每次使用znz后要记住除权时间.

    [ -z "$1" ] && echo "Usage: $FUNCNAME date" && exit
    DATE=2013-12-12

    # SELECT code,date,yesc,open,high,low,close,volume,amount
    # SELECT code,date,open,high,low,close,volume,amount
    echo "
    SELECT code,date,yesc,open,high,low,trade,volume/100,amount/10000
        FROM min WHERE date='$DATE' and time='15:09:00';
	" | mysql -N kts > $m2d_temp

    ## LOAD时数据自动会进行四舍5入
    echo "
    LOAD DATA LOCAL INFILE '$m2d_temp' INTO TABLE day
	" | mysql kts

    return 0
}

function fn_redo_hexun_day_fr_min()
{
    #
    echo "    redo hexun_day fr min..."

    DATE=`mysql -N kts <<< "SELECT date FROM stamp_min WHERE id = (SELECT max(id) FROM stamp_min);"`
    TIME=`mysql -N kts <<< "SELECT time FROM stamp_min WHERE id = (SELECT max(id) FROM stamp_min);"`

    OPENDATE=`$W3M -dump ${url_sh000001} |awk -F',' '{print $(NF-2)}'`

    [ -z "$OPENDATE" ] && fn_echo_fail "    FINA UNREACHABLE!" && return 1
    [ "$DATE" != "$OPENDATE" ] && echo "Error: market is close" && return 1


    fn_del_hexun_day
    xt_ret $? "del error" || return $?

    echo "
    SELECT code,date,yesc,open,high,low,trade,volume/100,amount/10000
        FROM min WHERE date='$DATE' and time='${TIME}';
	" | mysql -N kts > $m2d_temp
    xt_ret $? "mysql > $m2d_temp" || return $?

    ## LOAD时数据自动会进行四舍5入
    echo "
    LOAD DATA LOCAL INFILE '$m2d_temp' INTO TABLE day
	" | mysql kts
    xt_ret $? "load data $m2d_temp" || return $?

    echo "    end of redo hexun_day fr min..."

    return 0
}

function fn_rzrq()
{
    > ${buffer}
    url0='http://datainterface.eastmoney.com/EM_DataCenter/JS.aspx?type=FD&sty=SHSZHSSUM'

    pages=4
    for (( i=1; i<=${pages}; i+=1 )); do
        url="${url0}&st=0&sr=1&p=${i}&ps=100&js=var%20EJcawWJn={pages:(pc),data:[(x)]}"
        w3m -dump "${url}" > ${cache}
        xt_ret $? "" || return $?
        
        cat ${cache} | tr -d '\n' |
            sed -e '1s/^.*data:.//' -e '$s/]}/\n/' |
            sed 's/","/\n/g'  | tr -d '"' >> ${buffer}
    done
    awk -F',' '{printf "%s\t%.2f\n", $1,$4/100000000}' ${buffer} > ${cache}

    echo "
    DROP TABLE IF EXISTS rzrq;
    CREATE TABLE rzrq (
        id      INT PRIMARY key AUTO_INCREMENT NOT NULL,
        date    DATE NOT NULL,
        net     DECIMAL(10,2) NOT NULL,
        INDEX(date)
    );

    LOAD DATA LOCAL INFILE '${cache}' INTO TABLE rzrq(date,net);
    " | mysql kts
    xt_ret $? "" || return $?

    fn_echo_succ "up rzrq succ"
}

function fn_wind()
{
    echo -n ${CURR} > ${file_wb}
    SCREENER 0
    echo "
    DROP TABLE IF EXISTS wind;
    CREATE TABLE wind (
        id      INT(6) PRIMARY key AUTO_INCREMENT NOT NULL,
        code    INT(6)  ZEROFILL
    );

    INSERT INTO wind(code) SELECT DISTINCT code FROM tbl_9jian WHERE close < avrg;
    " | mysql kts
    
    return $?
}

function fn_copy_table_2_table()
{
    fn_cp_tbl ${1:-zxg} ${2:-ipo}
    echo fn_cp_tbl ${1:-zxg} ${2:-ipo} over!!!
}

function fn_html()
{
    if [ "${FINA:-1}" -eq 1 ] ; then
        timeout 10 ./soptter > ${js_xunner_txt}
    else
        timeout 10 ./xunner > ${js_xunner_txt}
    fi
    xt_ret $? "timeout" || return $?

    names=(`awk '!/name/ {print $NF}' ${js_xunner_txt}`)
    codes=(`awk '!/name/ {print $1}' ${js_xunner_txt}| sed -e 's/^[03]/sz&/g' -e 's/^6/sh&/g'`)
    codes[0]=sh000001
    # echo ${names[@]}; echo ${codes[@]}; exit

    [ ${#names[@]} -eq ${#codes[@]} ]
    xt_ret $? "fail: ${#names[@]} -eq ${#codes[@]}" || return $?

    cp .template/KiTas.html /winc/relay/KiTas.html
    xt_ret $? "cp error" || return $?

    cat <<-"HERE_head" > /winc/relay/KiList.html
    <html>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>KiTas</title>
    <body>
    <p align="center">follow your heart!</p>
    <table align="center" width="100%" border="1">
	HERE_head

    local align='align="center" width="20%"'
    local chart='http://image.sinajs.cn/newchart'
    local target='TARGET="show"'
    local i
    for (( i=0; i<${#names[@]}; i+=1 )); do
    cat <<-HERE_mid >> /winc/relay/KiList.html
  <tr>
    <td align="center" width="40%">${names[$i]}</td>
    <td ${align}> <a HREF="${chart}/min/n/${codes[$i]}.gif"    ${target}>min</a> </td>
    <td ${align}> <a HREF="${chart}/daily/n/${codes[$i]}.gif"  ${target}>day</a> </td>
    <td ${align}> <a HREF="${chart}/weekly/n/${codes[$i]}.gif" ${target}>wek</a> </td>
  </tr>
	HERE_mid
    done
    cat <<-"HERE_tail" >> /winc/relay/KiList.html
    </table>
    </body>
    </html>
	HERE_tail
}

function fn_checkcode()
{
    if [ ! -f "${1}" ]; then
        echo "Usage: $FUNCNAME file"
        exit
    fi
    
    codes=(`cat ${1}|awk '/^[^#]/{print $1}' | xargs`)

    local i=
    for i in ${codes[@]}; do
        [[ ${i} =~ ^[036].* ]] || { echo "ignore code ${i}"; continue ;}
        grep -q ${i} .codelist
        xt_ret $? "${i} is a bad code" || return $?
    done

    fn_echo_succ "${1} is good code file"
}

function fn_day()
{
    bin/znz.yahoo $@
}


function fn_ipo()
{
    tmp='/tmp/kts/.ipo.tmp'
    raw='/tmp/kts/.ipo.raw'
    rip='/tmp/kts/.ipo.rip'

    > ${rip}

    local i
    for (( i=1; i<=1; i+=1 )); do
        url="http://datainterface.eastmoney.com/EM_DataCenter/JS.aspx?type=NS&sty=NSST&st=12&sr=-1&p=${i}&ps=50"

        echo dump ${url}
        w3m -dump "${url}" > ${tmp}

        # 's/,AN//g' 剔除申购准备中的票
        cat ${tmp} |sed -e '1s/(\[//' -e '$s/])//' -e 's/,AN//g' -e 's/"//g' | tr -d '\n' |
                    sed -e 's/AN201/\n&/g' -e 's/AN//g' | 
                    awk -F',' '/^201/{printf "%d\t%s\t%s\n", $1/1000000000000,$5,$4}'  > ${raw}

        cat ${raw} >> ${rip}
    done

    fn_echo_succ "
    日期为审批公告发布日期
    未申购的公司不在列表之内
    列表文件: ${rip}
    "
}

function fn_lhb()
{
    sql="SELECT max(date) FROM lhb"
    max_dt=`mysql -N kts <<< "${sql}"`
    max_dt=${max_dt/NULL/2015-07-08}
    sql="SELECT date from day WHERE code=900001 and date>'${max_dt}' ORDER by date ASC"
    dates=(`mysql -N kts <<<"${sql}"`)
    #dates=(2015-08-12 2015-08-14 2015-08-07)
    #echo ${dates[@]}

    if [ "${#dates[@]}" -eq 0 ]; then
        echo "It's latest" ; exit
    fi
    local i=
    for i in ${dates[@]}; do
        echo to up ${i}...
        fn_lhb0 ${i}
    done
    return $?
}

function fn_lhb0()
{
    url="http://data.eastmoney.com/stock/lhb/$1.html"
    w3m -cols 999 -dump "${url}" > ${lhb_raw}

    # $1      $2      $3      $4              $5   $6         $7          $8      $9          $10      $11
    # 序号  代码    名称      相关链接    涨跌幅  龙虎榜成  买入额(万)  占总成交  卖出额(万)  占总成交 上榜原因

    # ' N' 恒顺众日升 乱码
    cat ${lhb_raw} | grep -A1000 '^1\>' |
        sed -e 's/^           /999 1 2 3 4/' -e 's/ N\>//g' |
        grep '^[0-9]' > ${lhb_rip}
    #           12345678901
    awk -v v_date=$1 '
    BEGIN{ nr=0 } {
        if ($1==999) {
            printf "%s\t%s\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%s\t\n", \
                    v_date, code,chng,$6,$7,$8,$9,$10,$11;
        } else if ($1<nr) {
            exit
        } else if ($2<700000) {
            printf "%s\t%s\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%s\t\n", \
                    v_date, $2,$5,$6,$7,$8,$9,$10,$11;
            nr=$1;  
            code=$2;
            chng=$5;
        }
    }' ${lhb_rip} | 
    sed \
    -e 's/退市整理的证券/fired/g'                                       \
    -e 's/无价格涨跌幅限制的证券/unlimited/g'                           \
    -e 's/当日融资买入数量占该证券总交易量50%以上/rzrq50/g'             \
    -e 's/日均换手率与前五个交易日的.*/ratio30/g'                       \
    -e 's/当日价格振幅达到15%的证券/hilo15/g'                           \
    -e 's/当日换手率达到20%的证券/tov20/g'                              \
    -e 's/当日涨幅偏离值达7%的证券/up7/g'                               \
    -e 's/当日跌幅偏离值达7%的证券/dn7/g'                               \
    -e 's/S、ST、.ST连续三个交易日跌幅.*/s3dn12/g'                      \
    -e 's/S、ST、.ST连续三个交易日涨幅.*/s3up12/g'                      \
    -e 's/连续三个交易日收盘价涨幅偏离值累计20%/3up20/g'                \
    -e 's/连续三个交易日收盘价跌幅偏离值累计20%/3dn20/g'  > ${lhb_pro}

    awk '{print $2}' ${lhb_pro} | grep -q '^6'
    xt_ret $? "Error: sh_sec lhb is not released" || return $?

    lines=`wc -l<${lhb_pro}`
    if [ "${lines}" -lt 5 ]; then
        echo "Bad lhb data: ${url}"
        exit
    fi

    echo "
    -- DROP TABLE IF EXISTS lhb;
    CREATE TABLE IF NOT EXISTS lhb (
        id      int(4) ZEROFILL PRIMARY key AUTO_INCREMENT NOT NULL,
        date    DATE NOT NULL,
        code    INT(6)  ZEROFILL,
        chng    DECIMAL(6,2) NOT NULL,
        amount  DECIMAL(10,2) NOT NULL,     -- 万
        buy     DECIMAL(10,2) NOT NULL,
        bloo    DECIMAL(10,2) NOT NULL, 
        sell    DECIMAL(10,2) NOT NULL,
        sloo    DECIMAL(10,2) NOT NULL, 
        cause   CHAR(20),
        INDEX(date,code)
    );

    DELETE FROM lhb WHERE date='$1';
    LOAD DATA LOCAL INFILE '${lhb_pro}' INTO 
    TABLE lhb(date,code,chng,amount,buy,bloo,sell,sloo,cause);
    " | mysql -u root kts

    return $?
}

function fn_dorat()
{
    case $1 in
    l|loop)
        is_del_routine=true fn_timestamp_market
        xt_ret $? "unarm_close_forbid=true TO RERUN WHEN MARKET CLOSED" || return $?
        fn_isresting && { echo "is reseting"; exit 0; }
        ;;
    esac

    # [ $hhmm = 0940 ] || [ $hhmm = 0950 ] || [ $hhmm = 1015 ]
    hhmm=`date +%H%M | sed 's/^0//'`;
    
    [ "${hhmm}" = 930 ] && sleep 30
    let got30=hhmm%100%30   # 半小时响铃一次

    if [ "${got30}" -le 1 ] || [ $hhmm = 935 ] || [ $hhmm = 940 ] || [ $hhmm = 950 ]; then
        fn_bell "online.wav"
    fi

    if [ -z "${TBL}" ]; then
        fn_redo_hexun_day || FINA=1 up 4
        xt_ret $? "" || return $?
        sec_dt=(`mysql -N kts<<<"SELECT date,time FROM stamp_day ORDER by id DESC LIMIT 1"`)
    else
        # 手动补全5分钟数据，hexun会失败
        # DROP TABLE dorat_temp;
        # CREATE TABLE IF NOT EXISTS dorat_temp LIKE dorat;
        # INSERT INTO dorat_temp SELECT * FROM dorat WHERE date='2015-08-17' and time='11:14:49';
        # UPDATE dorat_temp SET time='11:20:00';
        # INSERT INTO dorat SELECT * FROM dorat_temp;
        sec_dt=${TBL#dorat_}
        sec_dt=(`fn_dt_hyphen_2_normal ${sec_dt}`)

    fi

    sec_date=${sec_dt[0]}
    sec_time=${sec_dt[1]}
    columns="code,yesc,open,high,low,close,volume,amount"
    # COND0="WHERE date='${sec_date}'" fn_cp_tbl day dorat_${sec_date//-/_}_${sec_time//:/_}
    echo "
    -- DROP TABLE dorat;
    CREATE TABLE IF NOT EXISTS dorat (
        date        date NOT NULL, 
        time        time NOT NULL, 
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0,
        yesc        DECIMAL(6,2) NOT NULL,
        open        DECIMAL(6,2) NOT NULL,
        high        DECIMAL(6,2) NOT NULL,
        low         DECIMAL(6,2) NOT NULL,
        close       DECIMAL(6,2) NOT NULL,
        volume      DECIMAL(12,2) NOT NULL,
        amount      DECIMAL(12,2) NOT NULL,
        INDEX(date,time,code)
    );
    DELETE from dorat WHERE date='${sec_date}' && time='${sec_time}';
    INSERT INTO dorat SELECT date,'${sec_time}',${columns} FROM ${TBL:-day} WHERE date='${sec_date}';
    " | mysql kts
    xt_ret $? "" || return $?

    fn_echo_succ "    succ: insert dorat ${sec_dt[@]}"
    
   #nb_2015=`cat /tmp/kts/2015 2>/dev/null`
   #if [ "${nb_2015:-1}" -eq 1 ]; then
    let got21=hhmm%100%30
    if [ "${got21:-0}" -lt 2 ]; then
        #echo got21:${got21}@${hhmm} >> /tmp/kts/got21
        fn_bell "system.wav"
    fi

    return 0
}

function fn_example_not_work_by_group()
{
    echo "
    SET @v_id = 1; 
    SELECT max(id)   FROM code2015 INTO @v_len;
    WHILE @v_id <= @v_len DO
        SELECT code FROM code2015 WHERE id=(@v_id) INTO @v_code;
        INSERT INTO ma2015(code,ma2015)
            SELECT @v_code, sum(close)/20 FROM (SELECT close FROM dorat2 WHERE code=@v_code) as t;
        SET @v_id = @v_id + 1;
    END WHILE;
    "
}

function fn_ma2015()
{
    function fn_creat_db_ma2015()
    {
        # fn_echo_fail "db DT is ${DT[@]}" > /dev/stderr
        # TEMPORARY=TEMPORARY
        echo "
        DROP   $TEMPORARY TABLE IF EXISTS dorat2;
        CREATE $TEMPORARY TABLE IF NOT EXISTS dorat2 (
            code        INT(6) ZEROFILL NOT NULL DEFAULT 0,
            close       DECIMAL(6,2) NOT NULL,
            date        date,
            time        time,
            INDEX(code)
        );"
        while read date time; do
            echo "INSERT INTO dorat2 SELECT code,close,date,time FROM dorat WHERE date='${date}' and time='${time}';"
        done <<<"`DT="${DT[@]}" ./SELECT dorat | tac | head -60 | sed -n '1~3p'`"
    }

    DT=(${DT})
    iEND=${DT[0]}
    END=${iEND:-$END}
    PREV=`fn_get_prev`
    fn_creat_db_ma2015 > ${mps_ma2015}

    echo "
delimiter //

DROP PROCEDURE IF EXISTS sp_ma2015 //
CREATE PROCEDURE sp_ma2015() tag_ma2015:BEGIN
    DROP   TABLE IF EXISTS ma2015;
    CREATE TABLE ma2015(
        id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0,
        ma2015      DECIMAL(8,2) NOT NULL DEFAULT 0
    );
    INSERT INTO ma2015(code,ma2015)
        SELECT t.code,ma2015 FROM ( SELECT code,sum(close)/20 as ma2015 FROM dorat2 GROUP by code ) as t, 
        (SELECT A.code FROM 
          (SELECT code FROM day WHERE date='${END}') as A,
          (SELECT code FROM day WHERE date='${PREV}') as B WHERE A.code=B.code 
        ) as code2015 
        WHERE t.code=code2015.code;
    -- NOT IN 比较慢
    -- SELECT code,sum(close)/20 as ma2015 FROM dorat2 GROUP by code;
    -- DELETE FROM ma2015 WHERE code NOT IN(SELECT code FROM code2015);
END tag_ma2015 //

call sp_ma2015();
    " >> ${mps_ma2015}
    mysql kts < ${mps_ma2015}
    xt_ret $? "" || return $?
    fn_echo_succ "    succ: up ma2015@${DT[@]}!"
    return $?
}

function fn_sipf()
{
    w3m -cols 999 -dump 'http://data.eastmoney.com/cjsj/bankTransfer.html' > ${chao}.sipf
    grep '^201[3-9]' ${chao}.sipf | sed -e 's/[年月]/-/g' -e 's/日//g' -e 's/  */\t/g' | \
        sed 's/\t[0-9.]*\t[0-9.%-]*$//g' | sort -k1 | grep -A1000 '2014-03-31' > ${chao}.ssss

    fn_echo_succ "succ and 使用sina数据后自动返回!"

    return

    fn_echo_succ "余额期末数\t日平均数\t银证转账+\t银证转账-\t银证转账net
    "
    url="
http://www.sipf.com.cn/NewCH/zt/11/101752.shtml
    "
    w3m -dump $url | grep 证券交易结算资金 | sed 's/,//g' | \
        awk '{printf "%s\t%s\t%s\t%s\t%s\n", $4,$6,$8,$10,$12}'

    # 两部分数据格式不一样，所以分的两部分
    exit
    host='http://www.sipf.com.cn'
    dates=(
    "/NewCH/zt/01/94402.shtml"    201501
    "/NewCH/zt/12/93151.shtml"    201412
    "/NewCH/zt/11/92201.shtml"    201411
    "/NewCH/zt/10/90801.shtml"    201410
    "/NewCH/zt/09/89104.shtml"    201409
    "/NewCH/zt/08/88352.shtml"    201408
    "/NewCH/zt/07/87752.shtml"    201407
    "/NewCH/zt/06/87102.shtml"    201406
    "/NewCH/zt/05/86303.shtml"    201405
    "/NewCH/zt/04/85854.shtml"    201404
    )
    for (( i=${#dates[@]}-1; i>0; i-=2 )); do
        let j=i-1
        echo -e "month: \t${dates[$i]}"
        w3m -dump "${host}/${dates[$j]}" | grep '201.\.' | sed 's/,//g' | \
            awk '{printf "%s\t%s\t%s\t%s\t%s\n", $2,$3,$4,$5,$6}'
    done

    dates=(
    "/NewCH/zt/09/100802.shtml"   201509
    "/NewCH/zt/08/100352.shtml"   201508
    "/NewCH/zt/07/99752.shtml"    201507
    "/NewCH/zt/06/98652.shtml"    201506
    "/NewCH/zt/05/97802.shtml"    201505
    "/NewCH/zt/04/97002.shtml"    201504
    "/NewCH/zt/03/96352.shtml"    201503
    "/NewCH/zt/02/95209.shtml"    201502
    )
    local i
    for (( i=${#dates[@]}-1; i>0; i-=2 )); do
        let j=i-1
        echo -e "month: \t${dates[$i]}"
        w3m -dump "${host}/${dates[$j]}" | grep 证券交易结算资金 | sed 's/,//g' | \
            awk '{printf "%s\t%s\t%s\t%s\t%s\n", $4,$6,$8,$10,$12}'
    done 
}

function fn_nets()
{
    # 2014-04 free0=5755
    awk '
    BEGIN { sum=0; free0=5755; net=0; }
    {
        net=net+$7;
        sum=(free0-$3)+$7+sum;
        printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n", $1,$2,$3,$4,$5,$6,$7,sum,net
        free0=$3;
    }'  ${chao}.ssss > ~/bin/stk/sql/money.clean
    fn_echo_succ "Done gen ~/bin/stk/sql/money.clean"
}


function fn_bala()
{
    cp sql/money.clean ${chao}.clean
    xt_ret $? "" || return $?

    head -n -5 $mps_org > $mps_nbm
    
    echo "
    DROP TABLE IF EXISTS balance;
    CREATE TABLE balance(
        id      int PRIMARY key AUTO_INCREMENT NOT NULL,
        mon     DATE NOT NULL,
        fri     DATE NOT NULL,
        close   INT DEFAULT 0,
        avrg    INT DEFAULT 0,
        kin     INT DEFAULT 0,
        kout    INT DEFAULT 0,
        net     INT DEFAULT 0,
        balance INT DEFAULT 0,
        INDEX(mon)
    );

    LOAD DATA LOCAL INFILE '${chao}.clean' INTO 
    TABLE balance(mon,fri,close,avrg,kin,kout,net);
    " | mysql kts

    echo "
DROP PROCEDURE IF EXISTS sp_mamacd //
CREATE PROCEDURE sp_mamacd() BEGIN
    DECLARE v_i INT DEFAULT 1;
    SET @v_len = 0;
    SELECT max(id) FROM balance INTO @v_len;
    loop_visit: REPEAT
        SELECT sum(net) FROM balance WHERE id<=v_i INTO @sumofnet;
        UPDATE balance SET balance=@sumofnet WHERE id=v_i;
        SET v_i = v_i + 1;
    UNTIL v_i > @v_len END REPEAT;

END //
call sp_mamacd();
    " >> $mps_nbm
    mysql $OPT -t kts <"$mps_nbm"
    
    fn_echo_succ "TABLE balance done..."
    return $?
}

function fn_wklist()
{
    echo "
    SELECT date,wkday FROM zzlt;
    " |  mysql -N kts  > ${chao}.wkday

    date_prev=NULL
    wkday_prev=6

    while read date wkday; do
        if [ "${date_prev}" != NULL ]; then
            dif=$(( ($(date -d "${date}" +%s) - $(date -d "${date_prev}" +%s))/(24*60*60) ))
        else
            dif=0
        fi
        fn_echo_warn haha: "${wkday}" -lt ${wkday_prev}
        if [ "${wkday}" -lt ${wkday_prev} ] || [ ${dif} -gt 7 ]; then
            wknew=${wkday}
            echo -e -n "${date_prev}\n${date}\t"
        fi
        date_prev=${date}
        wkday_prev=$wkday
    done < ${chao}.wkday > ${chao}.wklist
    fn_echo_succ "save to ${chao}.wklist"
    
    return $?
}

function fn_money()
{
    usage="
    券商经纪资金一周只更新一次。步骤如下：
    s|sipf      0 downLoad from sina 更新数据 并且 >> sql/money
    n|nets      1 计算叠加的.净流入 >> sql/money.clean
    z|zzlt      2 从同花顺获取数据，更新到表.中证流通.zzlt
    b|bala      3 从money.clean，生成表balance
    r|rzrq      4 更新RZRQ数据
    l|list      5 联合查讯
    u|usage     * 打印Usage
    "
    case $1 in
    s|sipf)
        fn_sipf
        ;;
    n|nets)
        fn_nets
        ;;
    z|zzlt)
        fn_zzlt
        ;;
    w|wklist)
        fn_wklist
        ;;
    r|rzrq)
        fn_rzrq
        ;;
    b|bala)
        fn_bala
        echo
        ;;
    l|listbana)
        fn_listbana
        ;;
    u|*)
        echo "${usage}"
        ;;
    esac

}
function fn_listbana()
{
    fn_echo_warn "
    cat /Export/Table.txt | awk 'BEGIN{sum=0; } { sum+=$3; } END{print sum}' ==> 37.1965万亿  5746.20
    net             当周银证增量
    balance         自2014.4银证增量资金和
    bala_rzrq       rzrq绝对资金
    bala_sum        (银证+rzrq)资金
    LT              流通总市值
    Dif_bala        自2014.4的增量资金
    Dif_LT_55
    "
    echo "
    SELECT b.*,r.net as bala_rzrq,(b.balance+r.net)as bala_sum,z.close as zzltC,
        round(371965*z.close/5746.20,2) as LT, 
        round(b.balance+r.net-4234.66)as Dif_bala,
        round((371965*z.close/5746.20-193466.21)/5.5,2) as Dif_LT_55
    FROM balance as b, rzrq as r, zzlt as z 
    WHERE b.fri=r.date && b.fri=z.date 
    ORDER by fri ${ASC:-DESC} LIMIT ${LIMIT:-40}
    " | mysql ${OPT:--t} kts
}

function fn_fenbi()
{
    code=$1
    date=${2:-${END//-/}}
    #code=399006
    fn_iscode ${code} || fn_isindex ${code}
    xt_ret $? "arg1 not code" || return $?

    [ "${#date}" -eq 8 ]
    xt_ret $? "date format 2015mmdd" || return $?

    sql="SELECT round(datetime/1000000) as dt, TRUNCATE(datetime%1000000/100,0) as time FROM fenbi"
    mysql -N kts <<< "${sql} WHERE code=${code} HAVING dt=${date}" | awk '{print $2}' > /tmp/kts/fenbi.up1

    close=`mysql -N kts <<< "SELECT max(trade) FROM fenbi WHERE code=${code} and datetime>${date}000000"`
    # echo ${close};exit
    grep -v -f /tmp/kts/fenbi.up1 sql/min.table > /tmp/kts/fenbi.up2
    rows=`wc -l < /tmp/kts/fenbi.up2`
    
    if [ "${rows}" -eq 0 ]; then
        echo rows is 0, exit
        exit
    else
        echo rows: ${rows}
    fi

    awk -v v_code=${code} -v v_date=${date} -v v_close=${close} '{
        printf "%s\t%s%06d\t%.2f\t%d\t%d\n", v_code, v_date,$1*100+55, v_close, 0,0
    }' /tmp/kts/fenbi.up2 > ${buffer}

    echo "
    LOAD DATA LOCAL INFILE '${buffer}' INTO TABLE fenbi(code, datetime, trade, volume, amount)
    " | mysql kts
}

function fn_yysj()
{
    pages=100       # assign to 0 to SKIP download, 100 to normal DL

    [ ${pages} != 0 ] && >${buffer}

    # 通过F12查看时间 http://data.eastmoney.com/bbsj/201512/yysj.html
    date=2015-12-31
    suffix='&js=var%20aisNXBuK={pages:(pc),data:[(x)]}&stat=0'
    url0="http://datainterface.eastmoney.com/EM_DataCenter/JS.aspx?type=SR&sty=YYSJ&"

    local i
    for (( i=1; i<=${pages}; i+=1 )); do
        fn_echo_succ "downlode ${i}..."
        url="${url0}fd=${date}&st=2&sr=1&p=${i}&ps=400${suffix}"
        # echo ${url}; exit
        w3m -cols 84 -dump "${url}" > ${cache}
        #
        [ "${pages}" -gt 10 ] && pages=`awk -F '[:,]' '/aisNXBuK/{print $2}' ${cache}`
        cat ${cache}  | tr -d '\n' |
            sed -e '1s/^.*data:.//' -e '$s/]}/\n/' |
            sed 's/","/\n/g'  | tr -d '"' >> ${buffer}
    done

    awk -F',' '{
        if ($5!="") {
            yysj=$5
        } else if ($4!="") { 
            yysj=$4
        } else {
            yysj=$3;
        }
        printf "%s\t%s\t%s\n", $1,yysj,$2
    }' ${buffer} > ${buffer}.rip

    echo "
    DROP TABLE IF EXISTS yysj;
    CREATE TABLE yysj (
        id      int(4) ZEROFILL PRIMARY key AUTO_INCREMENT NOT NULL,
        code    INT(6)  ZEROFILL,
        date    DATE NOT NULL,
        name    CHAR(16),
        INDEX(code,date)
    );

    LOAD DATA LOCAL INFILE '${buffer}.rip' INTO 
    TABLE yysj(code, date, name);
    " | mysql kts

    return $?
}

function fn_merge()
{
    [ -f "${1}" ]
    xt_ret $? "${1} not exist" || return $?

    cat ${@} > ${chao}.merge
    xt_ret $? "merge ${@}" || return $?
    PLAIN=${chao}.merge fn_gen_10jqka_sel
    return $?
}

function fn_zzlt()
{
    echo "
    -- DROP TABLE IF EXISTS zzlt;
    CREATE TABLE IF NOT EXISTS zzlt(
        id      int(4) PRIMARY key AUTO_INCREMENT NOT NULL,
        date    DATE NOT NULL,
        wkday   INT,
        close   DECIMAL(6,2) NOT NULL,
        INDEX(date)
    );"| mysql kts

    maxdate=`mysql -N kts <<< "SELECT max(date) FROM zzlt"`
    fn_echo_succ "maxdate is ${maxdate}"

    if [ "${maxdate}" != NULL ]; then
        iconv -f cp936 -t utf8 /Export/Table.txt | grep -A200 "${maxdate}"  > "${chao}.zzlt"
        xt_ret $? "bad Table.txt" || return $?

        sed -i "/${maxdate}/d" ${chao}.zzlt
        xt_ret $? "" || return $?
    else
        iconv -f cp936 -t utf8 /Export/Table.txt > "${chao}.zzlt"
        fn_echo_warn "first do zzlt"
    fi

    [ -f "${chao}.zzlt" ]
    xt_ret $? "" || return $?

    sed -i -e '/时间/d' -e 's/,/\t/g' -e 's/  */\t/g' \
        -e 's/\t\t/\t/g'\
        -e 's/一/1/g'   \
        -e 's/二/2/g'   \
        -e 's/三/3/g'   \
        -e 's/四/4/g'   \
        -e 's/五/5/g'   \
        -e 's///g'    \
        -e '/^$/d'      ${chao}.zzlt

    fn_echo_succ "content to load:"
    cat ${chao}.zzlt

    echo "
    LOAD DATA LOCAL INFILE '${chao}.zzlt' INTO 
    TABLE zzlt(date,wkday,@dummy,@dummy,@dummy,close);
    " | mysql -u root kts
    
    fn_echo_succ "up zzlt OK"
}

function fn_dig()
{
    if [ ! -f "${chao}.dig" ]; then
        fn_echo_fail "${chao}.dig not exist!"
        exit
    fi

    sed 's/[036][0-9][0-9][0-9][0-9][0-9]/\n&\n/g' ${chao}.dig | grep '^[036]' | \
        grep .codelist -f - | \
        tee ${chao}.dig.rip
    sed -i 's/$/\r/' ${chao}.dig.rip
    PLAIN=${chao}.dig.rip fn_gen_10jqka_sel
    fn_echo_succ "succ to 自选股.sel"
    return $?
}


function fn_market()
{
    url0="http://data.eastmoney.com/Notice/Noticelist.aspx?type=0&market=${market}&"

    w3m -cols 1000 -dump "${url0}date=${date}" > ${temp} 
    pages=`cat ${temp} | grep '下一页' | sed 's/下一页.*//g' | awk '{print $NF}'`
    # echo "${url0}date=${date}"
    NL=N fn_echo_warn "market=${market}&date=${date}&pages=$pages\t"

    local i
    for (( i=2; i<=${pages:-0}; i+=1 )); do
        echo -n " $i"
        # echo "market=${market}&date=${date}&page=$i ..."
        url="${url0}date=${date}&page=$i"
        w3m -cols 1000 -dump "${url}" >> ${temp}
    done
    echo

    return $?
}

function fn_notice0()
{
    local market=
    for market in sh_a sz_a zxb cyb sh_b sz_b; do
        temp=${chao}.notice.${market}
        fn_market
       #grep '更多公告股吧研报' ${temp} | grep '^[036]' >> ${notice}/${date}
        grep '更多公告股吧研报' ${temp} >> ${notice}/${date}
    done

    fn_echo_succ "@succ ${notice}/${date}"
    
    return $?
}

function fn_notice()
{
    notice=${chao}.notice
    ln -sfT /opt/notice ${chao}.notice

    start=`ls -r /opt/notice | head -1`

    hhmm=`date +%H%M | sed 's/^0//'`;
    [ "${hhmm}" -gt 1530 ] && news=1 || news=0
    newest=`date --date="${news} days" +'%F'`

    NUM=${NUM:-${1:-7}}

    local i
    for (( i=0; i<${NUM}; i+=1 )); do
        date=`date --date="${start} ${i} days" +'%F'`
        #echo ${date};continue
        >${notice}/${date}
        fn_notice0
        [ "${date}" = "${newest}" ] && break
    done
}

function fn_main()
{
    cmdlist=(
    # fixed sequence
    "cap [--keep.FIN -k]                # (max(中国石油)=2万亿 sum(nmc)=20万亿)"
    "redo_hexun_day_fr_min              # 利用已有分线，重做大盘日线"
    "hexun_day                          # 大盘日线数据 4:00:00 PM"
    "del_hexun_day                      # 删除大盘日线，防止冲突"
    "redo_hexun_day                     # 重做大盘日线数据"
    # --------------------              ABOVE IS FIXED SEQUENCE --------------------
    "up_tbl_xRD [--keep.PWR -k]         # --- 使用当前除权数据 --keep.PWR"
    "file_to_table {code...|file}       # 写file到表{TBL:-zxg}，并........ZXG.BLK........"
    "table_to_file {table:-chao}        # 添加表{table:-chao}到/tmp/zxg"
    # --------------------              ABOVE IS FIXED SEQUENCE --------------------
    "checkcode file                     # "
    "html                               # flush YIST=.soptter.xxx soptter result into html"
    "copy_table_2_table src dst         # --- 使用 1 1 做为代号"
    "add_yesclose                       # 为yahoo.指南针数据添加yesclose"
    "load_directory                     # load文件夹${znzday}到表day"
    "dump_day_2_tmp START END           # 导出日线到${daydump} \${START:-\$END} \${END:-\${END}}"
    "trs_min_2_day                      # 最后一笔分线转日线"
    "wind                               # wind(close<avrg)"
    "day    code                        # DL 1year data from znz"
    "ipo                                # DL ipo codes from east"
    "lhb                                # 龙虎榜"
    "dorat  [loop]                      # 量比数据，loop when run@crontab"
    "ma2015                             # "
    "yysj                               # 预约时间"
    "trace                              # "
    "fenbi  code 2015mmdd               # "
    "money                              # ---------资金分析---------"
    "power                              # 权重分析"
    "merge  file...                     # 合并多个文件到chao.merge"
    "dig                                # 从<chao.dig>输入，并输出到<dig.txt>"
    "notice NUM                         # 至多NUM天，更新公告 /opt/notice/"
    )

    # 存储过程函数文件的最后5行都是注释
    cd $workdir
    head -n -5 $mps_org > $mps_god

    fn_set_END
    fn_execute "$@"
}

fn_main "$@"

