#! /bin/bash

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_dugu9jian()
{   # date1,date2,amount,open
    columns="off,avrg,close,turnov"
    columns=${columns:-'*'}
    columns=t.${columns//,/,t.}

    DATE2=`mysql -N kts <<< "SELECT date2 from ${tablex:-tbl_9jian} LIMIT 1"`

    echo ----- COND: $COND -----
    function fn_get_tbl_9jian_dive()
    {
        tbl_super_dive="
        SELECT t.code,  DATE_FORMAT(date1,'%m-%d') as start, 
                        DATE_FORMAT(date2,'%m-%d') as end, ${columns}, c.nmc, chng, 
                        round(100*(d.yesc-d.low)/d.yesc,2) as down,
                        round(100*(d.close-d.low)/d.yesc,2) as up,
                        round(100*(t.low-avrg)/avrg,2) as lchng, 
                        round(100*(t.close-avrg)/avrg,2) as wchng, c.name 
           FROM ${tablex:-tbl_9jian} as t, cap as c, (SELECT * from day where date='${DATE2}') as d
           WHERE t.code = c.code and t.code = d.code HAVING 1 ${COND} 
           ORDER by ${1:-lchng} ${ASC:-asc} limit ${LIMIT:-36}     # COND='nmc<150000 and lchng<-9.7 and off<14'
        "
        echo "${tbl_super_dive}"
    }

    fn_get_tbl_9jian_dive $1
    lines=`mysql $mo -N kts <<< "${tbl_super_dive}" | wc -l`

    if [ "${lines}" -ge 1 ] ; then
        fn_write "
        ---------------------------
            ${lines} catched!!!
        ---------------------------
        "
    fi
}

function fn_main()
{
    # up 21 (windbell_codes) to accelerate
    export inwind=1
        COND='and lchng<-14 and up>.6' fn_dugu9jian
        exit

    while :; do
        up 4
        TBL=windbell_codes SCREENER 0
        COND='and lchng<-14 and up>.6' fn_dugu9jian
        sleep 25
    done
}

fn_main ${@}
