#! /bin/bash
. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc


function fn_up_raw()
{
    epath='/Export/'
    efile=`ls -t ${epath} | head -1`
    ctime=`ls -lt --time-style=+%s ${epath}/${efile} | awk '{print $6}'`
    fresh=600
    epoch=`date --date="${fresh} minute ago" +%s`
    t1500=`date --date="${CURR} 15:00:00" +%s`

    if [ "${ctime}" -lt ${epoch} ]; then
        past=`echo "scale=1;${fresh}+(${epoch}-${ctime})/60" | bc -l`
        fn_echo_fail "[fresh:${fresh}] ${efile} is laged ${past} min"
        return 1
    fi

    # 收盘后处理
    [ "${ctime}" -gt ${t1500} ] && ctime=${t1500}
    HHMMSS=`date -d @${ctime} +%T`

    # 代码   名称  机构动向     主动买入比  被动买入比  主动卖出比  被动卖出比 
    # 涨幅%  现价  涨速%        总手        换手        金额        流通市值    所属行业
    iconv -f cp936 -t utf8 ${epath}/${efile} | tail -n+2 > ${wolf_raw}
    if ! grep -q SZ300 ${wolf_raw}; then
        fn_echo_fail "not a wolf file"
        return 1
    fi

    tag_blank='--.--.--'
    sed -e 's///g' -e 's/S.//g' -e 's/ //g'               \
        -e 's/%//g' -e 's/\t$//g' -e 's/\t\t*/\t/g'         \
        -e "/${tag_blank}/d" -e '/^$/d' ${wolf_raw}         \
        | awk '{
            printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%.2f\t%.2f\t%s\n", 
            $1,$3,$4,$5,$6,$7,$8,$9,10,$11/10000,$12, $13/100000000, $14/100000000,$2
        }' \
        | sed "s/^/${CURR}\t${HHMMSS}\t/g" > ${wolf_rip}

    # 13:43:31
    # echo ${efile} ${ctime} ${epoch} $HHMMSS
    
    return $?
}

function fn_up_rip()
{
    echo "
    CREATE TABLE IF NOT EXISTS mat_dde (
        id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
        date        date NOT NULL DEFAULT 0,
        time        time NOT NULL, 
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0,
        pcnt        DECIMAL(6,2) NOT NULL DEFAULT 0, -- dec(p-n)/sum(p+n)
        pbuy        DECIMAL(6,2) NOT NULL DEFAULT 0,
        nbuy        DECIMAL(6,2) NOT NULL DEFAULT 0,
        psell       DECIMAL(6,2) NOT NULL DEFAULT 0,
        nsell       DECIMAL(6,2) NOT NULL DEFAULT 0,
        rise        DECIMAL(6,2) NOT NULL DEFAULT 0,
        trade       DECIMAL(6,2) NOT NULL DEFAULT 0,
        speed       DECIMAL(6,2) NOT NULL DEFAULT 0,
        shou        DECIMAL(8,2) NOT NULL DEFAULT 0,
        tov         DECIMAL(8,2) NOT NULL DEFAULT 0,
        amount      DECIMAL(8,2) NOT NULL DEFAULT 0,
        nmc         DECIMAL(8,2) NOT NULL DEFAULT 0,
        name        CHAR(16),
        INDEX(date,time,code)
    );

    CREATE TABLE IF NOT EXISTS dde LIKE mat_dde;

    DROP   TEMPORARY TABLE IF EXISTS ddx;
    CREATE TEMPORARY TABLE ddx LIKE mat_dde;
    LOAD DATA LOCAL INFILE '${wolf_rip}' INTO TABLE 
           ddx(date,time,code,pcnt,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name);

    DELETE FROM     dde WHERE date='${CURR}';
    INSERT INTO     dde(date,time,code,pcnt,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name)
        SELECT date,time,code,pcnt,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name FROM ddx;

    DELETE FROM mat_dde WHERE date='${CURR}' && time='${HHMMSS}';
    INSERT INTO mat_dde(date,time,code,pcnt,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name) 
        SELECT date,time,code,pcnt,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name FROM ddx;
    " | mysql kts   
    return $?
}

function fn_up()
{
    fn_up_raw
    xt_ret $? "" || return $?
    fn_up_rip
    xt_ret $? "" || return $?

    fn_echo_succ "wolf up succ @${CURR} ${HHMMSS}"
}

function fn_main()
{
    CURR=`fn_maxdate`

    case $1 in
    u|up)
        fn_up
        ;;
    h)
        echo
        ;;

    *)
        echo "
        Usage: wolf <param>...
        up      update database from newest file
        "
        ;;
    esac

    return $?
}

fn_main ${@}
