#! /bin/bash
. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_up_raw()
{
    fn_get_export_file
    xt_ret $? "" || return $?

    # 代码   名称  DDE大单净量  主动买入比  被动买入比  主动卖出比  被动卖出比 
    # 涨幅%  现价  涨速%        总手        换手        金额        流通市值
    iconv -f cp936 -t utf8 ${efile} | tail -n+2 > ${wolf_raw}
    if ! grep -q '^S[HZ]' ${wolf_raw}; then
        fn_echo_fail "not a wolf file"
        return 1
    fi

    tag_blank='--.--.--'
    sed -e 's///g' -e 's/S.//g' -e 's/ //g'               \
        -e 's/%//g' -e 's/\t$//g' -e 's/\t\t*/\t/g'         \
        -e "/${tag_blank}/d" -e '/^$/d' ${wolf_raw} > ${wolf_raw}.mid

    hhmm=`date +%H%M | sed 's/^0//'`;
    #hhmm=1500
    if [ "${hhmm}" -lt 931 ]; then
    # 代码  名称  涨幅  涨速    DDE大单净量 换手 量比   金额    流通市值
        sed '/--.--/d' ${wolf_raw}.mid |\
        awk '{
            printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%.2f\t%.2f\t%s\n", 
            $1,$5, 0,0,0,0,      $3,0,$4,   0,          $6,$8/10000,$9/100000000,$2
        }' \
        | sed "s/^/${CURR}\t${HHMMSS}\t/g" > ${wolf_rip}
    else
        awk '{
            printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%.2f\t%.2f\t%s\n", 
            $1,$3, $4,$5,$6,$7,  $8,$9,$10, $11/10000,  $12,$13/10000, $14/100000000,$2
        }' ${wolf_raw}.mid \
        | sed "s/^/${CURR}\t${HHMMSS}\t/g" > ${wolf_rip}
    fi

    # echo ${efile} ${ctime} ${epoch} $HHMMSS
    
    return $?
}

function fn_up_rip()
{
    echo "
    CREATE TABLE IF NOT EXISTS mat_dde (
        id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
        date        date NOT NULL DEFAULT 0,
        time        time NOT NULL, 
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0,
        net         DECIMAL(6,2) NOT NULL DEFAULT 0, -- dec(p-n)/sum(p+n)
        pbuy        DECIMAL(6,2) NOT NULL DEFAULT 0,
        nbuy        DECIMAL(6,2) NOT NULL DEFAULT 0,
        psell       DECIMAL(6,2) NOT NULL DEFAULT 0,
        nsell       DECIMAL(6,2) NOT NULL DEFAULT 0,
        rise        DECIMAL(6,2) NOT NULL DEFAULT 0,
        trade       DECIMAL(6,2) NOT NULL DEFAULT 0,
        speed       DECIMAL(6,2) NOT NULL DEFAULT 0,
        shou        DECIMAL(8,2) NOT NULL DEFAULT 0,
        tov         DECIMAL(8,2) NOT NULL DEFAULT 0,
        amount      DECIMAL(8,2) NOT NULL DEFAULT 0,
        nmc         DECIMAL(8,2) NOT NULL DEFAULT 0,
        name        CHAR(16),
        INDEX(date,time,code)
    );

    CREATE TABLE IF NOT EXISTS dde LIKE mat_dde;

    DROP   TEMPORARY TABLE IF EXISTS ddx;
    CREATE TEMPORARY TABLE ddx LIKE mat_dde;
    LOAD DATA LOCAL INFILE '${wolf_rip}' INTO TABLE 
           ddx(date,time,code,net,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name);

    DELETE FROM     dde WHERE date='${CURR}';
    INSERT INTO     dde(date,time,code,net,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name)
        SELECT date,time,code,net,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name FROM ddx;

    DELETE FROM mat_dde WHERE date='${CURR}' && time='${HHMMSS}';
    INSERT INTO mat_dde(date,time,code,net,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name) 
        SELECT date,time,code,net,pbuy,nbuy,psell,nsell,rise,trade,speed,shou,tov,amount,nmc,name FROM ddx;
    " | mysql kts   
    return $?
}

function fn_up_dde()
{
    fn_up_raw
    xt_ret $? "" || return $?
    fn_up_rip
    xt_ret $? "" || return $?

    fn_echo_succ "wolf up `wc -l<${wolf_rip}` raws succ @${YYMMDD} ${HHMMSS}"
}

function fn_bbd_database()
{
    echo "
    CREATE TABLE IF NOT EXISTS mat_bbd (
        id          INT PRIMARY key AUTO_INCREMENT NOT NULL,
        date        date NOT NULL DEFAULT 0,
        time        time NOT NULL, 

        rise        DECIMAL(12,2) NOT NULL DEFAULT 0,
        dde         DECIMAL(12,2) NOT NULL DEFAULT 0,

        bbd_net     DECIMAL(12,2) NOT NULL DEFAULT 0,
        bbd_amount  DECIMAL(12,2) NOT NULL DEFAULT 0,
        bbd_buy     DECIMAL(12,2) NOT NULL DEFAULT 0,
        bbd_sell    DECIMAL(12,2) NOT NULL DEFAULT 0,

        up          INT,
        down        INT,
        name        CHAR(16),
        INDEX(date,time,name)
    );

    CREATE TABLE IF NOT EXISTS bbd LIKE mat_bbd;

    DROP   TEMPORARY TABLE IF EXISTS bbx;
    CREATE TEMPORARY TABLE bbx LIKE mat_bbd;
    LOAD DATA LOCAL INFILE '${wolf_rip}' INTO TABLE 
           bbx(date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name);

    DELETE FROM     bbd WHERE date='${CURR}';
    INSERT INTO     bbd(date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name)
        SELECT date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name FROM bbx;

    DELETE FROM mat_bbd WHERE date='${CURR}' && time='${HHMMSS}';
    INSERT INTO mat_bbd(date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name) 
        SELECT date,time,rise,dde,bbd_net,bbd_amount,bbd_buy,bbd_sell,up,down,name FROM bbx;
    " | mysql kts   
    return $?
    
    return $?
}

function fn_up_bbd()
{
    fn_bbd_file
    xt_ret $? "" || return $?
    fn_bbd_database
    xt_ret $? "" || return $?
    fn_echo_succ "BBD up succ @${CURR} ${HHMMSS}"
}

function fn_bbd_file()
{
    fn_get_export_file
    xt_ret $? "" || return $?

    # 代码   名称  机构动向     主动买入比  被动买入比  主动卖出比  被动卖出比 
    # 涨幅%  现价  涨速%        总手        换手        金额        流通市值    所属行业
    iconv -f cp936 -t utf8 ${efile} | tail -n+2 > ${wolf_raw}
    if ! grep -q '机器人概念' ${wolf_raw}; then
        fn_echo_fail "not a bbd file"
        return 1
    fi

    tag_blank='--.--.--'
    sed -e 's///g' -e 's/S.//g' -e 's/ //g'               \
        -e 's/%//g' -e 's/\t$//g' -e 's/\t\t*/\t/g'         \
        -e "/${tag_blank}/d" -e '/^$/d' ${wolf_raw}         \
        | awk '{
            printf "%s\t%s\t%.2f\t%.2f\t%.2f\t%.2f\t%s\t%s\t%s\n",
            $2,$3,$4/10000,$5/10000,$6/10000,$7/10000,$8,$9,$1
        }' \
        | sed "s/^/${CURR}\t${HHMMSS}\t/g" > ${wolf_rip}
    xt_ret $? "" || return $?

    # echo ${efile} ${ctime} ${epoch} $HHMMSS
}

function fn_layout_bbd()
{
    sqls="
    SELECT l.code,count(l.code) as num, c.name FROM 
        (SELECT m.code FROM (
            SELECT name FROM bbd ORDER by bbd_amount DESC LIMIT ${LIMIT:-2}) as t, 
            blk_name as n, blk_memb as m 
            WHERE n.sym=t.name && n.blk=m.blk) as l, cap as c 
    WHERE l.code=c.code 
    GROUP by code 
    HAVING 1 ${COND}
    ORDER by num DESC
    " 
    mysql ${OPT:--t} kts <<<"${sqls}"
    fn_chao ${chao}.bbd
}

function fn_zxg()
{
    fn_up_raw
    xt_ret $? "" || return $?
    cat ${wolf_rip} | awk '{printf "%s\t%s\n", $3, $NF}' | sed "s/^/$1/g"
    return $?
}

function fn_main()
{
    CURR=`fn_maxdate`

    case $1 in
    u|up)
        fn_up_dde
        ;;
    b|bbd)
        fn_up_bbd
        ;;
    l|layout_bbd)
        fn_layout_bbd
        ;;
    z|zxg)
        fn_zxg ${@:2}
        ;;
    h|*)
        echo "
        Usage:  wolf <param>...             (4/3):1 14.28   门槛
        up      # DDE                       (3/2):1 20      登堂
        bbd     # 操盘热点导入              (5/3):1 25      入室
        layout  # 热点layout，观察概念叠加  (2/1):1 33      太极
        zxg     # 打印自选股
        "
        ;;
    esac

    return $?
}

fn_main ${@}
