#! /bin/bash

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_routine()
{
    grep -v '^#' .soptter.macd |
    while read code symble FM cond1 op cond2 tips; do
        if [ "${code}" = '-' ]; then
            code=$code0
        elif [ -z "${DT}" ]; then   # DT不指定，则从网络更新fenbi数据
            fenbi ${code} >& ${SUBOUT}
            xt_ret $? "down ${i} error" || return $?
        fi
        FM=${FM} macd ${code}
        sql="SELECT IF(${cond1} ${op} ${cond2}, 1, 0) FROM ma20macd WHERE code=${code} and fish=${FM}"
        ret=`mysql -N kts <<<"${sql}"`

        if [ "${ret}" = 1 ]; then
            fn_echo_succ "$code.$symble.$FM $cond1 $op $cond2"
            fn_echo_warn "$tips"
        elif [ "${ret}" = "" ]; then
            fn_echo_fail "bad condition ${code}: ${cond1} ${op} ${cond2}"
        fi
        code0=$code
    done
}

function fn_main()
{
    while :; do
        hhmmss=`date +%H:%M:%S`
        echo PATROL@${hhmmss}
        fn_routine
        [ -n "${DT}" ] && exit      # DT指定，即时退出
        sleep 120
    done
    return $?
}

fn_routine
# fn_main ${@}
