#! /bin/bash -
#---------------------------------------------------------------------------
#          FILE: xunner
#         USAGE: ./xunner
#   DESCRIPTION: 
#       CREATED: 2014-03-17 04:44:53 PM
#      REVISION: 1.0 
#---------------------------------------------------------------------------


#             000001
#             shanghai-idx
#             2023.67         trade
#             0.96            change
#             2004.34         yesclose
#             2009.88         open
#             86250374        volumn
#             720.18          amount
#             2024.37         high
#             1999.25         low
# 000002
# WKA
# 7.76        trade
# 3.05        change
# 7.53        yesclose
# 7.60        open
# 7.80        high
# 7.59        low
# 1177079     volumn
# 908293030   amount
# 1.22        turnov
# 2.79        swings
# 0.74        vratio

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_xunner()
{
    # w3m -dump 'http://quote.stock.hexun.com/stockdata/stock_quote.aspx?
    # stocklist=000002|000001&indexlist=000001_1|399001_2|399006_2'

    sed '/indexdataArr/Q' ${js_xunner} > ${js_xunner_stk}
    sed -n  '/indexdataArr/,$p' ${js_xunner} > ${js_xunner_idx}

    printf "%6s\t%s\t%s\t\t%s\t%s\t%-5s\t%5s\t%5s\t%5s\n" \
            symbol avrg trade change pcnt_hi pcnt_lo turnov vratio name

    cat ${js_xunner_idx} | \
        tr -d '\n' | tr "'" '"' | \
        sed -e 's/^.*= *//' -e 's/;.*$//' | \
        sed -e 's/[a-z][a-z][a-z]*/"&"/g' -e 's/;.*//g' | \
        JSON.sh -b | tr -d '"' | \
        awk '{printf "%s\t%.2f\t%.2f\t\t%.2f\t%.2f\t%.2f\t\t\t\t\t%s\n", 
                $1,10.00,$3,$4, 100*($3-$9)/$5, 100*($3-$10)/$5, $2}'

    cat ${js_xunner_stk} | \
        tr -d '\n' | tr "'" '"' | \
        sed -e 's/^.*= //' -e 's/;.*$//' | \
        sed -e 's/[a-z][a-z][a-z]*/"&"/g' -e 's/;.*//g' | \
        JSON.sh -b | tr -d '"' | \
        awk '{printf "%s\t%.2f\t%.2f\t\t%.2f\t%.2f\t%.2f\t%.2f\t%.2f\t%s\n", 
                $1,(100*$3-$10/($9+0.00001))/($3+0.00001),
                $3,$4, 100*($3-$7)/$5, 100*($3-$8)/$5, $11, $13, $2
        }' | sort -g -r -k4

    printf "%6s\t%s\t%s\t\t%s\t%s\t%-5s\t%5s\t%5s\t%5s\n" \
            symbol avrg trade change pcnt_hi pcnt_lo turnov vratio name
}


function fn_main() 
{
    url='http://quote.stock.hexun.com/stockdata/stock_quote.aspx?'
    url="${url}stocklist=`cat ${LIST:-.soptter} | xargs | sed 's/ /\|/g'`"
    url="${url}&indexlist=000001_1|399001_2|399006_2"

    # trim *ST individuals
    w3m -dump "${url}" 2>&1 | \
        sed -e 's/;indexdataArr/;\nindexdataArr/' \
            -e 's/*//g'  -e 's/ST//g'  > ${js_xunner} 

    fn_xunner
}

fn_main $@

