#! /bin/bash -

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_get_url()
{
    url="http://data.eastmoney.com/bbsj/stock${code}/yjbb.html"

    # 默认使用 RAW for detail
    if [ "${RAW}" != 1 ]; then
        w3m -dump ${url} | grep -A24 "点击进入年报大全"
        return 0
    else
        earning=(`w3m -dump ${url} | grep -m1 '^1[345]' | awk '{print $2, $8}'`)
        test -n "${earning[*]}"
        xt_ret $? "" || return $?

        echo "
        SELECT cap.name, d.code, round(d.close/${earning[0]},2) as EPS, 
            round(d.close/${earning[0]}/${earning[1]},2) as PEG,
            cap.nmc FROM day as d, cap
            WHERE  d.code=${code} and d.date='${END}' and d.code=cap.code;
        " | mysql -N kts
        xt_ret $? "" || return $?
    fi
}

function fn_online()
{
    CURR=`fn_maxdate`
    END=${END:-${CURR}}

    for code in $@; do
        fn_iscode ${code}
        xt_ret $? "" || return $?

        fn_get_url
        return $?
    done
}

function fn_load()
{
    if [ ! -f "${1}" ]; then
        echo "Redo after try: cp .template/yjbb_rip ${yjbb_rip}"; exit 1
    fi

    timestamp=`head -1 /dev/shm/yjbb_rip | awk '{print $1}'`
    echo "Delete data of ${timestamp} and load ${yjbb_rip}..."

    echo "
    -- DROP TABLE IF EXISTS tbl_yjbb;
    CREATE TABLE IF NOT EXISTS tbl_yjbb (
        date        date NOT NULL DEFAULT 0,
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0,
        EPS         DECIMAL(10,4) NOT NULL DEFAULT 0,
        revenue     DECIMAL(12,2) NOT NULL DEFAULT 0,
        r_grw_y     DECIMAL(10,2) NOT NULL DEFAULT 0,
        r_grw_q     DECIMAL(10,2) NOT NULL DEFAULT 0,
        profit      DECIMAL(12,2) NOT NULL DEFAULT 0,
        p_grw_y     DECIMAL(10,2) NOT NULL DEFAULT 0,
        p_grw_q     DECIMAL(10,2) NOT NULL DEFAULT 0,
        netassets   DECIMAL(10,4) NOT NULL DEFAULT 0,
        RoE         DECIMAL(10,2) NOT NULL DEFAULT 0,
        cashflow    DECIMAL(10,2) NOT NULL DEFAULT 0,
        INDEX(code,date)
    --  grossMgn    DECIMAL(10,2) NOT NULL DEFAULT 0
    );
    -- TRUNCATE tbl_yjbb;
    DELETE FROM tbl_yjbb WHERE date=${timestamp};
    LOAD DATA LOCAL INFILE '$1' INTO TABLE tbl_yjbb;
    " | mysql kts
    xt_ret $? "" || return $?

    fn_echo_succ "LOCAL INFILE '$1'"
}

function fn_dl_all()
{
    # [ "${#}" -eq 0 ] && fn_main

    echo "DL from http://data.eastmoney.com/bbsj/${1}/yjbb.html"

    date=${1:-'2014-12-31'}

    fn_url() 
    { 
        url0="http://datainterface.eastmoney.com/EM_DataCenter/JS.aspx?type=SR&sty=YJBB&"
        url0="${url0}fd=${date}&st=13&sr=-1&p=1&ps=3000"
    }
    fn_url
    w3m -dump ${url0} > ${yjbb_raw}
    if ! grep -q "${date}" ${yjbb_raw}; then
        fn_echo_fail "no ${date} data"
        exit 1
    fi
    cat ${yjbb_raw} |tr -d '\n' |
        sed -e '1s/^...//' -e '1s/...$//' -e 's/","/\n/g' | 
        awk -F',' '{
            printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n",
            $1,$3,$5/10000,
            $6,$7,$8/10000,
            $9,$10,$11,
            $12,$13
        }' | grep "^[036]" > ${yjbb_rip}

    sed -i "s/^/${date}\t/" ${yjbb_rip}
    sort -g -k2 ${yjbb_rip} -o ${yjbb_rip}

    fn_load ${yjbb_rip}

    return $?
}


function fn_detail()
{
    # 季度报表的所有项目分两个：环比数据，
    #                           同比数据，年初至报告期(所以EPS计算应该进行时间校正)

    # EPS    每股收益，PE=(close/EPS)
    # revenue营业额，必须配合ROE增长，如此才是可持续的。因缩减成本之节流不如开源。
    # r_grw_y
    # profit 直接反映企业的“赚钱能力”，1个亿起步，若1年只几百万，还不如一个个体户赚得多呢。
    # p_grw_y
    # ROE    净资产收益率 = 凈收入／股東股本，体现企业盈利能力，应该大于20%——10%以下免谈
    #        要配合这三个要素来看，一是利润率，二是总资产周转率，三是财务杠杆也就是（总资产/净资产）
    #        要结合着看，不需要太高不需要太低，要维持稳定。基本上每年大于15%

    # gross  产品毛利率——要高、稳定而且趋升，
    #        彩电行业，近10年来产品毛利率一直在逐年下降；而白酒行业产品毛利率却一直都比较稳定。

    # 季度环比数据 r_grw_q, p_grw_q 有时会是空数据0

    #olumns='code,EPS,revenue,r_grw_y,r_grw_q,profit,p_grw_y,p_grw_q,netassets,RoE,cashflow'
    columns='y.date,y.code,round(c.close/EPS,2) as PE'
    columns=${columns}',round(c.close/EPS/p_grw_y,2) as PEG'
    columns=${columns}',revenue,r_grw_y,profit,p_grw_y,netassets,RoE'
    CURR=`fn_maxdate`
    
    # SELECT name ${CODE}
    # 保持每日cap的更新
    if [ -z "${YIST}" ]; then
        fn_iscode $1 
        xt_ret $? "" || { echo "Usage: 120 code... {END}" && exit; }
        YIST=${file_ma120}
        xargs -n1 <<<"${*}" | sed 's/^0*//g' | xargs printf "%06d\n" > ${YIST}
    fi

    fn_yist 
    echo ----- LIST:${#LIST[@]} COND@${END}: $COND -----

    echo "
    SELECT $columns, c.nmc, c.name FROM tbl_yjbb as y, cap as c
        WHERE y.code=c.code 
        HAVING 1 ${COND} ${inLIST} 
        ORDER by code,${field:-date} ${ASC:-DESC} limit ${LIMIT:-48};
    " | mysql -t kts
    
    return $?
}


function fn_soptter()
{
    echo "
    SELECT *, count(code) as count FROM tbl_yjbb WHERE p_grw_y>15 and RoE > 10 GROUP by code ORDER by count DESC LIMIT 100;
    "
    return $?
}

function fn_main()
{
    case $1 in
   #1|online)
   #    fn_online "${@:2}"
   #    ;;
    1|detail)
        fn_detail "${@:2}"
        ;;
    3|dl_all)
        fn_dl_all "${@:2}"
        ;;
    4|load)
        fn_load "${@:2}"
        ;;
    5|soptter)
        fn_soptter "${@:2}"
        ;;
    6|ls_date)
        mysql -t kts <<< "SELECT DISTINCT date FROM tbl_yjbb";
        ;;
    7|dele)
        [ -z "${2}" ] && fn_main
        mysql -t kts <<< "DELETE FROM tbl_yjbb WHERE date=${2}";
        ;;
    *)
        echo "Usage: 
        yjbb {1|detail}     code...
        yjbb {3|dl_all}     20yy-mm-dd
        yjbb {4|load}       file
        yjbb {5|soptter}
        yjbb {6|ls_date}
        yjbb {7|dele}       20yy-mm-dd
        "
        exit
        ;;
    esac

    return $?
}
# 数据的延时在30s内
fn_main $@
