#! /bin/bash -

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_load()
{
    if [ ! -f "${1}" ]; then
        echo "Redo after try: cp .template/yjyg_rip ${yjyg_rip}"; exit 1
    fi

    # timestamp=`head -1 /dev/shm/yjyg_rip | awk '{print $1}'`
    # echo "Delete data of ${timestamp} and load ${yjyg_rip}..."

    echo "
    DROP TABLE IF EXISTS tbl_yjyg;
    CREATE TABLE IF NOT EXISTS tbl_yjyg (
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0,
        pcnt        DECIMAL(10,2) NOT NULL DEFAULT 0,
        type        INT(2) NOT NULL DEFAULT 0,
        profip      DECIMAL(14,2) NOT NULL DEFAULT 0,
        profit      DECIMAL(14,2) NOT NULL DEFAULT 0,
        public      date NOT NULL DEFAULT 0,
        date        date NOT NULL DEFAULT 0,
        name        CHAR(16),
        INDEX(code,date)
    );
    -- TRUNCATE tbl_yjyg;
    -- DELETE FROM tbl_yjyg WHERE date=${timestamp};
    LOAD DATA LOCAL INFILE '$1' INTO TABLE tbl_yjyg;
    " | mysql kts
    xt_ret $? "" || return $?

    fn_echo_succ "LOCAL INFILE '$1'"
}

function fn_dload()
{
    date=${1:-'2015-06-30'}

    fn_url() 
    { 
        url0="http://datainterface.eastmoney.com/EM_DataCenter/JS.aspx?type=SR&sty=YJYG&"
        url0="${url0}fd=${date}&st=4&sr=-1&p=1&ps=3000"
        echo "DL from ${url0}"
    }
    fn_url
    w3m -cols 1000 -dump ${url0} > ${yjyg_raw}
    if ! grep -q "${date}" ${yjyg_raw}; then
        fn_echo_fail "no ${date} data"
        exit 1
    fi

    # 预亏    -3
    # 预减    -2
    # 减亏    -1
    # 持平    0
    # 预警    0
    # 预盈    1
    # 预增    2
    cat ${yjyg_raw} |tr -d '\n' |
        sed -e '1s/^...//' -e '1s/...$//' -e 's/","/\n/g' |
        sed -e 's/预亏/-3/g' -e 's/预减/-2/g' -e 's/减亏/-1/g' -e 's/持平/0/g' \
            -e 's/预警/0/g' -e 's/预盈/1/g' -e 's/预增/2/g' > ${yjyg_rip}.pre
    cat ${yjyg_rip}.pre |
        awk -F',' '{
            if ($6>=0) {
                printf "%s\t%.2f\t%d\t%s\t%.2f\t%s\t%s\t%s\n", 
                    $1,$4,$5,$6,$6*($4/100+1),$8,$9,$2
            } else {
                printf "%s\t%.2f\t%d\t%s\t%.2f\t%s\t%s\t%s\n", 
                    $1,$4,$5,$6,$6*(1-$4/100),$8,$9,$2
            }
        }' | grep "^[036]" > ${yjyg_rip}

    #sort -g -k2 ${yjyg_rip} -o ${yjyg_rip}

    fn_load ${yjyg_rip}

    return $?
}


function fn_select()
{
    fn_yist 
    echo ----- LIST:${#LIST[@]} COND@${END}: $COND -----

      # -- and pcnt>0 and type>0
    echo "
    SELECT y.*, 10000*c.close/(profit/(c.cap/c.close)) as PE, c.nmc,c.shares
        FROM tbl_yjyg as y, cap as c 
        WHERE y.code=c.code 
        -- and type>0 and pcnt>100
        HAVING 1 ${COND} ${inLIST} 
        ORDER by ${1:-PE} ASC LIMIT ${LIMIT:-50}
    " | mysql -t kts
    
    return $?
}

function fn_main()
{
    case $1 in
    1|dload)
        fn_dload "${@:2}"
        ;;
    2|select)
        fn_select "${@:2}"
        ;;
    *)
        echo "Usage: 
        yjyg {1|dload}      code...
        yjyg {2|select}
        "
        exit
        ;;
    esac

    return $?
}

fn_main $@
