#! /bin/bash -

. `dirname ${0}`/'dbank' || { echo "dbank err" && exit; }
. /etc/common.rc

function fn_load()
{
    if [ ! -f "${1}" ]; then
        echo "Redo after try: cp .template/yjyg_rip ${yjyg_rip}"; exit 1
    fi

    # timestamp=`head -1 /dev/shm/yjyg_rip | awk '{print $1}'`
    # echo "Delete data of ${timestamp} and load ${yjyg_rip}..."

    echo "
    DROP TABLE IF EXISTS tbl_yjyg;
    CREATE TABLE IF NOT EXISTS tbl_yjyg (
        code        INT(6) ZEROFILL NOT NULL DEFAULT 0,
        pcnt        DECIMAL(10,2) NOT NULL DEFAULT 0,
        type        INT(2) NOT NULL DEFAULT 0,
        profip      DECIMAL(14,2) NOT NULL DEFAULT 0,
        profit      DECIMAL(14,2) NOT NULL DEFAULT 0,
        public      date NOT NULL DEFAULT 0,
        date        date NOT NULL DEFAULT 0,
        name        CHAR(16),
        INDEX(code,date)
    );
    -- TRUNCATE tbl_yjyg;
    -- DELETE FROM tbl_yjyg WHERE date=${timestamp};
    LOAD DATA LOCAL INFILE '$1' INTO TABLE tbl_yjyg;
    " | mysql kts
    xt_ret $? "" || return $?

    fn_echo_succ "LOCAL INFILE '$1'"
}

function fn_dload()
{
    date=${1:-'2015-12-31'}

    fn_url() 
    { 
        url0="http://datainterface.eastmoney.com/EM_DataCenter/JS.aspx?type=SR&sty=YJYG&"
        url0="${url0}fd=${date}&st=4&sr=-1&p=1&ps=3000"
        echo "DL from ${url0}"
    }
    fn_url
    w3m -cols 1000 -dump ${url0} > ${yjyg_raw}
    if ! grep -q "${date}" ${yjyg_raw}; then
        fn_echo_fail "no ${date} data"
        exit 1
    fi

    cat ${yjyg_raw} |tr -d '\n' |
        sed -e '1s/^...//' -e '1s/...$//' -e 's/","/\n/g' |
        sed -e 's/预亏/-3/g' -e 's/预减/-2/g' -e 's/减亏/-1/g' -e 's/持平/0/g' \
            -e 's/预警/0/g' -e 's/预盈/1/g' -e 's/预增/2/g' > ${yjyg_rip}.pre
    cat ${yjyg_rip}.pre |
        awk -F',' '{
            if ($6>=0) {
                printf "%s\t%.2f\t%d\t%s\t%.2f\t%s\t%s\t%s\n", 
                    $1,$4,$5,$6,$6*($4/100+1),$8,$9,$2
            } else {
                printf "%s\t%.2f\t%d\t%s\t%.2f\t%s\t%s\t%s\n", 
                    $1,$4,$5,$6,$6*(1-$4/100),$8,$9,$2
            }
        }' | grep "^[036]" > ${yjyg_rip}

    #sort -g -k2 ${yjyg_rip} -o ${yjyg_rip}

    fn_load ${yjyg_rip}

    return $?
}


function fn_select()
{
    fn_yist 
    echo ----- LIST:${#LIST[@]} COND@${END}: $COND -----

    columns="date,public,code,pcnt,type"
    columns=y.${columns//,/,y.}

    sqls="
    SELECT ${columns}, 
        round(profip/100000000,2) as prev, 
        round(profit/100000000,2) as curr,
        round(profit/(c.cap/c.close)/10000,2) as Eps,
        round(10000*c.close/(profit/c.shares), 2) as PE, 
        round(c.nmc/10000,1) as nmc, c.name
        FROM tbl_yjyg as y, cap as c 
        WHERE y.code=c.code 
        HAVING 1 ${COND} ${inLIST} 
        ORDER by ${FIELD:-public} DESC LIMIT ${LIMIT:-50}
    " 
    mysql -t kts <<< "${sqls}"
    fn_chao ${chao}.Yjyb
    
    return $?
}
function fn_layout()
{
    echo "
    SELECT date, public, count(code) FROM tbl_yjyg GROUP by public  
        ORDER by public DESC
    " | mysql -t kts
}

function fn_main()
{
    case $1 in
    l|layout)
        fn_layout
        ;;
    s|select)
        fn_select "${@:2}"
        ;;
    d|dload)
        fn_dload "${@:2}"
        ;;
    *)
        echo "
    Usage: 
        Yjyg {l|layout}                 # public日期分布
        Yjyg {s|select}                 # SELECT
        Yjyg {d|dload}  [2015-xx-xx]    # 下载YJYG

    type:
        -3  预亏    
        -2  预减        prev+ curr+ profit -20%+
        -1  减亏    
         0  持平/预警   prev+ curr+ profit -10%
         1  预盈/扭亏   prev- curr+
         2  预增        prev+ curr+

    常用条件:
        COND=\"nmc<200&&public='2015-10-15' && type=2\" Yjyb 2 pcnt
        "
        exit
        ;;
    esac

    return $?
}

fn_main $@
